### ISSUE TITLE
Use better icons for status

### ISSUE THREAD

**Issue by siduck76** [williamboman/nvim-lsp-installer#109]
Hi @williamboman great plugin! I think the icons for lspservers status could be changed , you could choose the circle tick icon 
from nerdfonts-cheatsheet : 

![image](https://user-images.githubusercontent.com/59060246/135391999-7250137c-d04b-41a8-9a55-c27720c23d02.png)

![image](https://user-images.githubusercontent.com/59060246/135391622-f83918ab-17ed-4b28-9e92-b4b37b35e666.png)

![image](https://user-images.githubusercontent.com/59060246/135391695-abeeca3f-d55f-482d-a738-0fda94462c17.png)

**Comment by williamboman** [comment]
Hey! Yeah the icons could be a bit better I guess. I'm not too sure about using a nerdfont glyph as default, but perhaps making this configurable instead? [In fact it's already on my todo list apparently :D](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/ui/status-win/init.lua#L26-L27)

**Comment by siduck76** [comment]
> Hey! Yeah the icons could be a bit better I guess. I'm not too sure about using a nerdfont glyph as default, but perhaps making this configurable instead? [In fact it's already on my todo list apparently :D](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/ui/status-win/init.lua#L26-L27)

agreed that would be better.
