### ISSUE TITLE
Clangd is not completting

### ISSUE THREAD

**Issue by XtraSavx** [williamboman/nvim-lsp-installer#115]
Hi i´m here again. 😀

Well I do this issue because as I could already install clangd, now that I wanted to make a .c file it does not give me the autocompletion option, but, when I write and repeat again, the "option" appears.
autocomplete but with buffer, if I do it in a .vim or .lua file if I get the autocomplete option.

Could you help me to know what the problem is? 🤔😅

Here are some evidences:
.vim file
![image](https://user-images.githubusercontent.com/81933734/135694465-ccfb337d-5702-4dce-b3bd-a0837246c759.png)

.c file 
In this part I want to write **int**, but I don´t see that the autocomplete is working in .c files
![image](https://user-images.githubusercontent.com/81933734/135694560-d3a3aec5-226e-43df-b87a-b7333f7cb6cb.png)

**Comment by TeoDev1611** [comment]
@XtraSavx  Hi some times the lsp is slow connecting the servers can you check if when open a C file run `:LspInfo` see clangd attached to this buffer?

**Comment by XtraSavx** [comment]
> @XtraSavx Hi some times the lsp is slow connecting the servers can you check if when open a C file run `:LspInfo` see clangd attached to this buffer?

Yes, I can see clangd
![image](https://user-images.githubusercontent.com/81933734/135698730-8d83e8f2-dd4a-49b9-9a89-26cb2597f2f8.png)

**Comment by TeoDev1611** [comment]
@XtraSavx  This is relative normal to the binaries of language servers or the .bat or script files because takes some time add the complete can you test the completion after 30 seg this can be solve your problem.

Or can you send the issue to the `nvim-lspconfig` repository for make this more faster i think. What you think @williamboman ?

**Comment by williamboman** [comment]
From what I can see the server is successfully installed, which is where the scope of this plugin ends. I am not having any issues personally with clangd. Probably something else going on

**Comment by XtraSavx** [comment]
> From what I can see the server is successfully installed, which is where the scope of this plugin ends. I am not having any issues personally with clangd. Probably something else going on

Can I put this issue in the lsp-config?

**Comment by williamboman** [comment]
> Can I put this issue in the lsp-config?

I don't think this is an issue with lspconfig either. If I had to guess it's either caused by

1) some other plugin
1) certain combination of plugins that triggers the issue
1) some personal config

Do you use null-ls? https://github.com/jose-elias-alvarez/null-ls.nvim/issues/229

**Comment by XtraSavx** [comment]
> > Can I put this issue in the lsp-config?
> 
> I don't think this is an issue with lspconfig either. If I had to guess it's either caused by
> 
> 1. some other plugin
> 2. certain combination of plugins that triggers the issue
> 3. some personal config
> 
> Do you use null-ls? [jose-elias-alvarez/null-ls.nvim#229](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/229)

Ok thanks, i´m gonna check that. 😀👏

**Comment by williamboman** [comment]
Good luck 😄

**Comment by mayankdutta** [comment]
https://github.com/williamboman/nvim-lsp-installer/issues/116#issuecomment-933446758

had same issue, this worked for me for macos.
