### ISSUE TITLE
Some servers fail to install when wget not availible

### ISSUE THREAD

**Issue by casonadams** [williamboman/nvim-lsp-installer#126]
When a system doesn't have `wget` some servers fail to install.

Example:
`LspInstall sumneko_lua`

Error:
```
[INFO  Mon Oct  4 22:58:34 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:286: Starting install server_name="sumneko_lua", requested_version="N/A"
[ERROR Mon Oct  4 22:58:34 2021] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:121: Failed to spawn process wget ENOENT: no such file or directory
[INFO  Mon Oct  4 22:58:34 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:305: Installation completed server_name="sumneko_lua", success=false
```

Would be nice to send a message to message window with more info.

**Comment by nyngwang** [comment]
I just want to create the same issue. I think it's valuable to emphasize this for macOS users, by maybe a line like this:

For macOS users, you might need to install `wget` to install some language-servers via [homebrew](https://brew.sh/):

```
brew install wget
```

**Comment by williamboman** [comment]
And here I was assuming macOS ships with wget installed. What about curl? Is that available?

**Comment by williamboman** [comment]
As for somewhat better error messages, added in d00fbe2058dbd175d2ff8d6f78b6f099a0fbdbd1

<img width="892" alt="Screenshot 2021-10-05 at 14 40 03" src="https://user-images.githubusercontent.com/6705160/136024179-499b083c-a647-4de0-955b-251ab5c06068.png">

**Comment by williamboman** [comment]
And here's a patch replacing `wget` with `curl` https://github.com/williamboman/nvim-lsp-installer/pull/129. I originally went with `wget` because in my own experience it's often shipped with the OS.

I might actually change it so that it falls back to the other one if the first is not installed. I can't imagine someone not having either `wget` or `curl` installed
