### ISSUE TITLE
clangd.bat not working well

### ISSUE THREAD

**Issue by grimgort** [williamboman/nvim-lsp-installer#127]
Hello,
When I go through clangd.bat, I get the error below, while I have a local clangd.exe that works fine. Why don't I go directly to a clangd.exe?
![image](https://user-images.githubusercontent.com/44238325/135998775-e99d2692-c496-4689-b5a6-6d90114933c4.png)
![image](https://user-images.githubusercontent.com/44238325/135998982-02dfc077-98e7-4265-9d40-9b90e3ad6520.png)

**Comment by williamboman** [comment]
Hey it seems like the error message is a bit cut off? What's the full error message? How do you trigger the error message, are you doing any LSP interactions or does it just show up by itself?

**Comment by grimgort** [comment]
it s with this lsp function : 
buf_set_keymap("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", opts)
