### ISSUE TITLE
[Feature] add Julia support

### ISSUE THREAD

**Issue by jvaverka** [williamboman/nvim-lsp-installer#143]
Execute LanguageServer.jl when opening Julia files.

**Comment by Jdbeck66** [comment]
I’d like to add support for nudging this along as well.

**Comment by williamboman** [comment]
coc-julia seems to do [something interesting](https://github.com/fannheyward/coc-julia/blob/master/src/index.ts#L16-L23).  I've only taken a glance at it, but it seems like they compile the bundled JuliaLS package (which calls into LanguageServer). What it compiles into I have no idea, and I have yet to actually try the coc extension.

**Comment by solidassassin** [comment]
@williamboman it compiles to sysimage (compiled julia session) or binary (self explanatory), I don't use Julia regularly, but I remember that jaot compilation times are notoriously long, so this improves startup time significantly (instant startup as opposed to ~30s). As for package management delegation to Julia I honestly think it would be way more efficient to set up a Github action to compile to releases and then grab it from there (preferably to executable so dependencies would be bundled, which wouldn't oppose the original idea of lsp-installer). That's just my take tho.

**Comment by williamboman** [comment]
Ah I see, thanks for the info! I'm however not going to write and/or host a repository of prebuilt binaries for the Julia LSP myself (I'd barely even consider doing this for servers I personally use every day). This sounds like something that could instead be incorporated in the release pipeline of https://github.com/julia-vscode/LanguageServer.jl itself? I'd also be happy to use a 3rd party vendor if someone wants to maintain and host one!

> preferably to executable so dependencies would be bundled, which wouldn't oppose the original idea of lsp-installer

I'm not sure I'm following this sentence 🙈. Do you mean preferably it'd provide prebuilt binaries (in which dependencies are bundled)?

**Comment by solidassassin** [comment]
> Do you mean preferably it'd provide prebuilt binaries (in which dependencies are bundled)?

Yup. I'll probably try to set up a repo which generates releases with actions requiring as less manual maintenance as possible (since I'm already dealing with university and a full time job :smiley: ), tho I really doubt that you would require active maintenance for something like this (unless breaking changes in `PackageCompiler`, `LanguageServer` or Julia itself are frequent).

**Comment by williamboman** [comment]
We might have a pretty simple solution to this, please see branch `add-julials` (#429) - does it work as expected?

**Comment by hasundue** [comment]
@williamboman It works almost perfectly.
Sure, it's better to have all the necessary things under the plugin's control.

The problem is that the language server can't locate the instances of dependent packages the file under the edit, even if you Pkg.instantiate(), because the server is running in an isolated an minimal environment which only have LanguageServer and SymboicServer packages.

![image](https://user-images.githubusercontent.com/309723/149686603-8ae0b03a-8b3b-42e8-ad32-745ef2155d16.png)

I'm looking into how vscode deals with this problem.

**Comment by hasundue** [comment]
My bad. I just didn't put dependent packages in my Project.toml.

As long as I have necessary packages in Project.toml and done Pkg.instantiate(), the plugin seems working properly.

![image](https://user-images.githubusercontent.com/309723/149734929-13b62dcd-cb90-49fe-9e65-546c6b07a62a.png)

**Comment by 00sapo** [comment]
I think that using DEPOT_PATH is not the best because in that way the user could have multiple packages around without it knows it. I think that it would be better to delegate the package management to Julia, which is superior in doing this

**Comment by 00sapo** [comment]
Ah, I see that the JULIA_DEPOT_PATH is always only one, and this makes the logic better than what I was thinking. However, it looks over-complex to me and I would prefer to delegate it to Julia which is much more reliable than us for future bugs (especially for a so little used feature such as JULIA_DEPOT_PATH that may receive little attention for strange bugs)

**Comment by williamboman** [comment]
> I think that using DEPOT_PATH is not the best because in that way the user could have multiple packages around without it knows it. I think that it would be better to delegate the package management to Julia, which is superior in doing this

To be honest I don't fully understand what this means haha :grimacing:, much of this is replicated from how VSCode does it. As I understand it, the JULIA_DEPOT_PATH will only be local to the language server "project" itself - you'll still manage your projects' Julia deps as usual.

**Comment by williamboman** [comment]
So at this point there's nothing more I can think of that needs to go into #429. Thanks for the assistance and initiative @hasundue :pray: and thanks everyone else for your inputs. I'll go ahead and just merge it tomorrow or so, we can easily do further improvements in future PRs should there be any.

**Comment by jvaverka** [comment]
I'm happy to test (Ubuntu + Windows) once merged.
Thank you all!
