### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by xdavidel** [williamboman/nvim-lsp-installer#145]
Currently I notice there is no ARM support - so running on a raspberry pi or even
in Termux (Android) would no work.

I realize that some / most of the servers are being downloaded from the corresponding release page and therefore the pc architecture is none exitances...

**Comment by xdavidel** [comment]
Yes, I know it's not the plugin's fault basically...

I, for example tried out sumneko_lua and clangd - both downloaded server binaries for x86 processor

I guess another option would be to search for the system path for existing server.

**Comment by shaunsingh** [comment]
I'm on an m1 machine (macOS, aarch64-darwin), and it installs/runs fine. I believe its running through x86 emulation though. 

Just wondering, if you install a language server/plugin through vscode, does it install a "native" version of the server?

**Comment by xdavidel** [comment]
> I'm on an m1 machine (macOS, aarch64-darwin), and it installs/runs fine. I believe its running through x86 emulation though.
> 
> Just wondering, if you install a language server/plugin through vscode, does it install a "native" version of the server?

Didn't try that - all my arm based hardware is tty based.

**Comment by williamboman** [comment]
I'm not sure there's any action to take in this plugin (correct me if I'm wrong). I suggest you to file issues with the LSP servers themselves if you want them to distribute ARM builds. We could of course implement the build steps directly in this plugin, but that's a route I'm not too keen on going down unless there are no other options. I think the more robust infra would be to have distributors provide builds directly
