### ISSUE TITLE
proxy support for pip

### ISSUE THREAD

**Issue by grimgort** [williamboman/nvim-lsp-installer#150]
hello,

sorry for the inconvenience, but python pip asks for the "--proxy=" argument when you are behind a proxy (and I can't find a global configuration for pip). Is it possible to add a proxy option for pip.

**Comment by williamboman** [comment]
Hey! I think it would make sense to add this as a setting. I've experienced similar issues with npm behind proxies, so might be a good opportunity to look into that as well.

**Comment by williamboman** [comment]
Yikes, ok. Let's add a setting and see if that helps 😅
