### ISSUE TITLE
[Feature] Allow users to install servers via Language Name

### ISSUE THREAD

**Issue by shaunsingh** [williamboman/nvim-lsp-installer#157]
With the now deprecated https://github.com/kabouzeid/nvim-lspinstall, I used to install language servers via the language name e.g. `:LspInstall lua`. With this plugin, you have to give the server name e.g. `:LspInstall sumneko_lua`, It gets a bit hard remembering all the names, and I have to check the readme every once in a while to find the server I need

Is it possible, along with the names of the servers themselves, to let users install via the language name?

**Comment by williamboman** [comment]
Hey! Ah I did not realize that plugin was deprecated :O, this one was originally very much inspired by it. Anyways, I coincidentally wrote a [comment recently](https://github.com/williamboman/nvim-lsp-installer/pull/117#issuecomment-944554273) about some ideas, will try to push this forward ASAP.
