### ISSUE TITLE
Completion with ansiblels is not functioning properly after setup with lsp-installer

### ISSUE THREAD

**Issue by ghillb** [williamboman/nvim-lsp-installer#160]
With the config (below screenshot) for nvim-lsp-installer and after installing ansiblels via `:LspInstall ansiblels` there occurs an error (screenshot), when typing in yaml files.

![2021-10-16-202226_1916x1046_scrot](https://user-images.githubusercontent.com/35503959/137598779-43d78837-e89b-4b26-9755-2255403e0169.png)

```
local ok, lsp_installer = pcall(require, 'nvim-lsp-installer')
if not ok then
  return
end

lsp_installer.settings {
  ui = {
    icons = {
      server_installed = "✓",
      server_pending = "➜",
      server_uninstalled = "✗"
    }
  }
}

lsp_installer.on_server_ready(function(server)
    local opts = {}

    if server.name == "ansiblels" then
      opts.settings = {
        ansible = {
          ansible = {
            path = "ansible"
          },
          ansibleLint = {
            enabled = true,
            path = "ansible-lint"
          },
          python = {
            interpreterPath = "python3"
          }
        }
      }
    end

    server:setup(opts)
    vim.cmd [[ do User LspAttachBuffers ]]
end)
```
Used config for ansiblels (lsp-config):
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#ansiblels

The error that occurs, when typing in yaml files:
```
Cannot read property 'enabled' of undefined                                                                                                 

Request Actions:
Type number and <Enter> or click with the mouse (q or empty cancels): Cannot read property 'enabled' of undefined
```
An exmple yaml file (ansible playbook):
```
#!/usr/bin/env ansible-playbook
---
- name: Test lsp  
  ta
```
The error occurs, when trying to complete `ta` to `tasks`.

**Comment by williamboman** [comment]
Hey so that seems like a JavaScript error message which suggests that it comes from the server itself. Could you try installing an older version of the server by doing the following:

```
:LspInstall ansiblels@<commit>
```

You can find the commits in their repo (there's a link if you expand the server in the :LspInstallInfo window)

**Comment by williamboman** [comment]
There seem to have been an issue with installing custom versions for ansiblels - fixed here https://github.com/williamboman/nvim-lsp-installer/commit/116b47e9301ead9638aa6d417984f76ea6baa1ab.

I tried `:LspInstall ansiblels@43b390f231be6f7034d5c4aff4b7487f845bda3e` and it seems to work fine - so it looks like this is an upstream issue with the server itself

**Comment by ghillb** [comment]
Thanks! I I got a new error, (also after installing the `nvim-lsp-installer` commit you mentioned):
```
 use {'williamboman/nvim-lsp-installer', commit='116b47e9301ead9638aa6d417984f76ea6baa1ab'}
```
and then ansiblels with
```
:LspInstall ansiblels@43b390f231be6f7034d5c4aff4b7487f845bda3e
```
This is the error from npm:
```
npm ERR! code EINVALIDTAGNAME                                                                                                                │                 
npm ERR! Invalid tag name "latest@43b390f231be6f7034d5c4aff4b7487f845bda3e": Tags may not have any characters that encodeURIComponent encodes.              
npm ERR! A complete log of this run can be found in:                                                                                         │                 
npm ERR!     /home/g/.npm/_logs/2021-10-17T11_41_43_818Z-debug.log
```

from the debug.log:
```
30 timing command:install Completed in 255ms
31 verbose stack Error: Invalid tag name "latest@43b390f231be6f7034d5c4aff4b7487f845bda3e": Tags may not have any characters that encodeURIComponent encodes.
31 verbose stack     at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:89:15)
31 verbose stack     at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:343:13)
31 verbose stack     at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:80:12)
31 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:48:10)
31 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:455:50
31 verbose stack     at Array.map (<anonymous>)
31 verbose stack     at Arborist.[add] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:452:28)
31 verbose stack     at Arborist.[applyUserRequestsToNode] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:427:23)
31 verbose stack     at Arborist.[applyUserRequests] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:383:43)
31 verbose stack     at Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:202:37)
32 verbose cwd /home/g/.local/share/nvim/lsp_servers/ansiblels
33 verbose Linux 5.11.0-37-generic
34 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "npm@latest@43b390f231be6f7034d5c4aff4b7487f845bda3e"
35 verbose node v12.21.0
36 verbose npm  v7.20.6
37 error code EINVALIDTAGNAME
38 error Invalid tag name "latest@43b390f231be6f7034d5c4aff4b7487f845bda3e": Tags may not have any characters that encodeURIComponent encodes.
39 verbose exit 1
```
![Screenshot 2021-10-17 134221](https://user-images.githubusercontent.com/35503959/137626451-5eb7b2d0-1483-4d41-a0c2-c9df1a3da89a.png)

**Comment by williamboman** [comment]
That's precisely the issue that should've been fixed actually. Try just pulling the latest version, without specifying a commit?

**Comment by ghillb** [comment]
I'm now at:
```
6578fb5 (HEAD -> main, origin/main, origin/HEAD) ui: render header differently if help is showing
```
and it works!

I thought I updated all plugins with packer before trying the specific commit. Anyway, thank you :+1:

**Comment by williamboman** [comment]
Nice one! After a quick glance it seems like they added some new settings there. And they don't seem to merge the default settings with settings provided by the client: https://github.com/ansible/ansible-language-server/blob/cefd599043311fcba5803e780edce16c09cc9c64/src/services/settingsManager.ts#L102

I think we should either:
1) open a patch to lspconfig where we add the new `executionEnvironment` setting [here](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/ansiblels.lua#L8-L20) (no idea what values to use, maybe we should use the same as the default ones defined in ansible-language-server)
2) open an issue with ansible-language-server and suggest that they merge the client's settings with the default settings
