### ISSUE TITLE
Discussion on auto-installing servers

### ISSUE THREAD

**Issue by mjlbach** [williamboman/nvim-lsp-installer#184]
What would you need from lspconfig to make installing servers automatic? 

Two options: 

* No lspconfig config enabled, you open a lua file, lsp-installer detects this, enables the lsp config "blessed" configuration (pyright for python, clangd for c, etc.) and installs the language server for you, then lspconfig "just works"
* Lspconfig config enabled, lsp-installer detects this, and automatically installs the language servers matching your configs.

Happy to discuss.

I personally find this to be an anti-pattern, but there's an extremely vocal segment of users who probably will never use the built-in client until there is a supported option for this workflow.

**Comment by williamboman** [comment]
Hey! Not sure I'm following what lspconfig enabled means, do you mean individual servers that users have called `.setup()` on?

My initial thought would be that I guess this could be solved via `ftplugin`s, for example:

```vim
" autoload/lsp/autoinstall.vim
function lsp#autoinstall#setup(server_name)
    lua <<EOF
-- check if server is installed, if not install it
EOF
endfunc
```

```vim
" ftplugin/typescript.vim
call lsp#autoinstall#setup("tsserver")

" ftplugin/html.vim
call lsp#autoinstall#setup("html")

" ftplugin/terraform.vim
call lsp#autoinstall#setup("tflint")

" ...
```

This would require the user to only do the following in their config:

```lua
require("nvim-lsp-installer").on_server_ready(function (server)
  local opts = {...}
  server:setup(opts)
end)
```

But I guess this could also be abstracted away to turn it into a 100% no-code setup for users. But I'm starting to feel like that's out of scope for this plugin.

> I personally find this to be an anti-pattern, but there's an extremely vocal segment of users who probably will never use the built-in client until there is a supported option for this workflow.

Yeah I'm not too keen on automatically installing servers upon opening buffers. I've been wanting to continue building on the UI in this plugin to make LSPs more accessible. But ultimately the choice to install one should always be initiated by the user.

So just one concrete example is that we could scan 1) all currently open buffers, and/or 2) `v:oldfiles` to build a list of most common filetypes and from that identify whether the user is missing an LSP, in which case we could promote these in the UI window.

Btw, by UI window I mean `:LspInstallInfo`:
<img width="100" alt="Screenshot 2021-10-20 at 15 43 09" src="https://user-images.githubusercontent.com/6705160/138104678-af5173be-185d-40a1-a5f0-4df48ed7ba2a.png">

**Comment by kylo252** [comment]
> * No lspconfig config enabled, you open a lua file, lsp-installer detects this, enables the lsp config "blessed" configuration (pyright for python, clangd for c, etc.) and installs the language server for you, then lspconfig "just works"

That's basically how it's done in LunarVim, with the caveat of having to use that weird hack for ftplugin. Related: https://github.com/neovim/nvim-lspconfig/issues/970.

**Comment by mjlbach** [comment]
> I'm not very involved as far as user feedback goes, but I wonder how much of it is really about automatic installations of LSP servers?

Honestly, quite a bit. This is the number one thing I receive complaints about by far. The second and third are the lack of built-in autocompletion and snippets. The fourth being no default keybindings (although, this is the same as coc.nvim). The last thing is project local configuration/scratch servers which is WIP pending lua auto commands.

> As for this plugin, I'm starting to feel like it's somewhat feature complete. 

Totally understandable, I wanted to gauge your temperature on this. I think we could abstract away from having the "core" functionality in this plugin pending the ability to have a plugin manage other plugins with packer. This is essentially how coc-nvim works.

**Comment by mjlbach** [comment]
I think this could potentially be revived as an option with the new setup hook, such that calling setup for a given language server.

**Comment by mjlbach** [comment]
Yeah, it could be multi-typed, take a table for ensuring certain servers are installed (which can also be used in a loop to setup all of lspconfig) or a boolean which defaults to false that installs servers called by setup. I usually like having separate keys to keep the types consistent, for which perhaps `automatic` would be fine.

If you split this out into a separate companion plugin these could live in that plugin to avoid polluting the core installer plugin with things overfit to lspconfig.

**Comment by williamboman** [comment]
What about #638? I'm wondering if it also should make sure to uninstall any installed servers that haven't been set up..

**Comment by williamboman** [comment]
Added with the following variants:

```lua
-- 1.
require("nvim-lsp-installer").setup {
  ensure_installed = { "rust_analyzer" } -- will always make sure rust_analyzer is installed, no matter if you set the server up or not
}

-- 2.
require("nvim-lsp-installer").setup {
  automatic_installation = true, -- all servers set up via lspconfig will automatically be installed
}

-- 3.
require("nvim-lsp-installer").setup {
  automatic_installation = { exclude = { "rust_analyzer" } }, -- all servers set up via lspconfig, except "rust_analyzer", will automatically be installed
}
```
