### ISSUE TITLE
Add R language Server

### ISSUE THREAD

**Issue by alexhallam** [williamboman/nvim-lsp-installer#185]
An R language serve exists and instructions to install it are on the [vscode site](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp). I would be happy to add a PR, just not sure what that would require.

**Comment by williamboman** [comment]
Hey! There was an attempt to add R to this plugin, but we struggled with getting it to make a local, isolated, installation (see #81). IIRC, no matter what we attempted it'd either try to rely on some global property, or it'd install things globally, making it a bad fit for this plugin.

**Comment by williamboman** [comment]
Adding `help wanted` and `status:blocked` as I do not know how to proceed with this (i.e., ensuring a 100% local installation).

**Comment by meriops** [comment]
From reading #81 and #491, and this thread, I came across [jozefhajnala/languageserversetup](https://github.com/jozefhajnala/languageserversetup) which seems to provide a solution by installing "the languageserver package and its dependencies into a separate, independent library" (from the Readme).

**Comment by williamboman** [comment]
`r_language_server` added in #467! (installs locally with the help of https://github.com/jozefhajnala/languageserversetup/)
