### ISSUE TITLE
stylelint_lsp and eslint don't get fully installed

### ISSUE THREAD

**Issue by bowmanmike** [williamboman/nvim-lsp-installer#204]
Running `:LspInstall stylelint_lsp eslint` seems to run successfully, but when I look at the install directory, all I see is `package.json`, `package-lock.json`, and `node_modules`. Because of this, there are no servers to run.

Am I missing something? Thanks!

**Comment by bowmanmike** [comment]
Interesting. That makes sense. Given that though, how do I provide the path to the server? Like, what do I put for the `cmd` value for the servers in my LSP config?

**Comment by williamboman** [comment]
That's done for you when you call `server:setup()`, no need to provide `cmd` at all.

**Comment by bowmanmike** [comment]
Ahh! Figured it out, thanks! Looks like I wasn't calling `server:setup()` properly. Thanks for all your help! :D
