### ISSUE TITLE
nil is printed on jdtls attach event

### ISSUE THREAD

**Issue by s1n7ax** [williamboman/nvim-lsp-installer#211]
How to recreate
* Open neovim
* Open java source

Expected:
nvim-lspinstall used to display loading and the percentage

Actuat:
nil printed to the console

https://user-images.githubusercontent.com/18459807/139517785-e4723ffd-4b6e-481e-8219-9f53b53adcc2.mp4

**Comment by williamboman** [comment]
Hey there shouldn't be any differences. I took a look at the [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall/blob/main/lua/lspinstall/servers/java.lua#L79) definition, and it's pretty much a mirror of [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/jdtls.lua#L137). I wonder if jdtls changed their implementation of that specific LSP request

**Comment by williamboman** [comment]
Or actually, this could be due to neovim's LSP handler signature recently changing. Anyways this should probably be filed upstream in the lspconfig repo

**Comment by williamboman** [comment]
Pretty sure it is. Closing in favor of https://github.com/neovim/nvim-lspconfig/pull/1348
