### ISSUE TITLE
Global/Preinstalled language servers

### ISSUE THREAD

**Issue by ambasta** [williamboman/nvim-lsp-installer#213]
Hi,

How do I get nvim lsp installer to use pre-installed language servers? For example, I have clangd installed both as a system wide package as well as user built package. Both of these are available in $PATH.

How do I get nvim-lsp-installer.get_installed_servers() to detect these as available language servers?

**Comment by williamboman** [comment]
Hello! I'm not sure I'm following how you mean this plugin should use globally installed executables? If you're managing them externally, why not interact directly with lspconfig like

```lua
lspconfig.clangd.setup {
  ...
}
```

**Comment by ambasta** [comment]
Well, that is what I am doing currently. However, I believe that nvim lsp installer should also autodetect preinstalled LS and mark them as installed in get_installed_servers.

Ofcourse, a user a choose to install the LS again, in which case get_installed_servers should prioritize language servers installed in lsp root_dir

**Comment by williamboman** [comment]
Ah gotcha. That's not really a goal of this plugin currently. You can always customize the behavior of server instances by overloading some of its methods, like:

```lua
local server = require("nvim-lsp-installer.server")
local lsp_servers = require("nvim-lsp-installer.servers")
local shell = require("nvim-lsp-installer.installers.shell")

local clangd = server.Server:new {
    name = "clangd",
    root_dir = server.get_server_root_path("clangd"),
    installer = shell.bash [[ install-clangd-globally-non-interactively ]],
    default_options = {
       cmd = { "clangd", ... }
    }
}

lsp_servers.register(clangd) -- this should override the internal clangd server
```

More docs available in CUSTOM_SERVERS.md

**Comment by ambasta** [comment]
I understand if this is a non-goal, but one the advantages of using lsp-installer is automatic LSP installation/detection. While the solution provided does, once a user has multiple LS installed (via distro or otherwise), this adds a ton of additional config. IMHO, checking for known binaries in current path doesn't add a significant overhead.

Thanks for the guidance though.

**Comment by williamboman** [comment]
Yeah I think searching the path for executables is the easy part for sure. But the notion of a global installation and all the constraints that comes with it hinders pretty much every other feature this plugin offers (for example uninstalling, updating). I think this could be a case for a compat plugin which checks for each LSP servers executable in path and if it exists "ejects" from the LSP installer by overloading the functions of the server:

```lua
function theserver:install_attached(context, callback)
  context.stdio_sink.stderr("Globally installed servers cannot be installed via nvim.\n")
  callback(false)
end

function theserver:uninstall()
  error("Globally installed servers cannot be uninstalled via nvim.")
end
```
