### ISSUE TITLE
What's the colorscheme used in the preview image?

### ISSUE THREAD

**Issue by VimalMollyn** [williamboman/nvim-lsp-installer#219]
Hey,

Thanks for the awesome plugin! I was wondering which colorscheme is used in the preview gif? It looks great!

Thanks!
Vimal

**Comment by williamboman** [comment]
Haha thanks. It's actually the aurora theme in https://github.com/christianchiarulli/nvcode-color-schemes.vim + some [thrown together overrides](https://github.com/williamboman/nvim-config/blob/main/plugin/colors.vim)

**Comment by williamboman** [comment]
https://github.com/mhartington/oceanic-next might be interesting too, been meaning to try it out
