### ISSUE TITLE
[Feature Request] Expose get_server function

### ISSUE THREAD

**Issue by Akeboshiwind** [williamboman/nvim-lsp-installer#22]
I'm trying to do something like this:
```lua
local lsp_installer = require('nvim-lsp-installer')
local _, server = lsp_installer.get_server("rust-analyzer")

if not server.is_installed() then
    server.install()
end
```

I want to do this so that I only install the language server if a specific plugin is loaded (in this case `rust-tools.nvim`).

But I'm unable to because the `get_server` function isn't exposed. Would it be possible to expose it?

**Comment by williamboman** [comment]
Hi! I think it'd make sense to include such a Lua API for sure. I'm wondering whether such an API should be exported via the main module (as you've suggested) or if importing the server module directly would be neater. I can't make my mind up whether `require'nvim-lsp-installer.servers.rust_analyzer'` is reaching into internals or not.. wdyt?

**Comment by Akeboshiwind** [comment]
Hmm as long as it's a documented part of the API I think it's fine.

The only thing I would say is that it's difficult for the user to handle potential failure.

Say you were to update the plugin and remove support for an LSP I was using, it wouldn't be the end of the world if I got a `module not found` error, or if I had to wrap the require call in `pcall`. But it would be nicer if the API handled it for me.

**Comment by Akeboshiwind** [comment]
Although this isn't too bad tbh:

```lua
local server_name = 'rust_analyzer'

local ok, server = pcall(require, 'nvim-lsp-installer.servers.'..server_name)

if not ok then
    -- Show an error & throw
end
if not server.is_installed() then
    server.install()
end
```
