### ISSUE TITLE
Graphql lsp does not currently support graphql@16

### ISSUE THREAD

**Issue by NICHTJ3** [williamboman/nvim-lsp-installer#221]
This is an issue because the lsp installer for the graphql lsp installs the latest version of graphql. Is there something I can do to work around this quickly or do I have to create a custom server?

For more info see [here](https://github.com/graphql/graphiql/issues/1982)

**Comment by kylo252** [comment]
Yes you can specify the version that you want, e.g. `:LspInstall rust_analyzer@nightly`

**Comment by williamboman** [comment]
Ah I see. The version will only be applied to the "head" package, so if a server installs more than one npm package you're currently only able to specify the version for the first one

- https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/graphql/init.lua#L9
- https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/installers/npm.lua#L45-L48

I'm not sure how to best deal with this particular issue. I was thinking perhaps adding a `--interactive` flag to `:LspInstall` which will allow installers to prompt for input

As for the GraphQL LSP, I think we could pin it to `@15` for now. Preferably it should ship with a fallback graphql dependency itself, might be worth filing an issue upstream too?

**Comment by williamboman** [comment]
It seems to be installing graphql@15 though, I wonder if it's because of the peerDependency which specifies `"^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0"`. @NICHTJ3 what problems are you having?

**Comment by NICHTJ3** [comment]
It's probably my node version not installing the correct pair dependency. To work around it I just cd'd to the install directory and installed graphql@15

**Comment by williamboman** [comment]
I think the GraphQL LSP tries to use a project local `graphql` installation, maybe that's where the issue is? The `graphql` that is installed alongside the LSP in this plugin is just a fallback, iirc. Similar to ESLint and tsserver (I think)

**Comment by williamboman** [comment]
@NICHTJ3 Is this still causing problems? I can't seem to repro - it's installing `graphql@15` for me and I'm not running into any issues with GraphQL. I think it's most likely a project-local `graphql` dependency that is running version 16 that's causing this?

**Comment by NICHTJ3** [comment]
So I decided to test this again today. The project version of graphql is 15.5.1 so that's definitely not the issue but reinstalling the lsp doesn't install version 16 like it did the otherday. I put it down to maybe running `LspInstall graphql` with a different node version that didn't respect the pair dependency.

I'm going to close this issue since it's unrelated to this plugin 🤦‍♂️
