### ISSUE TITLE
[feat]: use `pnpm` if installed

### ISSUE THREAD

**Issue by younger-1** [williamboman/nvim-lsp-installer#222]
[pnpm](https://pnpm.io/) is faster and more efficient than `npm`.

If `pnpm` is found in system, it it better to use it other than `npm`

**Comment by williamboman** [comment]
Hello! I'd argue the technical implications of which Node package manager is used in this plugin is of less importance, as installations are 1) one-off events, and 2) generally only install one single package. npm is still the default package manager for node and is the safest option to assume is installed as it generally ships together with Node.js. In the interest of stability and maintainability I don't think it's currently of interest to add more variants of a Node package manager

**Comment by younger-1** [comment]
Thanks very much for your reply which is very reasonable!
