### ISSUE TITLE
New attach_buffers command not respecting autostart

### ISSUE THREAD

**Issue by jason0x43** [williamboman/nvim-lsp-installer#227]
With commit 14b64a2, servers that I have configured with `autostart=false` are being attached to buffers without being explicitly started (the `autostart` option seems to be ignored). If I revert to d5f370b and use `vim.cmd('do User LspAttachBuffers')`, behavior is as expected (`autostart=false` servers aren't attached until explicitly started).

To reproduce, configure an lsp-installer managed language server with `autostart=false`, open a matching filetype, and observe that the language server is started.

I also observed with commit 14b64a2 that a FileType autocommand I had setup to manually start one language server no longer appears to be firing. Again, switching back to d5f370b restores the expected behavior (the command fires and manually starts the language server).

**Comment by williamboman** [comment]
> I also observed with commit [14b64a2](https://github.com/williamboman/nvim-lsp-installer/commit/14b64a21e850eee2b9b351c92394e33df57a7f08) that a FileType autocommand I had setup to manually start one language server no longer appears to be firing

Ah, shoot. This ought to be an easy fix (`fix-autostart` #228).



> I also observed with commit [14b64a2](https://github.com/williamboman/nvim-lsp-installer/commit/14b64a21e850eee2b9b351c92394e33df57a7f08) that a FileType autocommand I had setup to manually start one language server no longer appears to be firing. Again, switching back to [d5f370b](https://github.com/williamboman/nvim-lsp-installer/commit/d5f370b7cea0466ceaca4af39efa2c013114f6ec) restores the expected behavior (the command fires and manually starts the language server).

Yeah prior to that commit, calling `vim.cmd("do User LspAttachBuffers")` would trigger `do FileType` behind the scenes. This no longer happens, in fact `User LspAttachBuffers` does nothing anymore. I'd recommend not relying on autocmds, but I don't know the full use case so what you could do is either:

```vim
" register your own handler for LspAttachBuffers which simply re-dispatches FileType in all buffers
autocmd User LspAttachBuffers doautoall FileType
```

```diff
- vim.cmd("do User LspAttachBuffers")
+ vim.cmd("do FileType")
```

**Comment by jason0x43** [comment]
Currently the only time I try to manually manage servers is for Typescript files. I want to use denols for Deno files and tsserver otherwise. I have a simple heuristic to guess which one is applicable. When the FileType event fires I decide whether to autostart denols or tsserver. This has been working well enough, but I'm definitely open to a better implementation.

**Comment by jason0x43** [comment]
Also, thanks for looking into this so quickly!

**Comment by williamboman** [comment]
Ah in that case I guess using FileType autocmd makes sense. I'm struggling to understand in what scenarios the removal of the autocmd causes issues. Is it when you're opening a new nvim instance with a filename as argument, like `nvim foo.ts`? Do you perhaps do any lazy loading of plugins or whatnot?

**Comment by jason0x43** [comment]
Ah, I see what you mean about lazy loading plugins.

**Comment by jason0x43** [comment]
Hmmm...a FileType autocmd may not be the best option. If the autocmd is installed in `init.lua`, it can be called before the language servers have been initialized. If the command is installed during the initialization process, it won't fire when a TS file is opened directly from the command line.

What I really need is a `before_attach` or `should_attach` or something that will be called at the point when lspconfig wants to try to attach. Using a custom `root_dir` function works, but is pretty hacky.

**Comment by williamboman** [comment]
With autostart = false lspconfig will never try to attach though, so there are no lifecycle hooks to begin with.

What about

```lua
lsp_installer.on_server_ready(function (server)
  server:setup()
  vim.cmd [[ doautoall FileType ]]
end)

**Comment by jason0x43** [comment]
Ah, that's what you meant earlier. Yes, that works. 😄
