### ISSUE TITLE
[Feature Request] Expose `default_options` as part of API

### ISSUE THREAD

**Issue by Akeboshiwind** [williamboman/nvim-lsp-installer#23]
I'm wanting to use this package to install `rust-analyzer` automatically but I actually want to use `rust-tools.nvim` to run the lsp stuff.

What I'd like to do is roughtly this:
```lua
local lsp_installer = require('nvim-lsp-installer')
local server = lsp_installer.get_server('rust_analyzer')

if not server.is_installed() then
    server.install()
end

require('rust-tools').setup({
    -- other opts
    server = server.default_options,
})
```

Currently I think I can just use `server._default_options`, but it would be nice if this was a documented field that was properly exposed.

**Comment by williamboman** [comment]
:+1: https://github.com/williamboman/nvim-lsp-installer/commit/97c92eaa217608d2b338babf3de85e39f352d8ea

**Comment by Akeboshiwind** [comment]
That's amazing, thanks :D
