### ISSUE TITLE
cmd ["texlab"] is not executable.

### ISSUE THREAD

**Issue by vincentqb** [williamboman/nvim-lsp-installer#231]
After doing `:LspInstall texlab` in neovim, closing neovim and opening a latex file, `:LspInfo` shows:
```
cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
```

`:checkhealth` shows
```
  - ERROR: texlab: The given command "texlab" is not executable.
```

**Comment by williamboman** [comment]
Hey it sounds like you're setting up the server by calling `lspconfig.texlab.setup {}` directly. To use the executables provided by nvim-lsp-installer, you need to set up the server via nvim-lsp-installer. There's an example in the README here https://github.com/williamboman/nvim-lsp-installer#setup

**Comment by vincentqb** [comment]
Good point! Removing that line and `:LspPrintInstalled` shows texlab. Thanks!
