### ISSUE TITLE
Tsserver not working with react/javascript

### ISSUE THREAD

**Issue by isaif** [williamboman/nvim-lsp-installer#243]
## Issue
Tsserver lsp features not working in react (javascript) project but works in react (typescript) project.

I created a react typescript project using `npx create-react-app tsexample --template typescript` and a react javascript project using `npx create-react-app jsexample`. Lsp errors, go to definition etc works in *tsexample* (react typescript projec) but in *jsexample* (react javascript) nothing works. 

## LspInfo
`LspInfo` shows tsserver as attached in both the project, so that may not be cause of the problem.

javascript project
```
 Language client log: /home/saif/.cache/nvim/lsp.log
 Detected filetype:   javascript
 
 1 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, pid: 99127, bufnr: [1, 1])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/saif/temp/jsexample
 	cmd:             /home/saif/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/typescript-language-server --stdio
 
 Configured servers list: clangd, tsserver, sumneko_lua
```
typescript project

```
 Language client log: /home/saif/.cache/nvim/lsp.log
 Detected filetype:   typescriptreact
 
 1 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, pid: 99320, bufnr: [1, 1])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/saif/temp/tsexample
 	cmd:             /home/saif/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/typescript-language-server --stdio
 
 Configured servers list: tsserver, sumneko_lua, clangd

```

## jsconfig.json for *jsexample* project

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "checkJs": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

## lsp config

I have tried using this minimal config to ensure that I am not making any mistake in my config.
```
local lsp_installer = require("nvim-lsp-installer")

lsp_installer.on_server_ready(function(server)
    local opts = {}
    server:setup(opts)
end)
```
## Solution

What solves this issue is by installing typescript globally `npm -g install typescript`. But what I know is we don't need to install typescript globally when using this plugin as it installs it in `.local/share/nvim/lsp_servers/tsserver/node_modules/` directory. Am I missing anything?

## **System info**
 - OS: linux
 - Neovim version: NVIM v0.6.0-dev+467-g30af69509

**Comment by cdimitroulas** [comment]
@lsalf I'm encountering this issue, how did you resolve it?
