### ISSUE TITLE
Help Recognizing Vim as a Global

### ISSUE THREAD

**Issue by e2oneedh2o** [williamboman/nvim-lsp-installer#245]
How do you go about configuring lsp installer to recognize vim as a global in lua? This is as far as I got with the documentation.

```-- lsp_installer
local lsp_installer = require("nvim-lsp-installer")
local servers = {
    "sumneko_lua",
}

lsp_installer.on_server_ready(function(server)
    local default_opts = {
    }
    local server_opts = {
        ["sumneko_lua"] = function()
            default_opts.cmd = {
                vim.fn.stdpath("data") .. "/lsp_servers/sumneko_lua/extension/server/bin/macOS/lua-language-server",
            }
            default_opts.diagnostics = [[ 
                globals = {'vim'},
    ]]

            return default_opts
        end
    }

    server:setup(server_opts[server.name] and server_opts[server.name]() or default_opts)
    vim.cmd([[ do User LspAttachBuffers ]])
end)

```

**Comment by williamboman** [comment]
Hello! I'd recommend using either https://github.com/folke/lua-dev.nvim or copy the changes made in https://github.com/neovim/nvim-lspconfig/pull/1339/files. Alternatively you could wait for the PR in lspconfig to be merged, which it most likely will, after which it will be the default settings

**Comment by maxmx03** [comment]
![Captura de tela de 2022-02-21 11-48-28](https://user-images.githubusercontent.com/50273941/154978082-9f8f8897-16ec-4113-9c62-e6560d6b4cce.png)
