### ISSUE TITLE
Add support for Dartls

### ISSUE THREAD

**Issue by Je12emy** [williamboman/nvim-lsp-installer#252]
**Which server would you like to request to be added?**
Server name: Dartls
Server homepage (e.g., GitHub page): https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec

**Which languages does this server target?**
Languages: Dart for flutter development

**Comment by williamboman** [comment]
Hello! I assume you're referring to dartls in lspconfig? The link is for a standalone plugin that has no interop with lspconfig

**Comment by Je12emy** [comment]
Hi, I just updated the link sorry, I must have pasted the wrong link since I was looking around for plugins for dart :P

**Comment by williamboman** [comment]
So it seems like the language server ships with Dart itself. I feel like that makes it a pretty bad fit for this plugin. We could of course download the entire Dart SDK so that we have the binary installed locally, but I feel like it's a fair assumption that if you need the Dart LSP you should already have `dart` installed on your system? In which case you can interact directly with lspconfig:

```lua
lspconfig.dartls.setup {}
```

We have a similar situation with other LSPs (#185, #143).

However, where I do see a use case is to allow using this plugin as a proxy for managing all your servers, so that you only need one piece of code in your config:

```lua
lsp_installer.on_server_ready(function (server)
  server:setup {}
end)
```

**Comment by williamboman** [comment]
I wouldn't be opposed to adding a "faux installer" that simply just verifies that the `dart` executable is on path, like so:

```lua
Server:new {
  name = "dartls",
  installer = std.ensure_executables {
    { "dart", "dart was not found on path. Refer to https://dart.dev/get-dart." }
  }
}
```

This would allow you to have dartls as an entry in `:LspInstallInfo`, and you can toggle it on/off as you wish.

**Comment by williamboman** [comment]
Hey could you give #267 a try? I tried installing dart but it wants me to install a bunch of other stuff that I can't be bothered to 😬

**Comment by Je12emy** [comment]
> Hey could you give #267 (branch `dartls`) a try? I tried installing dart but it wants me to install a bunch of other stuff that I can't be bothered to 😬

Will do!

**Comment by Je12emy** [comment]
# Environment

* OS: Pop_Os! 20.04
* Dart SDK version: 2.13.1 (stable)
* Dart Installation Method: Installed through the oficial snap package.

# Output

This is the output after installing the `dartls` with `:Lsp dartl`, this output is also shown when opening any folder with neovim.

```
[nvim-lsp-installer] vim/shared.lua:261: after the second argument: expected table, got nil
stack traceback:
^Ivim/shared.lua:261: in function 'tbl_deep_extend'
^I...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:54: in function 'setup_lsp'
^I...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:67: in function 'setup'
^I/home/dio/.config/nvim/lua/lsp.lua:68: in function </home/dio/.config/nvim/lua/lsp.lua:57>
^I[C]: in function 'pcall'
^I...nvim-lsp-installer/lua/nvim-lsp-installer/dispatcher.lua:9: in function 'dispatch_server_ready'
```

This is the log.

```
1   [INFO  Tue 26 Oct 2021 02:36:04 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:547: Starting install server_name="tsserver", requested_version="N/A"
  1 [INFO  Tue 26 Oct 2021 02:36:04 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:547: Starting install server_name="omnisharp", requested_version="N/A"
  2 [INFO  Tue 26 Oct 2021 02:36:04 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:566: Installation completed server_name="tsserver", success=false
  3 [INFO  Tue 26 Oct 2021 02:36:11 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:566: Installation completed server_name="omnisharp", success=true
  4 [INFO  Tue 26 Oct 2021 02:37:25 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:547: Starting install server_name="tsserver", requested_version="N/A"
  5 [INFO  Tue 26 Oct 2021 02:37:25 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:566: Installation completed server_name="tsserver", success=false
  6 [INFO  Tue 26 Oct 2021 02:37:50 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:547: Starting install server_name="tsserver", requested_version="N/A"
  7 [INFO  Tue 26 Oct 2021 02:37:57 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:566: Installation completed server_name="tsserver", success=true
  8 [INFO  Tue 26 Oct 2021 02:50:29 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:547: Starting install server_name="bashls", requested_version="N/A"
  9 [INFO  Tue 26 Oct 2021 02:50:36 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:566: Installation completed server_name="bashls", success=true
 10 [INFO  Thu 28 Oct 2021 09:10:56 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:547: Starting install server_name="pyright", requested_version="N/A"
 11 [INFO  Thu 28 Oct 2021 09:11:00 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:566: Installation completed server_name="pyright", success=true
 12 [INFO  Fri 19 Nov 2021 07:25:38 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="dartls", requested_version=""
 13 [INFO  Fri 19 Nov 2021 07:25:38 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="dartls", success=true
 14 [INFO  Fri 19 Nov 2021 07:29:13 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="dartls", requested_version=""
 15 [INFO  Fri 19 Nov 2021 07:29:13 PM CST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="dartls", success=true
```

The server is shown to be installed, but the client does not attach when opening a `.dart` file, let me know if you need anything else!

**Comment by williamboman** [comment]
Ah, thanks. I pushed a new commit that ought to fix that. Could you please try again?

**Comment by Je12emy** [comment]
The client is now shown as attached, but it seems like it's not doing anything... using the lsp's api seems to not be doing anything even though the client is shown as active and attached

 Video for reference.

https://user-images.githubusercontent.com/34408108/142743308-19b9f56e-ee55-4a71-9391-24f8d02ef66a.mp4

**Comment by williamboman** [comment]
Hm, and did you check `:LspInfo` and see that the server is attached to the buffer? The thing is that this plugin won't be responsible for installing nor setting up the LSP, so I feel like either:

1) the LSP server wasn't attached
1) there's some error upstream in [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/dartls.lua)
1) the `dart` executable you have in path is outdated

**Comment by Je12emy** [comment]
Looks like the LSP server wasn't attached.

```console
 Language client log: /home/dio/.cache/nvim/lsp.log
 Detected filetype:   dart
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: dart
 
 Config: dartls
 	filetypes:         dart
 	root directory:    /home/dio/Documents/code/startup_namer
 	cmd:               dart /usr/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: bashls, dartls, tsserver, omnisharp, pyright
```

**Comment by williamboman** [comment]
Hm not sure why it won't attach. nvim-lsp-installer won't be responsible for providing any settings that either starts or configures the LSP, so I'll go ahead and merge #267. As for why it didn't attach, I don't think I can be of much help as I don't use the dart LSP myself :/
