### ISSUE TITLE
Externalize UI library

### ISSUE THREAD

**Issue by s1n7ax** [williamboman/nvim-lsp-installer#263]
UI modules you have created are impressive. People can use those for other use cases if you can externalize them to a separate plugin.

**Comment by williamboman** [comment]
Hello and thank you! I have had this in mind as well. I think many plugins would benefit from a "simpler" API to build stateful UIs. It's helped tremendously in prototyping and iterating on the UI in this plugin for sure. However, there are a few things that makes me not want to do it right now, for example:

- The neovim plugin ecosystem doesn't really handle dependencies very well at the moment, I'd like to avoid adding yet another "plenary" plugin. I've thought about perhaps distributing it as a single Lua file that could be more easily version controlled and manually managed via `curl` et al.
- The current implementation is really hacky and the internals are pretty much at a "just get it working" stage. Would need quite some refinement and additions before it's ready for broader usage. There are also a bunch of public API improvements that I've been wanting to do. It's far from mature enough to warrant its own plugin.
