### ISSUE TITLE
esbonio: Need install all plugins of sphinx for esbonio

### ISSUE THREAD

**Issue by cathaysia** [williamboman/nvim-lsp-installer#264]
Hi, had remember that bug I mention? https://github.com/williamboman/nvim-lsp-installer/pull/253

I had talk with https://github.com/swyddfa/esbonio/issues/45 , then I solve this. In the short, for a spinx project, users my import many plugins, we **must** install all plugins for esbonio, else go dead. :(

So I want know how do we solve this?

source ~/.local/share/nvim/lsp_servers/esbonio/venv/bin/activate then install requirements.txt ?

Or can we change plugins that need be installed in user's configuration?
And or we remove esbonio installer?

Looking forward to your replay. And sorry for my pr cause this bug. :(

**Comment by williamboman** [comment]
Hello! Do I understand you correctly that it's common to declare project-local Sphinx dependencies in `requirements.txt`, which will need to be installed in the same venv as Esbonio?

I guess what could be done is to add a new command like `:EsbonioInstallPlugins`, which will use the same venv as the esbonio installation. This command would install packages defined in `project_root_dir .. "/requirements.txt"`. If possible this should probably also install to a different `PIP_TARGET` to avoid polluting the esbonio installation itself. Not sure if this makes sense, but I feel like it should be doable?

**Comment by cathaysia** [comment]
Yes, it's all I want express. :)

For my part, I declare all dependencies in requirements.txt, I can't sure others whether do this. So there are two ways. either write docs to tell users install all dependencies by themself, or add `:EsbonioInstallPlugins` commands.

I'm not familiar with PIP_TARGET, but I think, emm, dependencies shouldn't polluting esbonio itself. Because sphinx's plugins don't conflict with each other.(I haven't encounter this problem.) So maybe we can install all dependencs of all projects in a venv.

And, sorry for my plastic English.

**Comment by wainscape** [comment]
If I am understanding correctly, I had a similar issue. I want to take advantage of Pylsp's plugin support to use the Black formatter. Although Pylsp natively supports several third-party tools, such as autoPEP8, if they're installed, at this time Black is supported via a third party plugin, [python-lsp-black](https://github.com/python-lsp/python-lsp-black). 

To install the black plugin:
`source ~/.local/share/nvim/lsp_servers/pylsp/venv/bin/activate`
`pip install python-lsp-black`

And now it works. However, it could be handy to have some integration with the LspInstall commands and interface, which are so wonderfully convenient and easy to use. 

btw, another way to integrate Black and other tools with lsp is using null-ls, but for now I figured why add another layer if I don't need to.

**Comment by williamboman** [comment]
@wainscape There's already a [`:PylspInstall` command](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/pylsp/README.md#installing-pylsp-plugins) for this purpose.

**Comment by williamboman** [comment]
Closing this per conversation in https://github.com/williamboman/nvim-lsp-installer/pull/623#pullrequestreview-953626774
