### ISSUE TITLE
angularls: cmd ["ngserver"] is not executable

### ISSUE THREAD

**Issue by lucasvianav** [williamboman/nvim-lsp-installer#268]
(created an issue to make it easier to track)

> Hi, I'm having a `cmd ["ngserver"] is not executable` error, even though it is installed and I can run it directly from my shell. Maybe an issue with the folder having aliases instead of the actual binary?
> 
> Sorry I'm commenting too late, I was trying to debug it and you merged 2 min before I went to report it, and I skimmed the code, didn't really try it before commenting on the [original PR](https://github.com/williamboman/nvim-lsp-installer/pull/261)

@williamboman I'm having this problem as well. 

Before I had it set up with
```lua
  if server.name == 'angularls' then
    local cmd = {
      server.root_dir .. '/node_modules/.bin/ngserver',
      '--stdio',
      '--tsProbeLocations',
      server.root_dir,
      '--ngProbeLocations',
      server.root_dir,
    }

    opts.cmd = cmd
    opts.on_new_config = function(new_config)
      new_config.cmd = cmd
    end
  end
```
and it was fine, but when I realized this was still there and removed it (leaving only the plugin's config) it stopped working.

_Originally posted by @lucasvianav in https://github.com/williamboman/nvim-lsp-installer/issues/266#issuecomment-973254568_

**Comment by williamboman** [comment]
Ah we need to overload the on_new_config, otherwise it'll default to this https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/angularls.lua#L33. Happy to receive PR, on mobile atm. Just overloading it with an empty function should do it

**Comment by lucasvianav** [comment]
> Happy to receive PR, on mobile atm. Just overloading it with an empty function should do it

will do!
