### ISSUE TITLE
sumneko_lua: 32bit support 

### ISSUE THREAD

**Issue by voyeg3r** [williamboman/nvim-lsp-installer#270]
I have an old laptop (32bit) (voidlinux) - After running `:LspInstall lua` I go to the folder: `~/.local/share/nvim/lsp_servers/sumneko_lua/extension/server/bin/Linux` and type:  `file lua-language-server`, the result is:

`lua-language-server: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for
GNU/Linux 3.2.0, BuildID[sha1]=3503462e21a8d81ad582862a84c9236f9bf39daf, stripped`

I think this is the root cause of my LSP stopped working, would be it?

**Comment by williamboman** [comment]
Hello! Prebuilt binaries are currently used to download the lua language server. I don't believe they provide 32 bit builds.

Are you able to build it yourself https://github.com/sumneko/lua-language-server/wiki/Build-and-Run?

**Comment by TeoDev1611** [comment]
Hey hello you can change the name of this issue to `32bit support Sumneko Lua` i think this :)
