### ISSUE TITLE
How to install texlab or ltex server offline

### ISSUE THREAD

**Issue by flaviusbuffon** [williamboman/nvim-lsp-installer#272]
**Describe the bug**
Due to internet problem, i want to download zip file and install the server munally, but I put texlab into server folder, it failed.

**Expected behavior**
Lsp server loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/44057232/142713879-3c24b67c-41f3-49a7-a625-ce0154849fc7.png)

**System info (please complete the following information):**
 - OS: Arch linux
 - Neovim version: v0.6.0-dev+604-g725cbe7d41

Please also include any other system information you think is relevant!

**Install log**

```
SSL_INIt
```

**Comment by sethidden** [comment]
Also facing this, but I'm not trying to install from a .zip but I want lsp-installer to download ltex for me. I just get SSL_INIT in LspInstallInfo. Im on cafe wifi right now but it's working fine.

```
[INFO  Wed 24 Nov 2021 11:32:31 AM CET] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="ltex", requested_version=""
```

**Comment by sethidden** [comment]
Also facing this, but I'm not trying to install from a .zip but I want lsp-installer to download ltex for me. I just get SSL_INIT in LspInstallInfo. Im on cafe wifi right now but it's working fine.

```
[INFO  Wed 24 Nov 2021 11:32:31 AM CET] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="ltex", requested_version=""
```

**Comment by williamboman** [comment]
> Im on cafe wifi right now but it's working fine.

I think I found your problem 😅

**Comment by sethidden** [comment]
@williamboman Shockingly it's 80 Mbps :P Was confused for a while since all I saw for a few minutes is SSL_INIT (which I assumed means "it didn't start downoading yet, it's trying to establish a secure connection") but then it just switched to installed.

I'll try again on home network

**Comment by williamboman** [comment]
I was mostly thinking of vulnerabilities like mitm 😬

**Comment by flaviusbuffon** [comment]
maybe , my sslinit problem appear when i using proxy.
