### ISSUE TITLE
Add support for ccls for lsp-install

### ISSUE THREAD

**Issue by bavalpey** [williamboman/nvim-lsp-installer#273]
There doesn't exist any lsp for C.  ccls is relatively straightforward to download.  It just requires llvm+clang (which many systems already have). I think it would be very beneficial to add support for this to the list of language servers supported by LspInstall.

I've thought about coc.nvim, but I feel that it is more than just an lsp, so users could just install it themselves. 

**Which server would you like to request to be added?**
Server name: ccls
Server homepage (e.g., GitHub page): https://github.com/MaskRay/ccls

**Which languages does this server target?**
Languages: C, C++, ObjC

**Comment by williamboman** [comment]
Hello! The `clangd` server exists. I think it mainly targets C++, but I use it for very simple use cases in C projects. Will look into adding ccls (PRs always welcome btw)

**Comment by williamboman** [comment]
I've started looking into this and yikes is ccls a real pain to build.. the work continues

**Comment by williamboman** [comment]
Hey again, could you give the branch `add-ccls` (#299) a try? It downloads the latest llvm release and uses it for `DCMAKE_PREFIX_PATH` when building `ccls`, wdyt?

**Comment by bavalpey** [comment]
I've given this a try and this works great! Thanks for your work on this!
I also found ccls to be a real pain to build, so the fact that you've integrated this to the point that it works is fantastic.

**Comment by williamboman** [comment]
> I also found ccls to be a real pain to build, so the fact that you've integrated this to the point that it works is fantastic.

Yeah and I think it's especially these servers that should be added to this plugin. Most servers can already be installed via existing package managers which is pretty straight forward by itself (I think managing ones installed/enabled servers from within neovim has other benefits though).
