### ISSUE TITLE
jdtls Lombok support not working

### ISSUE THREAD

**Issue by zhongjis** [williamboman/nvim-lsp-installer#274]
**Describe the bug**
I am using the nightly version of the nvim and for some reason jdtls config no longer get along well with Lombok.

**Expected behavior**
jdtls should not throw any error when client is attached.

**Screenshots**
![Screen Shot 2021-11-22 at 18 09 34](https://user-images.githubusercontent.com/23202735/142957503-8cca0fb8-5904-4d7d-abee-8d6abfcecd45.png)
![Screen Shot 2021-11-22 at 18 10 37](https://user-images.githubusercontent.com/23202735/142957591-950e7519-6eec-4bff-ac52-d07d27b9f2dd.png)

**System info (please complete the following information):**
 - OS: macOS 12.0.1
- NVIM v0.6.0-dev+617-g64abd7be7
Build type: Release
LuaJIT 2.1.0-beta3

Please also include any other system information you think is relevant!

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

```
 35 [INFO  Sun Nov 21 22:58:38 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="lemminx", requested_version=""
   36 [INFO  Sun Nov 21 22:58:41 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="lemminx", success=true
   37 [INFO  Mon Nov 22 17:58:29 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="jdtls", requested_version=""
   38 [INFO  Mon Nov 22 17:58:34 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="jdtls", success=true
```

```
   Client: jdtls (id: 2, pid: 24982, bufnr: [12])
   filetypes:       java
   autostart:       true
   root directory: 
   cmd:             /Users/zshen/.jenv/versions/openjdk64-11.0.13/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL -Xms1g -Xmx2G --add-modules=ALL-SYSTEM --add-opens java.
```

**Comment by zhongjis** [comment]
Looks like this is discussed in #205 how ever I do not see the agent option in cmd. Any idea?

**Comment by zhongjis** [comment]
> Hello! Have you upgraded the `nvim-lsp-installer` and `nvim-lspconfig` plugins recently?

Yes. I just updated both again and the issue persists.

**Comment by zhongjis** [comment]
seems the short snippet included in #205 do the trick ... took a look in [code](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/jdtls/init.lua) but it looks fine for me ... any idea?

**Comment by williamboman** [comment]
What does the following produce?

```
:lua _, jdtls = require("nvim-lsp-installer.servers").get_server("jdtls")
:lua print(vim.inspect(jdtls:get_default_options()))
```

**Comment by williamboman** [comment]
How are you setting up the server? Are you calling `server:setup()`, like in the [docs here](https://github.com/williamboman/nvim-lsp-installer#setup)?

**Comment by zhongjis** [comment]
> :lua print(vim.inspect(jdtls:get_default_options()))

```
{
  cmd = { "/Users/zshen/.jenv/versions/openjdk64-11.0.13/bin/java", "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product=org.eclipse.jdt.ls.core.product", "-Dlog.protocol=true", "-Dlog.level=ALL", "-Xms1g", "-Xmx2G", "-javaagent:/Users/zshen/.local/share/nvim/lsp_servers/jdtls/lombok.jar", "--add-modules=ALL-SYSTEM", "--
add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-jar", "/Users/zshen/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar", "-configuration", "/Users/zshen/.local/share/nvim/lsp_servers/jdtls/config_mac", "-data", "/Users/zshen/workspace/app_annotation_service" }
}
```

> How are you setting up the server? Are you calling `server:setup()`, like in the [docs here](https://github.com/williamboman/nvim-lsp-installer#setup)?

Yes. here's my [lspconfig](https://github.com/zhongjis/dotfiles-awesome/blob/master/nvim/lua/zhongjis/lsp/config-general.lua). i've been working on my configs a lot recently, not sure what happened but now even without the snippet in #205 lombok works lol

**Comment by williamboman** [comment]
> Yes. here's my [lspconfig](https://github.com/zhongjis/dotfiles-awesome/blob/master/nvim/lua/zhongjis/lsp/config-general.lua). i've been working on my configs a lot recently, not sure what happened but now even without the snippet in #205 lombok works lol

:+1: I think previously you were calling lspconfig's `.setup()` method directly, causing it to use lspconfig's default cmd.
