### ISSUE TITLE
Pyright showing a completed install but doesn't work

### ISSUE THREAD

**Issue by HagaiHargil** [williamboman/nvim-lsp-installer#276]
**Describe the bug**
When running `:LspInstall pyright` the operation finishes successfully, but if I then immediately run `:checkhealth` it rightfully reports that there's no "pyright-langserver" in my path. Indeed the installation folder doesn't contain that binary file:
```bash
$ ls -lah .local/share/nvim/lsp_servers/python/
total 20K
drwxr-xr-x 3 root root 4.0K Nov 23 09:43 .
drwxr-xr-x 4 root root 4.0K Nov 23 09:43 ..
drwxr-xr-x 4 root root 4.0K Nov 23 09:43 node_modules
-rw-r--r-- 1 root root  995 Nov 23 09:43 package-lock.json
-rw-r--r-- 1 root root  291 Nov 23 09:43 package.json
```
Inside `node_modules` there's the `.bin` folder, but the files there are weirdly simlinked to some JS files, and indeed I can't really run them as binary files.

**System info (please complete the following information):**
```bash
$ uname -a
Linux d424efaea487 5.4.0-87-generic #98~18.04.1-Ubuntu SMP Wed Sep 22 10:45:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ nvim --version
NVIM v0.6.0-dev+617-g64abd7be7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Install log**

```
[INFO  Tue Nov 23 09:43:54 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:551: Starting install server_name="pyright", requested_version=""
[INFO  Tue Nov 23 09:43:56 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:570: Installation completed server_name="pyright", success=true
```

Thanks for your work on this project.

**Comment by williamboman** [comment]
Hello! To be honest I'm not sure how the health provider for lspconfig is implemented. There's currently no health provider implemented in this plugin, so I'd not be surprised if there are some compatibility issues, so `:checkhealth` alone is currently not the best source for debugging.

Is the LSP server not starting in python files? Does the following run fine?

```sh
~/.local/share/nvim/lsp_servers/python/node_modules/.bin/pyright-langserver --stdio
```

**Comment by saltsucker** [comment]
I have a similar problem. I installed pyright and eslint through your plugin, and I get a 
`cmd ["vscode-eslint-language-server"] is not executable.`  (or same for pyright). Are we suppose to add  
`~/.local/share/nvim/lsp_servers/python/node_modules/.bin/pyright-langserver` to our $PATH?

**Comment by saltsucker** [comment]
This is what I get when I manually run the server
$ ~/.local/share/nvim/lsp_servers/python/node_modules/.bin/pyright-langserver --stdio
Content-Length: 119

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Pyright language server 1.1.189 starting"}}Content-Length: 180

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Server root directory: /usr2/goberlan/.local/share/nvim/lsp_servers/python/node_modules/pyright/dist/"}}

**Comment by HagaiHargil** [comment]
I get the exact same response as @saltsucker. It also seems weird to add such a path to PATH, and I don't remember having to fiddle with it in my previous setup. But there's definitely nothing stopping me from doing it :)

After adding it it gives this message when opening a Python file:

```
Error executing vim.schedule lua callback: /root/.config/nvim/lua/lsp.lua:7: Invalid option name 'omnfunc'
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        /root/.config/nvim/lua/lsp.lua:7: in function 'buf_set_option'
        /root/.config/nvim/lua/lsp.lua:10: in function '_on_attach'
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:253: in function '_setup_buffer'
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:172: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```
and when I run `LspInfo` it appears to be attached and running.

**Comment by williamboman** [comment]
> I have a similar problem. I installed pyright and eslint through your plugin, and I get a
> `cmd ["vscode-eslint-language-server"] is not executable.` (or same for pyright). Are we suppose to add
> `~/.local/share/nvim/lsp_servers/python/node_modules/.bin/pyright-langserver` to our $PATH? (and same for eslint)?

How are you setting up your servers? Did you read the [setup](https://github.com/williamboman/nvim-lsp-installer#setup) section in the README? No need to add anything to the $PATH, calling `server:setup()` will make sure to provide the correct path to the cmd.

> After adding it it gives this message when opening a Python file:

Looks like you've misspelled `omnifunc` somewhere in your config?

**Comment by HagaiHargil** [comment]
Indeed I had a misspelled "omnifunc" 🤦‍♂️ 

I also downgraded to 0.5.1 but I believe that it was due to that error on my end. 

I'll keep it open for @saltsucker. Thanks and sorry.

**Comment by saltsucker** [comment]
@HagaiHargil glad you got it working :)

> How are you setting up your servers? Did you read the [setup](https://github.com/williamboman/nvim-lsp-installer#setup) section in the README? No need to add anything to the $PATH, calling `server:setup()` will make sure to provide the correct path to the cmd.

I was able to get the servers to start up with just using your simple setup code in the README. 

However, I am having a new issue because your [`eslint](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/eslint/README.md)` code info isn't complete or something. 

(I apologize for the line numbers, i haven't figured out how to use clipboard while using windows terminal and ssh'd into work server yet)
```  
  1 local lsp_installer = require "nvim-lsp-installer"
  2
  3 -- Register a handler that will be called for all installed servers.
  4 -- Alternatively, you may also register handlers on specific server instances instead (see example below).
  5 lsp_installer.on_server_ready(function(server)
  6   local opts = {}
  7   if server.name == "eslint" then
  8     function common_on_attach(client, bufnr) ... end
  9     opts = {on_attach = common_on_attach}
 10     opts.on_attach = function (client, bufnr)
 11       client.resolved_capabilities.document_formatting = true
 12       common_on_attach(client, bufnr)
 13     end
 14     opts.settings = {
 15       format = {enable = true},
 16     }
 17   end
 18     -- (optional) Customize the options passed to the server
 19     -- if server.name == "tsserver" then
 20     --     opts.root_dir = function() ... end
 21     -- end
 22
 23     -- This setup() function is exactly the same as lspconfig's setup function.
 24     -- Refer to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
 25     server:setup(opts)
 26 end)
 ```
Line 8 throws this error when I try to source it: `E5112: Error while creating lua chunk: lua/plugins/lspinstaller.lua:8: unexpected symbol near '...'` 

So, what is this syntax, or what is it suppose to signify? I am new to Lua, so idk if i am suppose to assume to put something in there?

Also, when the eslint server starts, I get a `Unable to find ESLint library.` I assume I need to have eslint installed in the node_modules in the project?

**Comment by williamboman** [comment]
Correct!

**Comment by saltsucker** [comment]
Great, thanks so much for your help! I can also make a PR to make the example a little clearer if you don't have time for that :)

**Comment by williamboman** [comment]
That'd be very appreciated!

**Comment by saltsucker** [comment]
https://github.com/williamboman/nvim-lsp-installer/pull/282
