### ISSUE TITLE
lsp server binaray script add parameter

### ISSUE THREAD

**Issue by fcying** [williamboman/nvim-lsp-installer#279]
**Is your feature request related to a problem? Please describe.**
I want change clangd cmd options, e.g. `clangd --background-index --compile-commands-dir=xxx`
I use `path.concat { server.get_server_root_path('clangd'), 'clangd'` get clangd path, it is a script
```
cat ~/.vim/.cache/lsp_servers/clangd/clangd
#!/usr/bin/env sh
exec "/home/fcying/.vim/.cache/lsp_servers/clangd/clangd_13.0.0/bin/clangd"
```
It not accept parameter, add `$@` can work.
```
exec "/home/fcying/.vim/.cache/lsp_servers/clangd/clangd_13.0.0/bin/clangd" $@
```
Another way, it there any way to get clangd's real path? 
`/home/fcying/.vim/.cache/lsp_servers/clangd/clangd_13.0.0/bin/clangd`

**Comment by williamboman** [comment]
Hey! Yeah the `clangd` and `ltex` servers have some pretty bad historic design decisions. They both create this script file that is used as the executable. This is done as a method to permanently capture contextual information which is only available at install time (this is stored in the script file). There are some other, better, methods to solve this, like normalizing the filesystem output during the installation itself (this is done in all other servers).

#283 should hopefully make what you want to do much easier, as this plugin will no longer have to override the `cmd` but can instead just modify the path and leave the `cmd` entirely to lspconfig. This will also make providing a custom `cmd` more straight forward for users, in your case:

```
server:setup {
    cmd = { "clangd", "--background-index", "--compile-commands-dir=xxx" }
}

-- or perhaps even simpler:

table.insert(
    require("lspconfig").clangd.cmd,
    "--compile-commands-dir=xxx"
)
```

Will have to work out the most intuitive APIs for this going forward

**Comment by williamboman** [comment]
However it will take a while for that to merge as neovim nightly is currently needed. To solve this today you could probably do something like:

```lua
lsp_installer.on_server_ready(function (server)
  local opts = {}
  if server.name == "clangd" then
    opts.cmd = {
        vim.fn.expand(server.root_dir .. "clangd_*/bin/clangd"),
        "--background-index",
        "--compile-commands-dir=xxx"
    }
  end
  server:setup(opts)
end)
```

**Comment by fcying** [comment]
> 

tks, this work fine~
