### ISSUE TITLE
fsharp is error

### ISSUE THREAD

**Issue by chen244** [williamboman/nvim-lsp-installer#288]
**Describe the bug**
The path is wrong
It require the 

$HOME/.local/share/nvim/lsp_servers/fsautocomplete/fsautocomplete/dotnet-fsautocomplete
![image](https://user-images.githubusercontent.com/60290287/143687311-4f535cea-dd65-41ab-b89a-81a109da5d7c.png)

**Expected behavior**
Into the right path

**Screenshots**
![image](https://user-images.githubusercontent.com/60290287/143687311-4f535cea-dd65-41ab-b89a-81a109da5d7c.png)
![image](https://user-images.githubusercontent.com/60290287/143687539-dff0ad6e-a48e-46c7-8ab2-acd64ec5d740.png)

**System info (please complete the following information):**
 - OS: Archlinux linux 5.15
 - Neovim version:0.5.1

Please also include any other system information you think is relevant!

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

```
"rpc"	"dotnet"	"stderr"	"Could not execute because the specified command or file was not found.\nPossible reasons for this include:\n  * You misspelled a built-in dotnet command.\n  * You intended to execute a .NET program, but dotnet-fsautocomplete does not exist.\n  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.\n"
```

**Comment by williamboman** [comment]
Hello! I can't really tell what kind of file `fsautocomplete` is in your screenshot. Is it a directory? Is there anything in it? Maybe @kaashyapan recognizes the error?

**Comment by chen244** [comment]
> 

It is *.fs, In the root there is a App.fsproj

**Comment by chen244** [comment]
![image](https://user-images.githubusercontent.com/60290287/143728157-70ffc574-c69f-42b0-9cc0-19c0011920ca.png)

**Comment by chen244** [comment]
and fsx is the same

**Comment by chen244** [comment]
![image](https://user-images.githubusercontent.com/60290287/143732160-380ffa7e-f81a-410b-b682-457cbcbf5f3d.png)

**Comment by kaashyapan** [comment]
@chen244 
The tool name was changed from dotnet-fsautocomplete to fsautocomplete 10 days ago .

https://github.com/fsharp/FsAutoComplete/commit/dfcc63d3cd4f2803ceb53d3309e840caedf927b3#diff-fbfdf221e61d9ee5995990c90109910b3a1578733a6635662df3f6185b343384

Please feel free to PR the change that works for you. I cant get to a system now.

You may want to make sure you have the latest nvim-lspconfig for testing. 
See this....
https://github.com/neovim/nvim-lspconfig/pull/1477

**Comment by chen244** [comment]
> @chen244 The tool name was changed from dotnet-fsautocomplete to fsautocomplete 10 days ago .
> 
> [fsharp/FsAutoComplete@dfcc63d#diff-fbfdf221e61d9ee5995990c90109910b3a1578733a6635662df3f6185b343384](https://github.com/fsharp/FsAutoComplete/commit/dfcc63d3cd4f2803ceb53d3309e840caedf927b3#diff-fbfdf221e61d9ee5995990c90109910b3a1578733a6635662df3f6185b343384)
> 
> Please feel free to PR the change that works for you. I cant get to a system now.
> 
> You may want to make sure you have the latest nvim-lspconfig for testing. See this.... [neovim/nvim-lspconfig#1477](https://github.com/neovim/nvim-lspconfig/pull/1477)

https://github.com/williamboman/nvim-lsp-installer/pull/290
this is my pr
