### ISSUE TITLE
I can't set the root_dir in spectral lsp

### ISSUE THREAD

**Issue by A-Siam** [williamboman/nvim-lsp-installer#293]
**Note:** If this issue is not exactly related to the installer please let me know, Any guidance is much appreciated, I've very new to all of this btw 😅.

**What I've tried**

I've created this lua file for my custom server

```lua
local servers = require "nvim-lsp-installer.servers"
local server = require "nvim-lsp-installer.server"
local npm = require "nvim-lsp-installer.installers.npm"

local installer = npm.packages { "spectral-language-server" }

local server_name = "spectral"

local get_root_dir = function (sn)
  return server.get_server_root_path(sn)
end

local spectral_server = server.Server:new {
  name = server_name,
  root_dir = get_root_dir(server_name),
  installer = installer,
-- default options copied from the server config in lsp config
  default_options = {
        cmd = { "spectral-language-server", "--stdio" },
    filetypes = { "yaml", "json", "yml" },
    root_dir = function() -- [1] I don't know exactly that I should write here
        return get_root_dir(server_name)
      end,
    settings = {
      enable = true,
      run = "onType",
      validateLanguages = { "yaml", "json", "yml" }
    },
    single_file_support = true
  }
}
servers.register(spectral_server)
```
part of my issue is I can't write a suitable root_dir function [1], in the config guide https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#spectral There is `M` I don't know what it does refer to in this context.

The log from lsp-install seems normal
```
[DEBUG Mon 29 Nov 2021 04:02:47 AM EET] ...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:75: Attaching server to buffers spectral
[DEBUG Mon 29 Nov 2021 04:02:47 AM EET] ...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:86: Successfully attached server to buffers spectral
```
The log from lsp is 
```
[START][2021-11-29 04:02:47] LSP logging initiated
[ERROR][2021-11-29 04:02:51] .../vim/lsp/rpc.lua:417	"rpc"	"spectral-language-server"	"stderr"	"node:internal/modules/cjs/loader:936\n  throw err;\n  ^\n\nError: Cannot find module 'vscode-languageserver/lib/utils/is'\nRequire stack:\n- /home/a/.npm/lib/node_modules/spectral-language-server/dist/spectral-language-server/server.js\n- /home/a/.npm/lib/node_modules/spectral-language-server/bin/spectral-language-server\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n    at Module.require (node:internal/modules/cjs/loader:999:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/home/a/.npm/lib/node_modules/spectral-language-server/dist/spectral-language-server/server.js:7:14)\n    at Module._compile (node:internal/modules/cjs/loader:1097:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)\n    at Module.load (node:internal/modules/cjs/loader:975:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:999:19) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/a/.npm/lib/node_modules/spectral-language-server/dist/spectral-language-server/server.js',\n    '/home/a/.npm/lib/node_modules/spectral-language-server/bin/spectral-language-server'\n  ]\n}\n\nNode.js v17.1.0\n"
```

**Comment by williamboman** [comment]
Hello! Ah yes it seems like you're on the right track. The idea of the `root_dir` is different between `lspconfig` and `nvim-lsp-installer`. It's a bit unfortunate I ended up using the same name for a different concept. The `root_dir`  is responsible for the following ,respectively:

**lspconfig**
`root_dir` is a function that receives a `filename` and a `bufnr` as arguments. It needs to return the absolute path to a working directory in which lspconfig should start the server (aka root_dir, aka workspace folder). This is generally done by scanning the file system for the existence of certain files and/or directories. Usually one would start this scan from the directory of the provided `filename` argument, and continue upwards until the search pattern is found or until there are no more parent directories to traverse. A very common search pattern is the existence of a `.git/` directory, but some LSPs may also search for a specific file (for example GraphQL looks for a `.graphqlrc*` file).

**nvim-lsp-installer**
The `root_dir` property of a server instance controls where the server should be installed. This is only used when:

 - installing a server
 - uninstalling a server
 - telling lspconfig where to find the `cmd` to the server (this is done when calling `server:setup()`)

**Comment by williamboman** [comment]
I think we should add spectral to nvim-lsp-installer, it seems like a really straight forward server to install as it's just an npm package.

**Comment by williamboman** [comment]
Since lspconfig [already provide](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/spectral.lua) a default config for `spectral`, all you really need to do is override the `cmd`, like so:

```lua
local root_dir = get_root_dir(server_name)

local spectral_server = server.Server:new {
  name = server_name,
  root_dir = root_dir,
  installer = installer,
-- default options copied from the server config in lsp config
  default_options = {
        cmd = { npm.executable(root_dir, "spectral-language-server"), "--stdio" },
  }
}
```

**Comment by williamboman** [comment]
See #295 for adding this to nvim-lsp-installer. However there seem to be some potential issues with the npm package, see https://github.com/luizcorreia/spectral-language-server/issues/1

**Comment by A-Siam** [comment]
Thanks for your work I will check https://github.com/luizcorreia/spectral-language-server/issues/1. I think this issue should be closed now
