### ISSUE TITLE
Angularls does not work without adding to ngProbeLocations path

### ISSUE THREAD

**Issue by jaredrooprai** [williamboman/nvim-lsp-installer#300]
**Describe the bug**
Out of the box angularls does not work for me without changing `root_dir` to `root_dir .. "/node_modules/@angular/language-server"` for the `--ngProbeLocations` param. 

**Expected behavior**
A month ago I used angularls with this plugin and it worked without issue out of the box.
Today I was attempting to set up my configuration on a new mac and ran into an issue where the `ngProbeLocations` path could not be resolved by ngserver. I then re-installed angularls on my old mac and this issue came up there too. For now I have just fixed it in my local handler but i'm not sure if this is a change we would want to make in the plugins config itself.

**System info (please complete the following information):**
 - OS: [e.g. macOS 11.6]
 - Neovim version: v0.6.0

**Comment by williamboman** [comment]
Hey! So this was changed [here](https://github.com/williamboman/nvim-lsp-installer/pull/261), for some background context.

I did some more research how the VSCode client sets things up, and it seems like [they append the workspace directory to the probe locations](https://github.com/angular/vscode-ng-language-service/blob/b9d8bc7d9125e5775fd7d7f78f22f182499d59df/client/src/client.ts#L402-L418). I'll open a PR which mimics this behavior, hopefully it fixes things

**Comment by williamboman** [comment]
Could you give branch `fix-angularls-probe-locations` (#302) a try?

**Comment by jaredrooprai** [comment]
@williamboman I tested your branch and it worked perfectly

**Comment by williamboman** [comment]
:+1: does it still work with the latest commit (I just pushed https://github.com/williamboman/nvim-lsp-installer/pull/302/commits/b0e7641977fae43fe56e9b9f5f214d7fba89fb6b)?

**Comment by jaredrooprai** [comment]
yeah that commit is working for me as well
