### ISSUE TITLE
Make readme more noob friendly

### ISSUE THREAD

**Issue by juligreen** [williamboman/nvim-lsp-installer#301]
I spent quite some time trying to understand how to get the lsp keybinds described in the nvim-lspconfig's README until I read https://github.com/williamboman/nvim-lsp-installer/issues/244 .

Could this project's README include that you should remove the configuration from nvim-lspconfig?
Also it would be nice if it could also include the keybinds from the original readme.
Kind of like this:

```
local lsp_installer = require("nvim-lsp-installer")

-- Register a handler that will be called for all installed servers.
-- Alternatively, you may also register handlers on specific server instances instead (see example below).
lsp_installer.on_server_ready(function(server)
    local opts = {}

    -- (optional) Customize the options passed to the server
    -- if server.name == "tsserver" then
    --     opts.root_dir = function() ... end
    -- end

    -- This setup() function is exactly the same as lspconfig's setup function.
    -- Refer to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
    server:setup(opts)
  
  -- Add keybinds
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  -- Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  buf_set_keymap('n', '<space>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)

end)
``` 
　
Thank you! :)

**Comment by williamboman** [comment]
Hello! Hehe yeah this is good feedback, I'm aware it can be difficult to understand the relationship between this plugin and nvim-lspconfig at times. I have a few ideas in mind in terms of how to alleviate it in terms of changes to the APIs themsevles, as well as improving the docs with more explanations and, even better, illustrations. My excuse so far is that I'm sort of waiting for things to stabilize a bit, and as an example of a concrete thing would be waiting for lspconfig to cut the first official "release" on which it'll be safer to anchor to from a stability perspective.

**Comment by williamboman** [comment]
As for adding more to the example snippets - I'm a bit careful with what's put in them as I've noticed people have a tendency to just copy-paste things as-is. I really don't want to include keymaps snippets. I personally think (neo)vim is an editor that ought to be discovered through own learnings and experiments, and I'm not too sure the current docs really are that unclear? Tinkering and getting to know the plugins you install are part of that (like you just did :D). Also, projects like https://www.lunarvim.org/ exists which will more or less bootstrap a fully-fledged neovim environment that can be compared to other modern IDEs for you.

**Comment by juligreen** [comment]
Sure, that's certainly fine!
As soon as one knows that they don't need the nvim-lspconfig default configuration it's easy enough to figure out keybinds.

Cheers!
