### ISSUE TITLE
Custom filetypes are not respected

### ISSUE THREAD

**Issue by ErikEBZ** [williamboman/nvim-lsp-installer#303]
**Describe the bug**

Installed emmet_ls and it works on html and css files with no problem, but I would like be able to use emmet in js files. So to accomplish this i wrote the following if inside the `on_server_ready`:

```
-- LspConfig
local lsp_installer = require("nvim-lsp-installer")
lsp_installer.on_server_ready(function(server)
    local opts = {}

    -- (optional) Customize the options passed to the server
    -- if server.name == "tsserver" then
    --     opts.root_dir = function() ... end
    -- end

    if server.name == "emmet_ls" then
        opts.filetypes = {"html", "css", "javascript", "javascriptreact"}
    end

    -- This setup() function is exactly the same as lspconfig's setup function (:help lspconfig-quickstart)
    server:setup(opts)
    -- vim.cmd [[ do User LspAttachBuffers ]]
end
)
```

So the problem is: write and save the init.lua config file but `emmet_ls` only loads for `css, html` files, all `javascript` files are ignored by emmet_ls.

**Expected behavior**
To be able to use emmet inside `.js` files.

**Screenshots**
In this Screenshot we can see how emmet_ls is only loaded for css and html, ignoring the opts.filetype.
![image](https://user-images.githubusercontent.com/36607582/144620911-4d38204d-b897-4533-b95a-6faae276cfec.png)

**System info (please complete the following information):**
 - OS:  Arch Linux
 - Neovim version: v0.6.0

Well, i have spent like 3 hours trying to make emmet_ls work with javascript but i have not been able to, i would really appreciate the help with this :)

**Comment by williamboman** [comment]
Hey! That sounds odd, are your dotfiles public?

**Comment by ErikEBZ** [comment]
No (They are messy xd) but i can upload them to a gist:

init.lua: https://gist.github.com/ErikEBZ/eaaa225f06b3c7a629b96c57c96b804c
lua/plugins.lua: https://gist.github.com/ErikEBZ/905aa04cdf0f223b55ca1d54633e5409

**Comment by williamboman** [comment]
It seems like you're calling the `.on_server_ready()` function twice, [here](https://gist.github.com/ErikEBZ/eaaa225f06b3c7a629b96c57c96b804c#file-lua-L87) and [here](https://gist.github.com/ErikEBZ/eaaa225f06b3c7a629b96c57c96b804c#file-lua-L227). I honestly don't know in details what happens if you call `.setup()` on a server twice, but it's definitely not recommended :D. I imagine the latter `.on_server_ready()` will effectively override the first one.

**Comment by ErikEBZ** [comment]
I can't believe I didn't notice it, removing the second `.on_server_ready()` call fixed the problem, thank you so much :), now i think it detect the js as a css file but guess that is another thing to config.

**Comment by williamboman** [comment]
:+1: I know the emmet LSP is still bit early-stage, and I'm not sure it supports JavaScript files yet. Maybe https://github.com/aca/emmet-ls can provide some more insight
