### ISSUE TITLE
Phpactor server shows phpactor failed, matching root directory not detected

### ISSUE THREAD

**Issue by arionrefat** [williamboman/nvim-lsp-installer#312]
![image](https://user-images.githubusercontent.com/37513070/144853656-382c0a0a-9fe8-4687-82ab-f13aa0402bb6.png)
I can't find a proper solution online, what did I do wrong?

**Comment by williamboman** [comment]
Hey it seems like it's not finding a root directory to start the server in. This is also not an installer issue, maybe `:h lspconfig-root-detection` can provide more info? If you think it's a bug with the server config, then neovim/nvim-lspconfig is the repo to file an issue to 👍

**Comment by arionrefat** [comment]
Thank you!
