### ISSUE TITLE
New server request: sourcekit

### ISSUE THREAD

**Issue by jesse-c** [williamboman/nvim-lsp-installer#320]
**Which server would you like to request to be added?**
Server name: `sourcekit`
Server homepage (e.g., GitHub page): https://github.com/apple/sourcekit-lsp

**Which languages does this server target?**
Languages: Swift and C-based languages (C/C++/ObjC)

Related: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sourcekit

NB: Thank you for this project!

**Comment by williamboman** [comment]
Hello! I took a look at this but I'm struggling to understand how one installs/builds this as a standalone component? At first glance it seems like this ships with Xcode and Swift Toolchain. Do you perhaps know more?

**Comment by jesse-c** [comment]
Yes, you're correct it looks like. Aside from building from source, the only way to get a pre-built solution is a Swift toolchain (Xcode or standalone), which I imagine wouldn't fit into the use-case for this plugin.

**Comment by williamboman** [comment]
I wouldn't be opposed to building it if that makes sense for Swift devs. But this all feels kinda similar to how Dart does it, where the language server ships with the development platform/SDK itself. The rationale I've had so far with these kinds of servers is to not actually do custom builds or install the entire SDK within this plugin, but only verify that the platform is installed on the system (https://github.com/williamboman/nvim-lsp-installer/issues/252#issuecomment-968078522).

In this case, adding sourcekit here would be really easy as we'd only have to check that the `sourcekit-lsp` executable is available, and if it's not fail the installation with a helpful error message.

**Comment by jesse-c** [comment]
That makes sense!

https://github.com/williamboman/nvim-lsp-installer/issues/252#issuecomment-968078522 does look exactly what would be needed for this.

Since a PR would effectively seem quite straight-forward, I'd be happy to create one and test it locally, otherwise happy to leave it to you too.

**Comment by williamboman** [comment]
PR is very much welcomed!

**Comment by jesse-c** [comment]
https://github.com/williamboman/nvim-lsp-installer/pull/336 — just an issue with my env blocking me from finishing it.
