### ISSUE TITLE
MacOS LspInstall Fails, installation requires local user auth

### ISSUE THREAD

**Issue by pard68** [williamboman/nvim-lsp-installer#322]
**Describe the bug**
Running `:LspInstall` fails due to a need to authenticate as my local user

**Expected behavior**
I expect that when authentication is required the LspInstall command will prompt for username/password

**System info (please complete the following information):**

-   OS: macOS 12.1
-   Neovim version: 0.6

**Comment by williamboman** [comment]
Hello! I'll need some more information than this to know what might be happening. Which server(s) does this apply to? Could you also provide the installation logs?

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

```
Paste your logs here
```

**Comment by pard68** [comment]
Sorry, yes, I'm attempting to install `sumneko_lua`.

So, this is the LsPInstallLog:
```
[DEBUG Wed Dec  8 15:52:23 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:625: Queuing server="sumneko_lua", version="" for installation
[DEBUG Wed Dec  8 15:52:23 2021] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:628: Installer is already queued/running sumneko_lua
[DEBUG Wed Dec  8 15:52:23 2021] ...nvim-lsp-installer/lua/nvim-lsp-installer/ui/display.lua:396: Opening window
[DEBUG Wed Dec  8 15:58:45 2021] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:152: Job pid=93337 exited with exit_code=6, signal=0
[DEBUG Wed Dec  8 15:58:45 2021] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:296: Previous job failed, attempting next.
[DEBUG Wed Dec  8 15:58:45 2021] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:120: Spawning cmd="curl", spawn_opts={
  args = { "-fsSL", "-o", "archive.zip", "https://github.com/sumneko/vscode-lua/releases/download/v2.5.3/lua-2.5.3.vsix" },
  cwd = "/Users/ian/.local/share/nvim/lsp_servers/sumneko_lua.tmp"
}
[DEBUG Wed Dec  8 15:58:45 2021] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:166: Spawned with pid 93813
[DEBUG Wed Dec  8 16:01:16 2021] ...nvim-lsp-installer/lua/nvim-lsp-installer/ui/display.lua:199: Deleting window
```

The output of the LspInstall window states that it fails due to:
```
sumneko_lua (installer) Username/Password Authentication Failed.
```

**Comment by pard68** [comment]
Update, I fixed this. I can only assume there was at least one failed install in the past. The lsp server directory in the .local/share/nvim dir was a bit messed up. It contained a dir called `$HOME` and two sumneko_lua dirs. One was `sumneko_lua.tmp/` and the other was `sumneko_lua`. `sumneko_lua` contained a number of nested dirs with no files in it:

```
~/.local/share/nvim/lsp_servers/sumneko_lua/$HOME/.local/share/nvim/lsp_servers/sumneko_lua/```

Not sure how this was all created. Anyway it is now fixed. I have to assume the auth issue was related to maybe overwriting or deleting this dir?

**Comment by williamboman** [comment]
Huh.. that sounds really odd. Did you perhaps provide custom settings, especially a custom `install_dir`?

> So, this is the LsPInstallLog:

Is this the full log? It seems a bit cut off 🤔. 

Can you otherwise run the following in a shell window, without being prompted?

```sh
$ curl -fsSL "https://github.com/sumneko/vscode-lua/releases/download/v2.5.3/lua-2.5.3.vsix" > /dev/null
```

**Comment by pard68** [comment]
Yes, I can do that.
