### ISSUE TITLE
How to I make it work with null-ls

### ISSUE THREAD

**Issue by GZLiew** [williamboman/nvim-lsp-installer#327]
**Which server would you like to request to be added?**
Server name: null-ls
Server homepage (e.g., GitHub page): https://github.com/jose-elias-alvarez/null-ls.nvim

**Comment by williamboman** [comment]
Hello! null-ls is not really a language server per se, it just implements the LSP spec to interface with non-LSP tools such as prettier. There is an existing feature request (#95) to enable installation of tools enabled through null-ls which you may follow for updates.
