### ISSUE TITLE
Autostart for efm failed

### ISSUE THREAD

**Issue by thebluelake** [williamboman/nvim-lsp-installer#335]
**Describe the bug**
After installing the efm server I get this error message whenever I open up nvim

**Expected behavior**
I want to make efm server work and get autoformatting working with the lsp

**Screenshots**
![image](https://user-images.githubusercontent.com/96130308/146022863-cc7416e0-6043-4da0-aa7e-9c9eef8e448a.png)

**System info (please complete the following information):**

-   OS: WSL 2 Ubuntu
-   Neovim version: 0.6.0 stable

Checkhealth output (`:checkhealth nvim-lsp-installer`):

```
Paste `:checkhealth nvim-lsp-installer` output here
```
![image](https://user-images.githubusercontent.com/96130308/146023034-fc316cef-81d5-4b33-89eb-2ef63d915181.png)

Please also include any other system information you think is relevant!

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

```
Paste your logs here
```
If you need any other info please feel free to ask! Thank you

**Comment by williamboman** [comment]
Hello! See the following resources for more information on how the EFM language server works:

- https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#efm
- `:help lspconfig-root-detection`
- https://github.com/mattn/efm-langserver#efm-langserver

I've never used the EFM server myself, so I'm afraid I can't help more than that. I'm sure the resource above will have the answers though!

**Comment by thebluelake** [comment]
Thanks! Will go and take a look
