### ISSUE TITLE
Can't install ccls server

### ISSUE THREAD

**Issue by phanlong2811** [williamboman/nvim-lsp-installer#337]
**Describe the bug**
Can't install ccls server

**Expected behavior**
Command line execution ":LspInstall ccls"

**Screenshots**
![image](https://user-images.githubusercontent.com/44520002/146349133-7d5c9d7a-27bc-4d55-a4df-1c6d2603ea7a.png)
![image](https://user-images.githubusercontent.com/44520002/146349401-412147fd-7e45-417f-8a96-c0bc09591133.png)

**System info (please complete the following information):**

-   OS: Ubuntu 20.10
-   Neovim version: NVIM v0.6.0

Checkhealth output (`:checkhealth nvim-lsp-installer`):
![image](https://user-images.githubusercontent.com/44520002/146349544-1f86f89a-3dd9-4a61-8d37-eb23b61ad6c6.png)

```
Paste `:checkhealth nvim-lsp-installer` output here
```
```

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - ERROR: **Composer**: not available
  - ERROR: **java**: not available
  - ERROR: **sh**: not available
  - INFO: **tar**: `tar (GNU tar) 1.34`
  - INFO: **gzip**: `gzip 1.10`
  - INFO: **wget**: `GNU Wget 1.21 built on linux-gnu.`
  - INFO: **python3**: `Python 3.8.8`
  - INFO: **PHP**: `PHP 7.4.16 (cli) (built: Oct 26 2021 16:46:20) ( NTS )`
  - INFO: **Ruby**: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]`
  - INFO: **Go**: `go version go1.17.5 linux/amd64`
  - INFO: **bash**: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
  - INFO: **curl**: `curl 7.71.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1k zlib/1.2.11 libssh2/1.9.0`
  - INFO: **RubyGem**: `3.2.5`
  - INFO: **pip3**: `pip 21.0.1 from /home/phanlong2811/anaconda3/lib/python3.8/site-packages/pip (python 3.8)`
  - INFO: **node**: `v14.18.2`
  - INFO: **npm**: `6.14.15`


```
Please also include any other system information you think is relevant!

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

```
Paste your logs here
```
        Submodule path 'third_party/rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
        -- The CXX compiler identification is GNU 10.3.0
        -- The C compiler identification is GNU 10.3.0
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: /usr/bin/c++ - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: /usr/bin/cc - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
        -- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
        -- Looking for pthread.h
        -- Looking for pthread.h - found
        -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
        -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
        -- Check if compiler accepts -pthread
        -- Check if compiler accepts -pthread - yes
        -- Found Threads: TRUE  
        -- RapidJSON found. Headers: /usr/include
        -- Configuring done
        fatal: No names found, cannot describe anything.
        -- Generating done
        -- Build files have been written to: /home/phanlong2811/.local/share/nvim/lsp_servers/ccls/ccls/Release
        Scanning dependencies of target ccls
        [  2%] Building CXX object CMakeFiles/ccls.dir/third_party/siphash.cc.o
        [  4%] Building CXX object CMakeFiles/ccls.dir/src/clang_tu.cc.o
        [  6%] Building CXX object CMakeFiles/ccls.dir/src/config.cc.o
        [  9%] Building CXX object CMakeFiles/ccls.dir/src/filesystem.cc.o
        [ 11%] Building CXX object CMakeFiles/ccls.dir/src/fuzzy_match.cc.o
        [ 13%] Building CXX object CMakeFiles/ccls.dir/src/main.cc.o
        [ 16%] Building CXX object CMakeFiles/ccls.dir/src/include_complete.cc.o
        [ 18%] Building CXX object CMakeFiles/ccls.dir/src/indexer.cc.o
        [ 20%] Building CXX object CMakeFiles/ccls.dir/src/log.cc.o
        [ 23%] Building CXX object CMakeFiles/ccls.dir/src/lsp.cc.o
        [ 25%] Building CXX object CMakeFiles/ccls.dir/src/message_handler.cc.o
        [ 27%] Building CXX object CMakeFiles/ccls.dir/src/pipeline.cc.o
        [ 30%] Building CXX object CMakeFiles/ccls.dir/src/platform_posix.cc.o
        [ 32%] Building CXX object CMakeFiles/ccls.dir/src/platform_win.cc.o
        [ 34%] Building CXX object CMakeFiles/ccls.dir/src/position.cc.o
        [ 37%] Building CXX object CMakeFiles/ccls.dir/src/project.cc.o
        [ 39%] Building CXX object CMakeFiles/ccls.dir/src/query.cc.o
        In file included from /home/phanlong2811/.local/share/nvim/lsp_servers/ccls/ccls/src/indexer.hh:6,
                         from /home/phanlong2811/.local/share/nvim/lsp_servers/ccls/ccls/src/query.hh:6,
                         from /home/phanlong2811/.local/share/nvim/lsp_servers/ccls/ccls/src/query.cc:4:
        /home/phanlong2811/.local/share/nvim/lsp_servers/ccls/ccls/src/lsp.hh: In function ‘std::optional<ccls::SymbolInformation> ccls::getSymbolInfo(ccls::DB*, ccls::SymbolIdx, bool)’:
        /home/phanlong2811/.local/share/nvim/lsp_servers/ccls/ccls/src/lsp.hh:179:8: warning: ‘info.ccls::SymbolInformation::kind’ may be used uninitialized in this function [-Wmaybe-uninitialized]
          179 | struct SymbolInformation {
              |        ^~~~~~~~~~~~~~~~~
        [ 41%] Building CXX object CMakeFiles/ccls.dir/src/sema_manager.cc.o
        [ 44%] Building CXX object CMakeFiles/ccls.dir/src/serializer.cc.o
        [ 46%] Building CXX object CMakeFiles/ccls.dir/src/test.cc.o
        [ 48%] Building CXX object CMakeFiles/ccls.dir/src/utils.cc.o
        [ 51%] Building CXX object CMakeFiles/ccls.dir/src/working_files.cc.o
        [ 53%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_call.cc.o
        [ 55%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_info.cc.o
        [ 58%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_inheritance.cc.o
        [ 60%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_member.cc.o
        [ 62%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_navigate.cc.o
        [ 65%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_reload.cc.o
        [ 67%] Building CXX object CMakeFiles/ccls.dir/src/messages/ccls_vars.cc.o
        [ 69%] Building CXX object CMakeFiles/ccls.dir/src/messages/initialize.cc.o
        [ 72%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_code.cc.o
        [ 74%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_completion.cc.o
        [ 76%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_definition.cc.o
        [ 79%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_did.cc.o
        [ 81%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_foldingRange.cc.o
        [ 83%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_formatting.cc.o
        [ 86%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_document.cc.o
        [ 88%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_hover.cc.o
        [ 90%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_references.cc.o
        [ 93%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_rename.cc.o
        [ 95%] Building CXX object CMakeFiles/ccls.dir/src/messages/textDocument_signatureHelp.cc.o
        [ 97%] Building CXX object CMakeFiles/ccls.dir/src/messages/workspace.cc.o
        [100%] Linking CXX executable ccls
        /usr/bin/ld: cannot find -lexecinfo
        collect2: error: ld returned 1 exit status
        gmake[2]: *** [CMakeFiles/ccls.dir/build.make:761: ccls] Error 1
        gmake[1]: *** [CMakeFiles/Makefile2:207: CMakeFiles/ccls.dir/all] Error 2
        gmake: *** [Makefile:149: all] Error 2

**Comment by kylo252** [comment]
Try installing

```shell
sudo apt install libncurses-dev
```

Ref: https://github.com/MaskRay/ccls/wiki/Build

**Comment by phanlong2811** [comment]
> Try installing
> 
> ```shell
> sudo apt install libncurses-dev
> ```
> 
> Ref: https://github.com/MaskRay/ccls/wiki/Build

I installed it before but it still wrong

**Comment by williamboman** [comment]
This is probably because we're not always downloading the correct llvm distribution (on Linux). I've pushed to branch `fix-ccls` - could you give it a try?

**Comment by phanlong2811** [comment]
> This is probably because we're not always downloading the correct llvm distribution (on Linux). I've pushed to branch `fix-ccls` - could you give it a try?
This is the result when I tried
![image](https://user-images.githubusercontent.com/44520002/146488331-6b2fcccf-35d1-45e5-9307-83c7f3dcb5c5.png)

**Comment by williamboman** [comment]
Can you try the latest version of that branch? Should <sup>probably</sup> work now

**Comment by phanlong2811** [comment]
> Can you try the latest version of that branch? Should probably work now
Not working
![image](https://user-images.githubusercontent.com/44520002/146628912-f3ad3e36-08c1-4467-ad56-b018330e5057.png)

**Comment by williamboman** [comment]
Ah I didn't consider versions above 20.04 - could you try once more 🙏?

**Comment by phanlong2811** [comment]
> Ah I didn't consider versions above 20.04 - could you try once more pray?

![image](https://user-images.githubusercontent.com/44520002/146648984-b8fea937-f5b1-4705-96d7-f35d569b698c.png)

the installation is successful but it gives error
![image](https://user-images.githubusercontent.com/44520002/146648998-759fda2e-d572-4d3b-b844-52bf4bb8ac00.png)

**Comment by kylo252** [comment]
Just create a `.ccls` file in the same directory.

see: `:h lspconfig-root-detection`
https://github.com/neovim/nvim-lspconfig/blob/0f72e5468e510429d5f14b73c93fb528ead1fdaa/lua/lspconfig/server_configurations/ccls.lua#L7

**Comment by phanlong2811** [comment]
Thanks everyone, it worked <3
