### ISSUE TITLE
Fails to install latest sumneko_lua

### ISSUE THREAD

**Issue by Backman** [williamboman/nvim-lsp-installer#339]
**Describe the bug**
Fails to run `LspInstall: lua` when selecting `sumneko_lua`. It tries to fetch `lua-2.5.5.vsix` but since `sumneko_lua v2.5.4` there are [OS-specific versions provided.](https://github.com/sumneko/vscode-lua/releases)

**Expected behavior**
The `sumneko_lua` server should be installed successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/2965716/146511428-369cd543-856c-4893-b7a5-3d9a8a1f8b30.png)

**System info (please complete the following information):**

-   OS: Windows 10.0.19042 Build 19042
-   Neovim version: NVIM v0.6.1-dev+658-gbd057d4b4

**Comment by williamboman** [comment]
Ah I see. For now you should at least still be able to install an older version via `:LspInstall sumneko_lua@v2.5.3`
