### ISSUE TITLE
vim.lsp.diagnostic.get_count Warning

### ISSUE THREAD

**Issue by mrxiaozhuox** [williamboman/nvim-lsp-installer#346]
When I use `lsp-installer` install some lsp like `denols` and `rust`, and open a code file, then this warning info will be display:
```
vim.lsp.diagnostic.get_count is deprecated. See :h deprecated
```

**Comment by mrxiaozhuox** [comment]
I use the config system with: `NvChad` and I use `Packer` to install the `lsp-installer`. [system: WSL2-Ubuntu]

**Comment by williamboman** [comment]
Hi! This plugin doesn't make any calls to `vim.lsp`, so this is probably something in your own config (or in NvChad). Reading the `:h deprecated` docs might be a good start!

**Comment by mrxiaozhuox** [comment]
thanks.

**Comment by vlstv** [comment]
@mrxiaozhuox It is probably in galaxyline plugin
