### ISSUE TITLE
[New server request] taplo-lsp

### ISSUE THREAD

**Issue by zmtq05** [williamboman/nvim-lsp-installer#354]
**Which server would you like to request to be added?**

- Server name: `taplo-lsp`
- Server homepage (e.g., GitHub page):
  - https://taplo.tamasfe.dev/lsp/
  - https://github.com/tamasfe/taplo

**Which languages does this server target?**

- Languages: `toml`

**How is this server distributed?**

- Is the server distributed through a standardized channel (such as release files, npm, pip, etc.)? (leave empty if unknown):
  - [`cargo install`](https://crates.io/crates/taplo-lsp)
- Is this server added in [lspconfig](https://github.com/neovim/nvim-lspconfig)?:
  - https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#taplo

**Comment by williamboman** [comment]
Hello! Cool! Could you give #373 (branch `add-taplo`) a try? I wrote a comment in that PR about an issue I'm personally experiencing, are you getting the same?
