### ISSUE TITLE
ccls install failed

### ISSUE THREAD

**Issue by MohamedIrfanAM** [williamboman/nvim-lsp-installer#355]
**Describe the bug**
Tried to install ccls with `:LspInstallInfo` but the installation failed

**Screenshots**

![image](https://user-images.githubusercontent.com/64521698/147362506-6d8e69f1-99e9-43ad-a946-f933831d9cb5.png)

**System info (please complete the following information):**

-   OS: ArchLinux
-   Neovim version:0.7

Check health output (`:checkhealth nvim-lsp-installer`):
```
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - WARNING: **Go**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **java**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.10`
  - OK: **curl**: `curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.75.0 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0`
  - OK: **wget**: `GNU Wget 1.21.1 built on linux-gnu.`
  - OK: **python3**: `Python 3.9.2`
  - OK: **node**: `v15.12.0`
  - OK: **Ruby**: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
  - OK: **RubyGem**: `3.2.13`
  - OK: **npm**: `7.7.5`
  - OK: **pip3**: `pip 20.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)`
```
My issue is similar to this https://github.com/williamboman/nvim-lsp-installer/issues/337
I tried installing `llvm`,`clang` using pacman, still, the issue persists
I used to use `ccls` with `coc` before

**Comment by JcdeA** [comment]
Having the same issue, using Arch Linux

**Comment by williamboman** [comment]
Hello! It's been quite unclear to me to what degree the LLVM release binaries can be used on different Linux distros. Could you provide the last couple of lines of the build output? In the screenshot there's only output for `tar` unpacking stuff

**Comment by ruanyouxing** [comment]
the last lines are:
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libtinfo.so, needed by 'ccls'. Stop'
make[1]: ***[CmakeFiles/Makefile:87: CmakeFiles/ccls.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by ruanyouxing** [comment]
I use Arch and have a same problem with him so...
![2021-12-26-223650_1024x600_scrot](https://user-images.githubusercontent.com/87190231/147413036-aa36460b-24df-45d9-beda-02720507d999.png)

**Comment by williamboman** [comment]
@ruanyouxing Could you try the branch `fix-ccls-arch-linux`?

**Comment by ruanyouxing** [comment]
it builed to 100% but it have a new error:
[100%] Linking CXX executable ccls
/usr/bin/ld: cannot find -lexecinfo
collect2: error: ld returned 1 exit status
make[2]: *** [CmakeFiles/ccls.dir/build.make:796: ccls] Error 1
make[1]: *** [CmakeFiles/Makefile2:87: CmakeFiles/ccls.dir/all] Error 2
make: ***[Makefile:146: all] Error 2

**Comment by MohamedIrfanAM** [comment]
@williamboman Sorry for the late reply
Screenshot of `fix-ccls-arch-linux`
![image](https://user-images.githubusercontent.com/64521698/147425654-7b87487a-e419-44cf-9c71-8a977014769b.png)

**Comment by JuniorSuperTux** [comment]
Same error here on Ubuntu Server 20.04 LTS. Has the same output as the original screenshot of the issue.

**Comment by williamboman** [comment]
@JuniorSuperTux Hmm Ubuntu should work fine 🤔. Are you on the latest plugin version? Usually it's the very last few lines that have the interesting information, in OPs screenshot we only see `tar` unpacking stuff (so it'll look the same for everyone, even if it's successful). If you're on the latest plugin version and it still doesn't work, make sure you have `libncurses5` installed (`sudo apt install libncurses5`)

**Comment by ruanyouxing** [comment]
so how about arch?

**Comment by williamboman** [comment]
> so how about arch?

It seems like the proposed fix fixed the first issue, but produced another one. There's apparently some BSD-specific artifacts in the LLVM distribution. I'll need to set up an Arch container to properly debug this, will do so when I find the time. If you'd like to try and build ccls manually and report back what worked that'd be helpful as well.

Otherwise I believe ccls is distributed among most package managers, so for the time being you might want to manage it outside of nvim-lsp-installer (I'm somewhat starting to lean towards removing ccls from this plugin due to how difficult it is to provide cross-platform support, or at the very least tightening the requirements a bit). To set up ccls outside of nvim-lsp-installer you may interact directly with lspconfig, like so:

```lua
local lspconfig = require("lspconfig")

lspconfig.ccls.setup {}
```

**Comment by kylo252** [comment]
> I'm somewhat starting to lean towards removing ccls from this plugin due to how difficult it is to provide cross-platform support

I'm very much in favor of removing this until it's guaranteed that the cmake recipe can handle finding all the dependencies. The overhead here is way over what's reasonable, imho.

It's worth mentioning that ccls has _barely_ had 10 commits over this past year compared to the very active and capable clangd.

**Comment by williamboman** [comment]
> I'm very much in favor of removing this until it's guaranteed that the cmake recipe can handle finding all the dependencies. The overhead here is way over what's reasonable, imho.

Let's give the following mechanism a try first: If prebuilt clang+llvm distribution exist for the current OS & arch, install and use it for building. Otherwise default to using system clang+llvm (on macOS we can definitely check whether this exists because we just use Homebrew, with Linux we'll let the build fail if these deps aren't installed).

**Comment by williamboman** [comment]
See #414 for impl

**Comment by williamboman** [comment]
@ruanyouxing @MohamedIrfanAM try pulling the latest plugin version and install `ccls` now. You will have to install `llvm` separately before that though:

```
$ pacman -Sy llvm
```

**Comment by MohamedIrfanAM** [comment]
@williamboman  It works!!. Thank you

**Comment by ruanyouxing** [comment]
> @ruanyouxing @MohamedIrfanAM try pulling the latest plugin version and install `ccls` now. You will have to install `llvm` separately before that though:
> 
> ```
> $ pacman -Sy llvm
> ```

i did it but when i tried to install ccls again, it still says 'cannot find -lexecinfo' and quit the installation
![image](https://user-images.githubusercontent.com/87190231/149263132-ba3e1760-6197-4c9c-befa-2f4e76672452.png)

**Comment by williamboman** [comment]
@ruanyouxing Could you submit a new issue, using the [appropriate issue template](https://github.com/williamboman/nvim-lsp-installer/issues/new?assignees=&labels=server-issue&template=server_installation_form.yaml) :pray:? It's so much easier for me if the information that's being asked for in that form is provided from the start.

If you'd like to do some investigation on your own, I'd recommend trying to compile ccls yourself by following the instructions [here](https://github.com/MaskRay/ccls/wiki/Build), this could help determine whether it's a plugin issue or a broader issue with your system.

**Comment by MSMazaya** [comment]
> @ruanyouxing Could you submit a new issue, using the [appropriate issue template](https://github.com/williamboman/nvim-lsp-installer/issues/new?assignees=&labels=server-issue&template=server_installation_form.yaml) pray? It's so much easier for me if the information that's being asked for in that form is provided from the start.
> 
> If you'd like to do some investigation on your own, I'd recommend trying to compile ccls yourself by following the instructions [here](https://github.com/MaskRay/ccls/wiki/Build), this could help determine whether it's a plugin issue or a broader issue with your system.

This really helps, i was here to search for an answer to my ccls install bug. But after looking at the [instructions](https://github.com/MaskRay/ccls/wiki/Build) you mentioned and install all the required dependencies there, it automatically works :D
