### ISSUE TITLE
sumneko_lua download 404s

### ISSUE THREAD

**Issue by zfogg** [williamboman/nvim-lsp-installer#356]
looks like the binary release url is broken:

![image](https://user-images.githubusercontent.com/774794/147370088-946d0c9b-a488-465d-a282-91adfd37816e.png)
![image](https://user-images.githubusercontent.com/774794/147370101-ebfced2d-00e2-4114-adaa-5f363e07342c.png)

see?

**Comment by williamboman** [comment]
Hey! Try updating your plugins, this was fixed recently! If your plugin versions are pinned, you can still `:LspInstall sumneko_lua@v2.5.3`
