### ISSUE TITLE
linting errors in .ts, .tsx files when tsserver and deno are installed

### ISSUE THREAD

**Issue by jose4125** [williamboman/nvim-lsp-installer#366]
**Describe the bug**
linting errors in .ts, .tsx files when tsserver and deno are installed #366

**Expected behavior**
Should attached just the tsserver. not the deno server

**Screenshots**
<img width="1465" alt="Screen Shot 2021-12-26 at 9 21 06 PM" src="https://user-images.githubusercontent.com/1216119/147428220-680c7935-82a9-41e8-a0a8-937c1388fab4.png">

**System info (please complete the following information):**

-   OS: macOS 12.1
-   Neovim version: NVIM v0.6.0-dev+604-g725cbe7d4

previously I was not using nvim-lsp-installer. I was having the same issue. the following lines fixed it
```
function file_exists(name)
    local f = io.open(name, 'r')
    if f ~= nil then io.close(f) return true else return false end
end

if file_exists(os.getenv('PWD')..'/package.json') then
    require'lspconfig'.tsserver.setup {}
else
    require'lspconfig'.denols.setup{}
end
```
How I can do something like that

**Comment by williamboman** [comment]
Hello! You could translate that as-is

```lua
local package_json_exists = file_exists(vim.loop.cwd() .. '/package.json')

lsp_installer.on_server_ready(function (server)
    if server.name == "denols" and package_json_exists then
        return
    elseif server.name == "tsserver" and not package_json_exists then
        return
    end
    server:setup {}
end)
```

I'd however recommend looking into the `root_dir` mechanism of lspconfig to control when servers are started instead (see `:h lspconfig-root-dir`). It can be a bit tricky at first and you have to read up on how it works, but something like this ought to achieve the same thing:

```lua
local lsp_installer = require("nvim-lsp-installer")
local lspconfig_util = require("lspconfig.util")

local tsserver_root_dir = util.root_pattern "package.json"
local denols_root_dir = util.root_pattern("deno.json", "deno.jsonc", "tsconfig.json", ".git")

lsp_installer.on_server_ready(function (server)
    local opts = {}
    if server.name == "denols" then
        opts.root_dir = function (fname)
            return not tsserver_root_dir(fname) and denols_root_dir(fname)
        end
    elseif server.name == "tsserver" and not package_json_exists then
        opts.root_dir = tsserver_root_dir
    end
    server:setup(opts)
end)
```
