### ISSUE TITLE
[New Server Request]: Integrate solc 0.8.11's LSP server

### ISSUE THREAD

**Issue by OliverNChalk** [williamboman/nvim-lsp-installer#368]
**Which server would you like to request to be added?**

-   Server name: `solc` LSP
-   Server homepage (e.g., GitHub page): https://github.com/ethereum/solidity/releases/tag/v0.8.11

**Which languages does this server target?**

-   Languages: `solidity`

**How is this server distributed?**

-   Is the server distributed through a standardized channel (such as release files, npm, pip, etc.)? (leave empty if unknown): there are [js bindings](https://github.com/ethereum/solc-js) but that introduces overhead. If possible it'd be preferable to pull a system-dependent release from their github releases channel.
-   Is this server added in [lspconfig](https://github.com/neovim/nvim-lspconfig)?: Not for `solc`

**Comment by williamboman** [comment]
Hello! Cool! I remember reading about this being in the works. Happy to receive PR (also, lspconfig needs to be covered first), otherwise I'll look into it eventually

**Comment by OliverNChalk** [comment]
Issue opened with [lspconfig](https://github.com/neovim/nvim-lspconfig/issues/1622), I have not written a line of Lua / explored neovim scripting so I'll probably have to tap out of this one. I consumer LunarVim repo so am pushing these issues through as I think there is definitely some desire for strong solidity support in neovim

**Comment by williamboman** [comment]
- https://github.com/neovim/nvim-lspconfig/pull/1623
- https://github.com/williamboman/nvim-lsp-installer/pull/371

**Comment by williamboman** [comment]
> I have not written a line of Lua / explored neovim scripting

Understandable! Lua is probably the simplest language there ever was (in a positive way), so don't be afraid of it. Neovim is also very friendly to get into as there's a tremendous amount of docs (`:help` is your friend).
