### ISSUE TITLE
[question] is there any way let pylsp get system pip package ?

### ISSUE THREAD

**Issue by fcying** [williamboman/nvim-lsp-installer#374]
default  `pylsp` is install by `venv`, it can't search  system pip package.

If I install same package in `venv` it can work( use PylspInstall xxx)), 
but this is a bit cumbersome to use.

Is there any way let pylsp get system pip package?

**Comment by williamboman** [comment]
Hello! I believe this should be configurable when setting up the server (settings can be found [here](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md)). Why does pylsp need to access system packages?

**Comment by williamboman** [comment]
I also found https://github.com/python-lsp/python-lsp-server/issues/29 which seems to ask the same question. https://github.com/python-lsp/python-lsp-server/issues/29#issuecomment-882161177 seems to suggest configuring the `pylsp.plugins.jedi.environment` setting

**Comment by fcying** [comment]
Thanks, this is exactly what i need.

after set `jedi = { environment = '/usr/bin/python3' }`, it can search system pip packages.
