### ISSUE TITLE
[new LSP] Language server for NASM/GAS/GO Assembly

### ISSUE THREAD

**Issue by shaeinst** [williamboman/nvim-lsp-installer#378]
**Which server would you like to request to be added?**

-   Server name: asm-lsp
-   Server homepage (e.g., GitHub page): https://github.com/bergercookie/asm-lsp

**Which languages does this server target?**

-   Languages: NASM/GAS/GO Assembly

**How is this server distributed?**

-   Is the server distributed through a standardized channel (such as release files, npm, pip, etc.)? (leave empty if unknown):
-   Is this server added in [lspconfig](https://github.com/neovim/nvim-lspconfig)?: NO

**Comment by williamboman** [comment]
https://github.com/neovim/nvim-lspconfig/pull/1652

**Comment by williamboman** [comment]
Added in #411
