### ISSUE TITLE
sumneko-lua does not work

### ISSUE THREAD

**Issue by Q-Xue** [williamboman/nvim-lsp-installer#381]
**Describe the bug**
I am on windows system. I installed lsp with this plugin for vim, pyright, c. Thay all work. I also installed sumneko-lua, LspInstallInfo shows that the installation is successful, but when I open a lua file, an error is reported: cmd is not defined. I enter :LspInfo, it shows that 0 server is attached to the buffer. cmd is not defined... There is a linking problem here?

**Expected behavior**
It should work the same as other lsp.

**Screenshots**
![1641276458](https://user-images.githubusercontent.com/34317733/148016545-1b0e7161-2a55-4c94-a0a7-772675fb24e7.png)
![1641276507(1)](https://user-images.githubusercontent.com/34317733/148016615-9ee029d7-9a1c-484b-a232-bdeb22cbdefe.png)

**System info (please complete the following information):**

-   OS: [e.g. macOS 12.1]
-   Neovim version:

Checkhealth output (`:checkhealth nvim-lsp-installer`):

```
Paste `:checkhealth nvim-lsp-installer` output here
```

Please also include any other system information you think is relevant!

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

```
Paste your logs here
```

**Comment by williamboman** [comment]
Hello! Try upgrading your lspconfig plugin, the default `cmd` was added there about a month ago

**Comment by Q-Xue** [comment]
It works. Thanks a lot!
