### ISSUE TITLE
New server request: rnix-lsp (for Nix)

### ISSUE THREAD

**Issue by kradalby** [williamboman/nvim-lsp-installer#382]
**Which server would you like to request to be added?**

-   Server name: rnix-lsp
-   Server homepage (e.g., GitHub page): https://github.com/nix-community/rnix-lsp

**Which languages does this server target?**

-   Languages: [Nix](https://github.com/NixOS/nix)

**How is this server distributed?**

-   Is the server distributed through a standardized channel (such as release files, npm, pip, etc.)?: [Cargo](https://crates.io/crates/rnix-lsp)
-   Is this server added in [lspconfig](https://github.com/neovim/nvim-lspconfig)?: [yes](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/rnix.lua)

**Comment by williamboman** [comment]
Hello! Could you give branch `add-rnix` (#408) a try?

**Comment by kradalby** [comment]
I am seeing:

```
[nvim-lsp-installer] /Users/kradalby/.config/nvim/lua/lsp.lua:60: attempt to call field 'executable' (a nil value)
```

When I start nvim after switching to the branch.

But the server installs fine and seem to work as intended :)

**Comment by williamboman** [comment]
Ah that's probably due to some other recent change, where the `executable()` functions were removed in favor of providing the `PATH` env instead, more info the commit message here: https://github.com/williamboman/nvim-lsp-installer/commit/095ab4eb6a02d5fd3ea4b782a0e868e2c65e4427
