### ISSUE TITLE
Unable to install `clangd` & `checkhealth nvim-lsp-installer` fails too

### ISSUE THREAD

**Issue by shrkamat** [williamboman/nvim-lsp-installer#384]
**Describe the bug**
clangd wouldn't install
checkhealth nvim-lsp-installer fails

**Expected behavior**
clangd install should succeed

**Screenshots**
PSB

**System info (please complete the following information):**

-   OS: Linux / Ubuntu
-   Neovim version:  0.6
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9/build/config -I/build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9/src -I/build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9/build/src/nvim/auto -I/build/neovim-0bOHCD/neovim-0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9/build/include
Compiled by buildd@lgw01-amd64-059
```

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

Checkhealth output (`:checkhealth nvim-lsp-installer`):
![Failure](https://i.imgur.com/kb0rJpS.png)

```
":help feature-compile
```

Please also include any other system information you think is relevant!

**Install log**
If applicable, include nvim-lsp-installer's logs. See `:help nvim-lsp-installer-debugging` for instructions on how to set the log level and access the logs.

![Failure](https://i.imgur.com/0CuZHVj.png)

**Comment by shrkamat** [comment]
After pulling in latest 0.6.1 neovim release, this issue is resolved.

**Comment by williamboman** [comment]
Cool! Yeah 0.6.0 is now required because usage of `vim.json`. I'll look into the checkhealth issue though, it's intended to work on 0.5.0
