### ISSUE TITLE
ltex is not find in path

### ISSUE THREAD

**Issue by grimgort** [williamboman/nvim-lsp-installer#385]
ltex is not find in path. This plugin working before recent update . Windows 10 OS
![image](https://user-images.githubusercontent.com/44238325/148093756-0b63ccfe-13df-46ed-b3dd-8556a867b412.png)
![image](https://user-images.githubusercontent.com/44238325/148093806-09b223d4-c6ab-4b5f-9254-9a1cfc9cbd94.png)

**Comment by williamboman** [comment]
Hello! Did you try reinstalling it after pulling the latest plugin version? There was a commit recently that had a breaking change for `ltex` and `clangd`, see https://github.com/williamboman/nvim-lsp-installer/issues/387

**Comment by williamboman** [comment]
Ah wait, are you on Windows? The cmd for `ltex` on Windows turned out to be incorrect in lspconfig, see: https://github.com/neovim/nvim-lspconfig/pull/1628. Until that PR is merged, you can fix this by overriding the command yourself:

```lua
lsp_installer.on_server_ready(function (server)
    local opts = {}
    if server.name == "ltex" then opts.cmd = { "ltex.bat" } end
    server:setup(opts)
end)
```

**Comment by grimgort** [comment]
it's working thanks a lot !!
