### ISSUE TITLE
Add support for OpenCL language server 

### ISSUE THREAD

**Issue by krishnakumarg1984** [williamboman/nvim-lsp-installer#393]
**Which server would you like to request to be added?**

-   Server name: OpenCL Language Server
-   Server homepage (e.g., GitHub page): https://github.com/Galarius/vscode-opencl

**Which languages does this server target?**

-   Languages: OpenCL, a custom dialect of `C`, that targets kernel development in the parallel programming of heterogeneous systems (GPUs, FPGAs, CPUs, DSPs) 

**How is this server distributed?** 

-   Is the server distributed through a standardized channel (such as release files, npm, pip, etc.)? (leave empty if unknown): VSCode Marketplace, but possible to get a `.vsix` file and install locally.
-   Is this server added in [lspconfig](https://github.com/neovim/nvim-lspconfig)?: No

**Further Comments**

It is vital to add this language server to vim.  There is literally no good extension (either in vimscript or Lua) that provides modern OpenCL editing capabilities. The existing plugins are all outdated syntax highlighting based on old OpenCL standards.  OpenCL is getting popular as a vendor-agnostic way to program heterogeneous systems that includes accelerators like GPUs and FPGAs.

**Comment by williamboman** [comment]
Hello! I will wait for initial response in https://github.com/Galarius/vscode-opencl/issues/34 before proceeding with this

**Comment by williamboman** [comment]
So just FYI: it seems like much of the VSCode extension's features are implemented on the client side entirely, meaning some of it won't be available for other clients. The author made an effort to extract the server from the VSCode extension to its own repository with a separate release pipeline, so this should be good to land soon

**Comment by williamboman** [comment]
Added in #415. Note that you may run into a bunch of errors when saving files. This was fixed in https://github.com/Galarius/opencl-language-server/pull/2 but has not yet made it into a new release.
