### ISSUE TITLE
Styled component support

### ISSUE THREAD

**Issue by kgnugur** [williamboman/nvim-lsp-installer#397]
Hello,
Is it possible to add [Styled plugin](https://github.com/Microsoft/typescript-styled-plugin) support?
Thanks.

**Comment by williamboman** [comment]
Hello! Is this an LSP server? There is a dedicated issue template for requesting new servers!

**Comment by kgnugur** [comment]
My bad, it's not an LSP rather it's a TS Plugin. For reference here is what I did to make it work.

`npm install --save-dev typescript-styled-plugin typescript`

add a plugins section to your tsconfig.json

```
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin"
      }
    ]
  }
}
```

Tsserver should be working probably ofcourse.

Thank you for the great plugin
