### ISSUE TITLE
Issue in ESLint auto-fix when it adds disable rule comment on same line

### ISSUE THREAD

**Issue by zlksnk** [williamboman/nvim-lsp-installer#4]
~~I'm not sure if this is the correct repo to file this issue but for few auto-fixes where ESLint needs to remove a line and insert another, it doesn't removes the line. Also notice a newline after comment isn't added either:~~

When a code action to disable ESLint rule using comment is applied on the same line, it appends original content of the line after the comment.

![tre (0)](https://user-images.githubusercontent.com/26769888/113599696-d0f15300-95f3-11eb-8d1f-84b4e451180d.gif)

![cdcds 398](https://user-images.githubusercontent.com/26769888/113599723-dd75ab80-95f3-11eb-84a0-c485e37f6474.png)

I can confirm that this correctly works in VS Code.

**To reproduce**:
- [Open this CodeSandbox](https://codesandbox.io/s/boring-sea-6hid8?file=/src/App.js:173-175) and download it using File -> Export to ZIP
- Extract the zip and install packages using `npm i` or any Node.js package manager
- Open `App.js` and navigate to line 9 to see a warning and code action

**Comment by williamboman** [comment]
Hey! Hmm I'm not able to repro: https://asciinema.org/a/LPrMxG1NpvgN8o2HoFe52al8W. I'm also not quite following what you mean by adding newlines?

The default behaviour is to apply the disable rule comment on the [same line](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/eslintls.lua#L23).

You can override this by setting the location to  `separateLine`, for example per the [README setup example](https://github.com/williamboman/nvim-lsp-installer#setup):

```lua
if server.name == "eslintls" then
    opts.settings = {
        codeAction = {
            disableRuleComment = {
                location = "separateLine"
            }
        }
    }
end
```

**Comment by lrvpxl** [comment]
Using `seperateLine` solves the issue.

About adding newlines part, yeah I haven't done a good job explaining it. If you look at the pic above, on line 57 when the code action is applied, while it adds ESLint disable rule it also appends original content of the line right after the disable rule which is incorrect behavior. 

That being said it is not reproducible at your side, so it might be that one of my plugin is behaving incorrectly. Let me check and confirm this.

**Comment by williamboman** [comment]
What's your `nvim --version`?

**Comment by lrvpxl** [comment]
NVIM v0.5.0-dev+1160-g0f7b6b2ef

**Comment by lrvpxl** [comment]
I'm using latest version of nvim now, and I've also tried disabling other plugins to check if they are interfering. I'm still facing the same issue.

**Comment by williamboman** [comment]
Hmm ok that's a fresh version.

Here's the workspace edit that the ESLint LSP server sends the client (for same line edit). The values for `character` looks quite interesting.. 

```json
{
  "documentChanges": [
    {
      "textDocument": {
        "uri": "file:///Users/williamboman/Downloads/repro/src/App.js",
        "version": 0
      },
      "edits": [
        {
          "range": {
            "start": {
              "line": 8,
              "character": 2147483647
            },
            "end": {
              "line": 8,
              "character": 2147483647
            }
          },
          "newText": " // eslint-disable-line react-hooks/exhaustive-deps"
        }
      ]
    }
  ]
}
```

**Comment by williamboman** [comment]
And here's for `separateLine`:

```json
{
  "documentChanges": [
    {
      "textDocument": {
        "uri": "file:///Users/williamboman/Downloads/repro/src/App.js",
        "version": 0
      },
      "edits": [
        {
          "range": {
            "start": {
              "line": 8,
              "character": 0
            },
            "end": {
              "line": 8,
              "character": 0
            }
          },
          "newText": "  // eslint-disable-next-line react-hooks/exhaustive-deps\n"
        }
      ]
    }
  ]
}
```

**Comment by williamboman** [comment]
This seems mostly to be a compatibility issue between neovim's LSP client and the ESLint LSP server implementation, but it's weird that it works for me.

I'll change the default value to `separateLine` though

**Comment by lrvpxl** [comment]
That long int is coming correctly [from VSCode ESLint extension](https://github.com/microsoft/vscode-eslint/blob/main/server/src/eslintServer.ts#L1732) and this value is basically 2**31 - 1. Yeah, it could have been that it is interpreted incorrectly either by Vim or by terminal. I'm using WSL but I don't think that WSL is causing problem here.

**Comment by lrvpxl** [comment]
What command do you use to inspect the workspace edit that ESLint LSP server sends?

**Comment by williamboman** [comment]
> What command do you use to inspect/log the workspace edit that ESLint LSP server sends?

I think you can set the nvim lsp client log level to some level and then check the `lsp.log`, but I find it easier and a bit more interactive to debug the LSP server itself, like: https://asciinema.org/a/xBJn9vrscwLRXod1uQMiCKicd
