### ISSUE TITLE
Add remark_ls

### ISSUE THREAD

**Issue by sarmong** [williamboman/nvim-lsp-installer#401]
**Which server would you like to request to be added?**

-   Server name: `remark_ls`
-   Server homepage (e.g., GitHub page): https://github.com/remarkjs/remark-language-server

**Which languages does this server target?**
-   Languages: markdown

**How is this server distributed?**

-   Is the server distributed through a standardized channel: `npm`
-   Is this server added in [lspconfig](https://github.com/neovim/nvim-lspconfig)?: yes ([link](https://github.com/remarkjs/remark-language-server))

**Comment by chancez** [comment]
It also wants `remark` installed, but installing it into the node_modules directory isn't sufficient, and it has to be installed globally. Is there a way to make it so the server can automatically install `remark` in it's own node_modules and use that?
