### ISSUE TITLE
[New server]: metals

### ISSUE THREAD

**Issue by baku1101** [williamboman/nvim-lsp-installer#428]
### Server name

metals

### Server homepage

https://scalameta.org/metals/

### Languages

scala

### Is this server added in lspconfig?

- [X] Yes
- [ ] No

**Comment by williamboman** [comment]
Hello @baku1101! Are you aware of the https://github.com/scalameta/nvim-metals auxiliary plugin? It's a completely standalone plugin for MetaLS (it also provides its own installation mechanism for MetaLS). I'd be happy to add a "barebones MetaLS" installation to nvim-lsp-installer, but these auxiliary LSP plugins provide a much better, tailored, experience and I don't want people to miss out on them. I've had the idea of providing installers for these auxiliary plugins (nvim-jdtls, nvim-metals, rust-tools, etc.), but those ideas are far too undeveloped atm.

**Comment by baku1101** [comment]
I'm using nvim-metals right now and am happy with it. Thanks for the reply!
