### ISSUE TITLE
Bug on pyright version 1.1.100, upgrade to >=1.1.101

### ISSUE THREAD

**Issue by bryangeplant** [williamboman/nvim-lsp-installer#439]
### Problem description

Was fiddling with django and found a bug with the pyright lsp. I found [this issue](https://github.com/microsoft/pyright/issues/1359) that was posted recently. Mind upgrading the pyright version? 

### Neovim version (>= 0.6)

NVIM v0.7.0-dev+665-g4e352ecc4
Build type: RelWithDebInfo
LuaJIT 2.0.5

### Operating system/version

5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

pyright

### Actual behavior

Accessing the static method `objects` from django models yields the linting error "Cannot access member "object" for type "Type[Book]" Member "objects" is undefined" Problem was a regression and has recently been fixed.

### Expected behavior

Not happening

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - OK: **bash**: `GNU bash, version 5.1.12(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.1 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.1`
  - OK: **node**: `v17.2.0`
  - OK: **PHP**: `PHP 8.0.14 (cli) (built: Dec 17 2021 14:16:47) ( NTS )`
  - OK: **Composer**: `Composer version 2.2.1 2021-12-22 22:21:31`
  - OK: **Ruby**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
  - OK: **Go**: `go version go1.17.5 linux/amd64`
  - OK: **sh**: `Ok`
  - OK: **RubyGem**: `3.2.29`
  - OK: **npm**: `8.3.0`
  - OK: **pip3**: `pip 21.3.1 from /home/elysium/.local/share/virtualenvs/ex-django-gaAVZ4d7/lib/python3.10/site-packages/pip (python 3.10)`
```

### Screenshots

![image](https://user-images.githubusercontent.com/97959091/150537451-2caf8b8e-dd29-43dd-bc8d-c891b7785880.png)

**Comment by williamboman** [comment]
Hello @bryangeplant! This plugin will install the latest version of every LSP. Recently there was a feature added that will check for outdated servers when you open the UI window (`:LspInstallInfo`). I'd recommend just updating all the servers (you can easily do this by pressing `U` in the `:LspInstallInfo` window).
