### ISSUE TITLE
Outdated LS for CSS

### ISSUE THREAD

**Issue by JustMikey** [williamboman/nvim-lsp-installer#46]
I believe this plugin relies on [`vscode-css-languageserver-bin`](https://www.npmjs.com/package/vscode-css-languageserver-bin) NPM package, which seems to be outdated and doesn't support some features, such as `@use` statements. 

The official NeoVim LSP GitHub [page](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#cssls)  recommends using another package [`vscode-langservers-extracted`](https://www.npmjs.com/package/vscode-langservers-extracted), which seems to be more up to date.

I wonder if we should consider doing the switch?

**Comment by williamboman** [comment]
Hey! Sure, I think that sounds reasonable. I saw that package also provides HTML and JSON LSP servers - are these also preferred over the standalone packages?

**Comment by williamboman** [comment]
Fixed in #47. Note that you'll have to reinstall either the cssls, jsonls, or html LSP server due to the changes introduced there (the root directory was changed to a new one so that all these servers share the same installation to avoid bloat)
