### ISSUE TITLE
`ccls` cannot execute binary file

### ISSUE THREAD

**Issue by MomePP** [williamboman/nvim-lsp-installer#466]
### Problem description

`ccls` was installed successfully but when lsp start the process, 'Client 1 quit with exit code 126 and signal 0'

I've try to execute binary directly and it failed to execute.
```
exec: Exec format error
The file './ccls' is marked as an executable but could not be run by the operating system.
```

There is no issue while installing the LSP but might be related with build flag.

PS. I've installed `llvm` stable 13.0.1 from Homebrew

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin 21.3.0 Darwin Kernel Version 21.3.0: root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

ccls

### Actual behavior

`ccls` quit with exit code 126 and signal 0

### Expected behavior

`ccls` working normally without exit code

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **python3**: `Python 3.9.10`
  - OK: **node**: `v17.4.0`
  - OK: **Ruby**: `ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]`
  - OK: **sh**: `Ok`
  - OK: **wget**: `GNU Wget 1.21.2 built on darwin21.1.0.`
  - WARNING: **java**: not available
  - WARNING: **javac**: not available
  - OK: **npm**: `8.3.1`
  - OK: **pip3**: `pip 21.3.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **RubyGem**: `3.3.3`
```

### Screenshots

lsp.log
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/13793017/152962655-651b1d6a-0952-4c5f-9de6-1631fc8195b0.png">

:LspInfo
![image](https://user-images.githubusercontent.com/13793017/152963029-2f167fd1-f4b9-4da8-871f-f3a3a3a1afb7.png)

execute `ccls` directly
<img width="732" alt="image" src="https://user-images.githubusercontent.com/13793017/152963392-1abe1eb7-44e3-48c7-9ed6-01a2a4eb1b3c.png">

**Comment by MomePP** [comment]
Seems to be issue from `CMAKE_PREFIX_PATH`. I've changed `llvm_dir` just like the attach screenshot. [ccls build macos](https://github.com/MaskRay/ccls/wiki/Build#macos)

![image](https://user-images.githubusercontent.com/13793017/152975465-d2bde72a-7bda-4de2-8ba2-9f17355af38d.png)

And `ccls` getting back to work as expected after reinstall the LSP.

![image](https://user-images.githubusercontent.com/13793017/152970749-66dcb582-75d3-47e3-846b-9fcfc1d984ab.png)

**Comment by williamboman** [comment]
Hello! Hmm I'm running virtually the same environment but I'm not experiencing any issues. Let's try your suggestion, I see now that the guide suggests appending `/lib/cmake` to the llvm root path

**Comment by williamboman** [comment]
@MomePP Does branch `ccls-macos-prefix-path` fix this?

**Comment by MomePP** [comment]
@williamboman 
Yes, it does. I've completely remove `ccls` and try to switching branch between `llvm` root path.
`ccls-macos-prefix-path` fixed the issue.
