### ISSUE TITLE
texlab: unable to find executable

### ISSUE THREAD

**Issue by aspeddro** [williamboman/nvim-lsp-installer#468]
### Problem description

texlab not find executable. I run :LspIntall texlab

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux arch 5.16.2-arch1-1

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

texlab

### Actual behavior

command to binary not found.

### Expected behavior

The binary should be found as it exists.

```sh
~/.local/share/nvim/lsp_servers/latex 
❯ ls
nvim-lsp-installer-receipt.json  texlab
```

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.2`
  - OK: **node**: `v17.3.0`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **julia**: `julia version 1.7.1`
  - OK: **java**: `Ok`
  - OK: **npm**: `8.3.2`
  - OK: **pip3**: `pip 22.0 from /home/pedro/.local/lib/python3.10/site-packages/pip (python 3.10)`
```

### Screenshots

![image](https://user-images.githubusercontent.com/16160544/153083108-d904dc0b-0c51-482c-9e21-0e0d57ed5dd9.png)

**Comment by williamboman** [comment]
Hey @aspeddro ! How are you setting up the server?

**Comment by aspeddro** [comment]
Closing, was a issue with filetype detection.
