### ISSUE TITLE
Replace ocaml-language-server with ocaml-lsp

### ISSUE THREAD

**Issue by adlrwbr** [williamboman/nvim-lsp-installer#474]
### Problem description

The [OCaml language server NPM package](https://www.npmjs.com/package/ocaml-language-server) is 4 years outdated and has since been relocated to [ocaml/ocaml-lsp](https://github.com/ocaml/ocaml-lsp). Rather than using NPM, I suggest installing the server with the officially supported [OCaml Package Manager (opam)](https://opam.ocaml.org/). The opam-installed binary is named `ocaml-lsp`, which is how I initially discovered this inconsistency. Lastly, I believe `ocaml-lsp` supports development with the Reason language, so the supported languages table should reflect that change.

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

### Operating system/version

Linux laptop 5.12.19-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

ocaml-language-server

### Actual behavior

The OCaml language server is being installed from NPM and is out of date and not maintained.

### Expected behavior

The latest OCaml language server should be installed from official sources.

### Installation log

```shell
NA (the install is successful)
```

### Healthcheck

```shell
NA (the install is successful)
```

**Comment by williamboman** [comment]
Ah :+1:. I believe this is the `ocamllsp` server in lspconfig. I think it'd make sense to deprecate `ocamlls` in favor of `ocamllsp`.

**Comment by harrydt** [comment]
I can take a stab at this
