### ISSUE TITLE
Border for popup window

### ISSUE THREAD

**Issue by aryzing** [williamboman/nvim-lsp-installer#475]
### Is your feature request related to a problem? Please describe.

It's hard to see where the popup window ends and the buffers starts

### Describe the solution you'd like

Borders around the popup window

### Describe potential alternatives you've considered

Sucking it up

### Additional context

n/a

**Comment by williamboman** [comment]
> ### Describe potential alternatives you've considered
> Sucking it up

Ahahahah 😂

The popup window actually uses the builtin highlight groups for the borders, try setting `hi FloatBoarder guifg=red`?

**Comment by aryzing** [comment]
Unsuccesful, did I do something wrong?

https://user-images.githubusercontent.com/4924405/153712458-84de05f9-651c-405a-8e3e-ebd95e28c516.mp4

**Comment by williamboman** [comment]
Ah that's the nvim-lspconfig window. They seem to [hardcode no borders](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/ui/windows.lua#L43-L52) atm. You could probably override this by overriding the method, something like:

```lua
local lspconfig_window = require("lspconfig.ui.windows")

local old_defaults = lspconfig_window.default_opts
function lspconfig_window.default_opts(opts)
    local win_opts = old_defaults(opts)
    win_opts.border = "rounded"
end
```

**Comment by ghillb** [comment]
@williamboman 

> Ah that's the nvim-lspconfig window. They seem to [hardcode no borders](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/ui/windows.lua#L43-L52) atm. You could probably override this by overriding the method, something like:
> 
> ```lua
> local lspconfig_window = require("lspconfig.ui.windows")
> local old_defaults = lspconfig_window.default_opts
> 
> function lspconfig_window.default_opts(opts)
>     local win_opts = old_defaults(opts)
>     win_opts.border = "rounded"
>     return win_opts
> end
> ```

Is there a way to manipulate/drop the borders for the `:LspInstallInfo` popup?

**Comment by williamboman** [comment]
Try

```vim
autocmd FileType lsp-installer lua vim.api.nvim_win_set_config(0, { border = "none" })
```

**Comment by ghillb** [comment]
Thank you, this works perfectly fine!

I have rewritten it for the lua autocmd api, for anyone finding this in the future:

```lua
vim.api.nvim_create_autocmd("FileType", {              
  pattern = "lsp-installer",                           
  callback = function()                                
    vim.api.nvim_win_set_config(0, { border = "none" })
  end,                                                 
})                                                     
```
