### ISSUE TITLE
Expected table got boolean

### ISSUE THREAD

**Issue by anoopd** [williamboman/nvim-lsp-installer#490]
### Problem description

After i installed and configured a few language servers with the help of  nvim-lsp-installer i am getting the error 
`[nvim-lsp-installer] vim/shared.lua:0: after the second argument: expected table, got boolean`

I am not that familiar with lua , so am not sure whether i am doing something wrong in my configs or is it something to do with the plugin itself . 

### Neovim version (>= 0.6)

NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

inux anoops-ubuntu 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

all

### Actual behavior

Error on starting nvim 

### Expected behavior

Nvim should start without any errors 

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.30`
  - OK: **gzip**: `gzip 1.10`
  - OK: **wget**: `GNU Wget 1.20.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.8.10`
  - OK: **node**: `v15.7.0`
  - OK: **PHP**: `PHP 8.0.13 (cli) (built: Nov 22 2021 09:50:43) ( NTS )`
  - OK: **curl**: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
  - OK: **npm**: `7.21.1`
  - OK: **java**: `Ok`
  - OK: **Composer**: `Composer version 1.10.24 2021-12-09 20:06:33`
  - OK: **javac**: `Ok`
  - OK: **pip3**: `pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)`
```

**Comment by williamboman** [comment]
Hey this is most likely due to some error happening inside the function you provide to `lsp_installer.on_server_ready()`. I'd recommend commenting out that function line by line until it (hopefully) stops erroring

**Comment by anoopd** [comment]
Thank you for the response . Will try it and let you know .

**Comment by williamboman** [comment]
That seems fine to me, it also works if I use it in the [`minimal_debug_init.lua`](https://github.com/williamboman/nvim-lsp-installer/blob/main/tests/minimal_debug_init.lua)

**Comment by anoopd** [comment]
Ok then   ..... let me go through it once more . The problem is i am not familiar with lua, but will try to find out  .

**Comment by anoopd** [comment]
Ok so i had it solved . It was because i had a error while calling the settings from another file .
