### ISSUE TITLE
[New server]: zeta-note

### ISSUE THREAD

**Issue by kyoh86** [williamboman/nvim-lsp-installer#494]
### Server name

zeta_note

### Server homepage

https://github.com/artempyanykh/zeta-note

### Languages

markdown

### Is this server added in lspconfig?

- [X] Yes
- [ ] No

### How is this server distributed?

ref: https://github.com/artempyanykh/zeta-note#how-to-install

It is distributed on GitHub release files like below:
- `zeta-note-macos`
- `zeta-note-linux`
- `zeta-note-windows.exe`

Or it can be built from source (rust/cargo)
```shell-session
$ git clone https://github.com/artempyanykh/zeta-note.git
$ cargo install
```

**Comment by williamboman** [comment]
Hey! Isn't this one added already? https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/zeta_note/init.lua

**Comment by kyoh86** [comment]
@williamboman Sorry it's my misunderstading
