### ISSUE TITLE
[lspconfig] Unable to find ESLint library.

### ISSUE THREAD

**Issue by Zw1d** [williamboman/nvim-lsp-installer#495]
### Problem description
After installing eslint via lsp-installer I get this message on startup: `[lspconfig] Unable to find ESLint library.` 
LspInfo reports that the server has attached. LSP features do not work. If I install eslint globally, then everything works fine, so I assume this is an issue of lsp-installer not passing some necessary paths to lspconfig (seems like it looks for eslint in the wrong place?). Other servers that I tested (phpactor, intellephense) work as expected.

### Neovim version (>= 0.6)

```shell
NVIM v0.6.1
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/zw1d/neovim/build/config -I/home/zw1d/neovim/src -I/home/zw1d/neovim/.deps/usr/include -I/usr/include -I/home/zw1d/neovim/build/src/nvim/auto -I/home/zw1d/neovim/build/include
Compiled by zw1d@XXX

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Operating system/version

`Linux XXX 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64 GNU/Linux
`
### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

eslint

### Actual behavior

Message on startup: `[lspconfig] Unable to find ESLint library.` 
LSP features do not work, unless eslint installed globally

### Expected behavior

Lspconfig reports no issues and just works.

### Installation log

```shell
[INFO  Sun 20 Feb 2022 11:20:17 AM CET] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:645: Starting install server_name="eslint", requested_version=""
[INFO  Sun 20 Feb 2022 11:20:26 AM CET] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:664: Installation completed server_name="eslint", success=true
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: Go: not available
  - WARNING: javac: not available
  - WARNING: java: not available
  - WARNING: julia: not available
  - OK: sh: `Ok`
  - OK: bash: `GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)`
  - OK: tar: `tar (GNU tar) 1.30`
  - OK: gzip: `gzip 1.9`
  - OK: wget: `GNU Wget 1.20.1 built on linux-gnu.`
  - OK: python3: `Python 3.7.3`
  - OK: node: `v16.6.0`
  - OK: Ruby: `ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]`
  - OK: curl: `curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3`
  - OK: PHP: `PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )`
  - OK: npm: `8.4.1`
```

### Screenshots

![image](https://user-images.githubusercontent.com/11756864/154837813-b7c164bd-73ec-4a46-a92d-bb9917efa3fa.png)
![image](https://user-images.githubusercontent.com/11756864/154837912-d4eb1ebb-1fe9-4450-96a5-6c2c5979e5e2.png)

**Comment by williamboman** [comment]
Hey! That's how the LSP server is designed - it will look for an ESLint installation in the current workspace, if it can't find one there it'll look for one installed globally. I guess eslint could be vendored in this plugin, but I don't think that's something we should do (you really should be running against the workspace's ESLint version)

**Comment by Zw1d** [comment]
All right, thanks for the info.

**Comment by nyngwang** [comment]
I just encountered the same error as title, and now I realized that I forgot to run `yarn install`. Lol.
