### ISSUE TITLE
Eslint with PNP example no longer seems to work

### ISSUE THREAD

**Issue by NICHTJ3** [williamboman/nvim-lsp-installer#507]
### Problem description

Solution described [here](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/eslint/README.md#eslint-in-projects-that-use-pnp) for using the eslint lsp with pnp does not appear to work since the change to using cmd_env. Is there a way to resolve the cmd with the cmd_env prepended for this usecase?

### Neovim version (>= 0.6)

NVIM v0.7.0-dev+1135-gfdea15723
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin LM-C02DR28LMD6R 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

eslint

### Actual behavior

local install of eslint is not resolved and there is a log from lspconfig stating that they could not find eslint library

### Expected behavior

Local install of eslint would be resolved and lsp would work without global installation of eslint

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **node**: `v14.17.0`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: **Go**: `go version go1.17.2 darwin/amd64`
  - OK: **java**: `Ok`
  - OK: **python3**: `Python 3.9.10`
  - OK: **javac**: `javac 15.0.2`
  - OK: **npm**: `8.1.2`
  - OK: **RubyGem**: `3.0.3.1`
  - OK: **pip3**: `pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
```

### Screenshots

<img width="1117" alt="Screen Shot 2022-02-26 at 12 45 16 AM" src="https://user-images.githubusercontent.com/39316919/155709896-26685743-c072-4d79-87ad-d561053a512e.png">

**Comment by williamboman** [comment]
Btw @NICHTJ3 I've opened a PR in lspconfig to address this: https://github.com/neovim/nvim-lspconfig/pull/1777. I definitely think it'd make sense to support this out of the box, let's see what happens
