### ISSUE TITLE
LspInstallInfo should show server version

### ISSUE THREAD

**Issue by cjnucette** [williamboman/nvim-lsp-installer#510]
### Is your feature request related to a problem? Please describe.

It is cumbersome to find out which version of the server is installed.

### Describe the solution you'd like

Show version alongside the name of the server in the LspInstallInfo window.

**Comment by williamboman** [comment]
Hello! Yes this is definitely something I want to do. It should actually be pretty straight-forward as everything is mostly in place, will look into soon. Just out of curiosity - is there some specific reason why you want/need to do this?

**Comment by williamboman** [comment]
So this wasn't nearly as straight forward to do as I had first thought, but here's a sneak peak:

https://user-images.githubusercontent.com/6705160/156441021-62d049e1-6199-4db1-b286-fafa24726dd7.mov

**Comment by cjnucette** [comment]
I was trying to find out which version of `sumneko_lua` was installed, because of the new formatting feature added to it, and I wanted to test it.
Thank you.

**Comment by williamboman** [comment]
See branch `ui/display-current-version` (#520). Just gotta do some cleaning up now
