### ISSUE TITLE
TailwindCSS autocomplete is not working

### ISSUE THREAD

**Issue by dheerajd5** [williamboman/nvim-lsp-installer#516]
### Problem description

There is no autocomplete suggestions for tailwind classes.

I have just installed nvim and my setup on a new laptop and now the tailwindcss auto complete isn't working. It used to work at my previous pc but now with the same config and steps it doesn't seem to work here.

Looking at looks it seems to find both the tailwind.config.js file and its required modules but the auto complete doesn't seem to be working.

I have installed tailwindcss using lsp-installer.

This is the same config from lsp-installer/tailwindcss.lua.

### LSP log
https://gist.github.com/dheerajd5/9c8d8aede3f74529c0473dea6edd1ffc

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430

### Operating system/version

Windows 11

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

tailwindcss

### Actual behavior

![image](https://user-images.githubusercontent.com/22520440/156308608-f7cd96ca-8606-411f-8c0b-d326a6dc3f9e.png)
This is my project file, and below is the LspInfo, i have installed the node modules too.
At the time of this issue, my neovim and lspconfig are both up to date.
 I have tried reinstalling tailwindcss but the same problem occurs.
![image](https://user-images.githubusercontent.com/22520440/156308641-9df81a75-5e0f-4d21-b722-80d1fc599d1c.png)

### Expected behavior

Auto complete isn't showing.

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - ERROR: **gzip**: not available
  - OK: **python**: `Ok`
  - OK: **node**: `v16.13.2
`
  - OK: **curl**: `curl 7.79.1 (Windows) libcurl/7.79.1 Schannel
`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 17.0.1
`
  - OK: **pip**: `pip 20.2.3 from C:\Python39\lib\site-packages\pip (python 3.9)

`
  - OK: **npm**: `8.1.2`
```

### Screenshots

![image](https://user-images.githubusercontent.com/22520440/156500074-a4661bb4-b8b9-42fb-8c02-1fa71347f422.png)

**Comment by williamboman** [comment]
Hello! I'm not sure how this is a problem with nvim-lsp-installer? Is this reproducable using the [minimal configuration](https://github.com/williamboman/nvim-lsp-installer/blob/main/tests/minimal_debug_init.lua)?

**Comment by dheerajd5** [comment]
Using the minimal config, I'm still not getting any auto complete results, I am relatively new to vim so I don't know if the issue might be lsp-installer or something else. Maybe we should close the issue here and move it to a discussion I think it would be better apt there.

**Comment by williamboman** [comment]
I'm fairly confident this is not an issue with nvim-lsp-installer, but more with your autocompletion config. I'm getting builtin omnicompletion from Tailwind when using the minimal config: https://asciinema.org/a/jKBOmvjiX6z0fkqFOj3Uyc6jI
