### ISSUE TITLE
Version check is not work for csharp_ls and fautocomplete

### ISSUE THREAD

**Issue by chen244** [williamboman/nvim-lsp-installer#532]
### Problem description

The version check is only work for lua and rust, but others not work

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux cht-PC 5.16.13-arch1-1 #1 SMP PREEMPT Tue, 08 Mar 2022 20:07:36 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

csharp_ls fautocomplete

### Steps to reproduce

1. run LspInstallerInfo
2. csharp_ls and fautocomplete always not checked

### Actual behavior

Not check

### Expected behavior

check the new release

### LspInfo

```shell
all is health
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **julia**: `julia version 1.7.2`
  - OK: **python3**: `Python 3.10.2`
  - OK: **node**: `v17.6.0`
  - OK: **Go**: `go version go1.17.8 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **java**: `Ok`
  - OK: **npm**: `8.5.3`
  - OK: **javac**: `javac 17.0.3`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
```

**Comment by williamboman** [comment]
Hello! This is because these servers (csharp_ls, fsautocomplete) are installed via `dotnet tool`. It does not seem like `dotnet` provides any ability to check which version has been installed, I'm happy to be corrected though. The vast majority of servers supported by nvim-lsp-installer will support checking its version
