### ISSUE TITLE
please state more cleearly that setup is nedded, and the order to require the lua config

### ISSUE THREAD

**Issue by DavidePatria** [williamboman/nvim-lsp-installer#537]
### Is your feature request related to a problem? Please describe.

without `nvim-lsp-installer.lua` manually added the servers are not found and do not work.
moreover, even it the file is present but required in `init.lua` after `lsoconfig.lua` , the [suggested configration](https://github.com/neovim/nvim-lspconfig#suggested-configuration) (which is widely used) is overwritten by the later call from `nvim-lsp-installer.lua` to the `server.setup()` function. 
might be a chaotic explanation, let me know if it is not understandable

### Describe the solution you'd like

point out the required steps to get everything working in the readme, specifically in the configuration section

**Comment by williamboman** [comment]
Hello! I'm not sure I'm following you. There's a section for usage [here](https://github.com/williamboman/nvim-lsp-installer#usage). The suggested configuration you linked to is if you use lspconfig only and manage servers outside of neovim.

**Comment by DavidePatria** [comment]
what I'm saying is:
1. some users (me included) use this plugin in conjunction with lsp-config, as can be confirmed by issues that involve both plugins. Given that lsp-config is also the way to lsp in neovim this is quite logical to deduce, I might have a wrong Venn's diagram in my head though.
2. calling the function server.setup(opts) overwrites any function call previously done for the same server, this means that if one followed the [suggested configuration on lsp-config](https://github.com/neovim/nvim-lspconfig#suggested-configuration) and installed this plugins the setup function gets called twice if the configurations are kept separated. This means that by calling the setup function for nvim-lsp-installer AFTER the lspconfig one the setup shortcuts included in the suggested configuration get overwritten. 
3. this behaviour can be mitigated (there's still a strange problem in my case) by requiring the lua file for nvim-lsp-installer BEFORE requiring the lua file for lspconfig, obviously requiring in `init.lua`. 

If you agree that the group of users that use this plugin and lspconfig is big enough then I think it is worth remarking this, otherwise nothing necessitates to be done

**Comment by williamboman** [comment]
> some users (me included) use this plugin in conjunction with lsp-config, as can be confirmed by issues that involve both plugins. Given that lsp-config is also the way to lsp in neovim this is quite logical to deduce, I might have a wrong Venn's diagram in my head though.

Ah, so this plugin requires lspconfig in order to be functional (you can install servers w/o having lspconfig installed, but attempting to set them up would crash).

> calling the function server.setup(opts) overwrites any function call previously done for the same server, this means that if one followed the [suggested configuration on lsp-config](https://github.com/neovim/nvim-lspconfig#suggested-configuration) and then installed this plugins the setup function would get called twice, this if the configurations are kept separated. This means that by calling the setup function for nvim-lsp-installer AFTER the lspconfig one the setup shortcuts included in the suggested configuration get overwritten.

By default the setup function would not be called twice, as you'd have to manually add this to your config. I had forgotten to include a section mentioning this in the README (it was only included in `:h nvim-lsp-installer`), fixed in https://github.com/williamboman/nvim-lsp-installer/commit/01c1285a3d3e67cca0ceea73937b19d1b30a0746.

> this behaviour can be mitigated (there's still a strange problem in my case) by requiring the lua file for nvim-lsp-installer BEFORE requiring the lua file for lspconfig, obviously requiring in init.lua.

Just requiring nvim-lsp-installer won't do anything, as mentioned above you'll also have to add some code that will register a hook (`lsp_installer.on_server_ready()`) to be executed when a server is available and ready to be set up.

> If you agree that the group of users that use this plugin and lspconfig is big enough then I think it is worth remarking this, otherwise nothing necessitates to be done

FWIW, I've been experimenting with a different configuration model that is "less intrusive". In short: the goal is to only make it necessary to install nvim-lsp-installer and it'll immediately manage the PATH for you - there wouldn't be a need to call any nvim-lsp-installer-specific Lua APIs.

**Comment by DavidePatria** [comment]
So if I understand correctly the way to set this up coming from externally manged servers and lspconfig would be to move the setup options to the configuration of this plugins, like setting up nvim-lsp-installer like so

```
local lsp_installer = require("nvim-lsp-installer")

-- suppose that capabilities and on_attach are the functions defined in lspconfig
-- suggested setup and I want to keep them

lsp_installer.on_server_ready(function(server)
  local opts = {
	capabilities = capabilities,
	on_attach = on_attach,
	}

    -- (optional) Customize the options passed to the server
    -- if server.name == "tsserver" then
    --     opts.root_dir = function() ... end
    -- end
    server:setup(opts)
end)
```
and remove remove the inclusion of any lspconfig related configuration.
right?
( by `require` I meant require the configuration file from `init.lua`, not simply putting `require'lspconfig'` somewhere)

**Comment by williamboman** [comment]
Yep exactly! That's the current and probably most straight forward to do it. If you prefer to set them up in a different manner there should be enough Lua APIs in nvim-lsp-installer to do so, but will require some digging and reading docs.

**Comment by DavidePatria** [comment]
having tried this plugins and the manual way to install it I feel like it would be easier to manage if this one simply exported the paths relative servers executables instead of calling the setup function for each one of the them in order to keep all the configuration in `lspconfig.lua` and not have to modify it, but this is a personal preference.
I might look into it, thank you

**Comment by FailFish** [comment]
From [this suggested configuration](https://github.com/neovim/nvim-lspconfig#suggested-configuration),
```lua

local servers = { 'pyright', 'rust_analyzer', 'tsserver' }
for _, lsp in pairs(servers) do
  local ok, server_instace = require('nvim-lsp-installer').get_server(lsp)
  if not ok then
    return
  end

  require('lspconfig')[lsp].setup {
    on_attach = on_attach,
    cmd_env = server_instance:get_default_options().cmd_env, -- newly added
  }
  -- OR,
  server_instance.setup_lsp {
    on_attach = on_attach,
  }
end
```
Both works for me, passing `cmd_env` from nvim-lsp-installer or calling its `setup_lsp` api. In this way, I removed `require("nvim-lsp-installer").on_server_ready(...)` and `lsp-installer.lua` from my config.

**Comment by DavidePatria** [comment]
so, `nvim-lsp-installer` is simply used to to get the path stuff done, this is what I wanted, thank you. 
changing to this configuration would still require modifying a bit `lspconfig.lua`, but I guess it is ok.

**Comment by DavidePatria** [comment]
a quick note: the second method doesn't work for me, the  first one is perfect. thank you

**Comment by FailFish** [comment]
> a quick note: the second method doesn't work for me, the first one is perfect. thank you
`:` should make it work. I edited the code.
