### ISSUE TITLE
Lua server installed but cant be ran

### ISSUE THREAD

**Issue by nagy135** [williamboman/nvim-lsp-installer#538]
### Problem description

I have tsserver and pyright LSPs installed without issue ...but sumneko_lua for some reason installs correctly but then produces
```
Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing f
rom PATH, or not executable.
```
Am I supposed to do some additional configuration? If so why only this one server when both tsserver and pyright worked flawlessly?

### Neovim version (>= 0.6)

:version                                                                                                    
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/xbr9nf3zv3gwd26siz0ssgqf03z8g2sk-neovim-unwrapped-0.6.1/share/nvim"

### Operating system/version

Linux nix 5.10.103 #1-NixOS SMP Wed Mar 2 10:42:57 UTC 2022 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

sumneko-lua

### Steps to reproduce

just run install action from LspInstallInfo and open lua file

### Actual behavior

.

### Expected behavior

.

### LspInfo

```shell
Language client log: /home/infiniter/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: lua
 
 Config: sumneko_lua
 	filetypes:         lua
 	root directory:    /home/infiniter/.dots
 	cmd:               lua-language-server
 	cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: intelephense, tsserver, pyright, sumneko_lua, bashls, yamlls, cssls, gopls, dockerls, nimls, jsonls, rust_analyzer, html, rnix
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.79.1 (x86_64-pc-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 libssh2/1.10.0 nghttp2/1.43.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - WARNING: **pip3**: not available
  - OK: **python3**: `Python 3.9.6`
  - OK: **node**: `v14.18.3`
  - OK: **Ruby**: `ruby 2.7.5p203 (2021-11-24) [x86_64-linux]`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.9.9`
  - OK: **RubyGem**: `3.2.26`
  - OK: **npm**: `6.14.15`
```

**Comment by RazorKitty** [comment]
just came accross this plugin today and was setting it up for lua and hit the same problem, i worked around it by adding the sumneko-lua bin directory to my path then opening a lua file and running `:lua require 'lspconfig'.sumneko_lua.setup{}`
while not ideal that made it work, so my guess is the correct path is not being passed from the installer to the setup?

**Comment by nagy135** [comment]
the error message is saying exactly where the problem is and your workouround works for sure. But if i understand correctly, this plugin should do it internally so there definitelly is a bug imho

**Comment by williamboman** [comment]
Hello! How do you set up your servers? That message in the `:LspInfo` window doesn't necessarily mean that the executable was not found, it can also be the result if the server fails to start for some other reason. Is this reproducible with the [minimal debug](https://github.com/williamboman/nvim-lsp-installer/blob/987b817468fc98b76b255ee4bb4b0104c04765ef/tests/minimal_debug_init.lua) config?

**Comment by nagy135** [comment]
Tried with your minimal config and output is identical. Any other ideas? I mean how would this not happend to everyone if this actually isnt "my setup specific". Just to remove any doubts I fetched your minimal config and ran `nvim -u /path/to/minimal/config /path/to/random/lua/file.lua` ...also tried removing sumneko using `LspInstallInfo` X and fetched it again. Am I really only one having getting this?

Also good to point out that until now I had sumneko installed [from nixos stable repo](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/development/tools/sumneko-lua-language-server/default.nix) and set up using lsp-config without issue.

**Comment by williamboman** [comment]
Ah you use NixOS? I didn't pay attention to it in your first post. I have no experience with NixOS myself, but I know it's not too happy about running non-nixified<sup>(i just made that up)</sup> binaries. Honestly if you use NixOS I feel like you'd probably want to manage this kind of configuration yourself, instead of relying on a 3rd party tool such as nvim-lsp-installer, no? I assume the reason tsserver and pyright work fine is because they just need a `node` runtime (plus `npm` to be installed) in order to run.

**Comment by williamboman** [comment]
> just came accross this plugin today and was setting it up for lua and hit the same problem, i worked around it by adding the sumneko-lua bin directory to my path then opening a lua file and running `:lua require 'lspconfig'.sumneko_lua.setup{}`

@RazorKitty do you have issues if you try the example setup in the [README](/lib64/ld-linux-x86-64.so.2)?

**Comment by nagy135** [comment]
@williamboman I guess I could, but I m not running nixos everywhere and thanks to your plugin i could completely forget about LSPs. Can you please explain to me what does install process do? I thought that all it does is "fetch binary", "unpack it" and "move it somewhere where nvim can execute it". Or is it system-wide install?

I will investigate further later, but lets keep this one open. Maybe if @RazorKitty also uses nixos, renaming the issue would be good idea.

**Comment by williamboman** [comment]
> I thought that all it does is "fetch binary", "unpack it" and "move it somewhere where nvim can execute it". Or is it system-wide install?

Precisely. Many of these binaries will however be dynamically linked, which causes issues with NixOS which does linking a bit differently. I found https://github.com/Mic92/nix-ld which explains it in more details and might eveb provide a compatibility layer

**Comment by RazorKitty** [comment]
@nagy135 im on Void linux, @williamboman ive just run `:PackerUpdate` and setup the example config, and now it works? is the the example setup necessary? i thought the docs implied to me it was optional

**Comment by williamboman** [comment]
> i thought the docs implied to me it was optional

Ah, no you'll have to setup the server somehow!
