### ISSUE TITLE
volar stopped working

### ISSUE THREAD

**Issue by lambda0xff** [williamboman/nvim-lsp-installer#543]
### Problem description

After updating Packer packages, volar stopped working.

### Neovim version (>= 0.6)

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1638296114063.local

### Operating system/version

Darwin lambda0xffs-Mac-mini.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

volar

### Steps to reproduce

1. Start neovim
2. Open a .vue file
3. :LspInstallInfo

### Actual behavior

See attached screenshot

### Expected behavior

Volar should work

### LspInfo

```shell
see screenshot
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **python3**: `Python 3.9.10`
  - OK: **node**: `v16.13.1`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **sh**: `Ok`
  - OK: **wget**: `GNU Wget 1.21.2 built on darwin21.1.0.`
  - WARNING: **java**: not available
  - WARNING: **javac**: not available
  - OK: **npm**: `8.1.2`
  - OK: **pip3**: `pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **RubyGem**: `3.0.3.1`
```

### Screenshots or recordings

![Screenshot 2022-03-14 at 09 06 42](https://user-images.githubusercontent.com/38687176/158132110-3a8bbe64-ecfe-44ec-b409-0ae989f9cb9e.jpg)

**Comment by williamboman** [comment]
Hey! This should be fixed in #534. Make sure you download the latest plugin versions (incl. lspconfig)!
