### ISSUE TITLE
gopls not detecting version, thus not updating

### ISSUE THREAD

**Issue by konradmalik** [williamboman/nvim-lsp-installer#555]
### Problem description

`gopls` works correctly, but is unable to detect it's version and that's the reason (I think) it's not suggesting updates.

### Neovim version (>= 0.6)

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux devarch 5.16.15-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 17 Mar 2022 00:30:11 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

gopls

### Steps to reproduce

Install gopls.

### Actual behavior

'version' is unknown, no new updates are suggested.

Workaround was to remove `gopls` and install it again.

### Expected behavior

gopls version should be detected and it should be automatically updated. This issue will be more and more visible as more and more people move to go 1.18 and gopls is not updated.

### LspInfo

```shell
Language client log: /home/konrad/.cache/nvim/lsp.log
 Detected filetype:   go

 1 client(s) attached to this buffer:

 Client: gopls (id: 1, pid: 18065, bufnr: [1])
    filetypes:       go, gomod, gotmpl
    autostart:       true
    root directory:  /home/konrad/<redacted>
    cmd:             gopls

 Configured servers list: sumneko_lua, pylsp, sqlls, gopls, rust_analyzer
```

### Healthcheck

```shell
1 nvim-lsp-installer: require("nvim-lsp-installer.health").check()
  2 ========================================================================
  3 ## nvim-lsp-installer report
  4   - OK: neovim version >= 0.6.0
  5   - WARNING: Ruby: not available
  6   - WARNING: RubyGem: not available
  7   - WARNING: Composer: not available
  8   - WARNING: PHP: not available
  9   - WARNING: javac: not available
 10   - WARNING: java: not available
 11   - WARNING: julia: not available
 12   - OK: tar: `tar (GNU tar) 1.34`
 13   - OK: gzip: `gzip 1.11`
 14   - OK: curl: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0             nghttp2/1.47.0`
 15   - OK: wget: `GNU Wget 1.21.2 built on linux-gnu.`
 16   - OK: node: `v17.7.2`
 17   - OK: sh: `Ok`
 18   - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
 19   - OK: python3: `Python 3.10.2`
 20   - OK: Go: `go version go1.18 linux/amd64`
 21   - OK: npm: `8.5.5`
 22   - OK: pip3: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
```

### Screenshots or recordings

<img width="815" alt="image" src="https://user-images.githubusercontent.com/13033392/159463191-efaff621-9f30-4c5f-899c-7009ac6b8603.png">

Noticed that today after bumping my repo to go 1.18. Gopls was highlighting `any` as not defined.
After checking the installed binary, it turns out I had version 7.5, while multiple newer versions were released in the meantime.

Workaround was to remove `gopls` and install it again, currently with version 8.1.

**Comment by williamboman** [comment]
Hey! Servers installed via `go` (`go install`) currently don't support providing version information. This is due to a limitation in how go handles installations of binaries, where there seemingly is no way to capture installed versions. I'm not a Go dev so my experience with its tooling is very limited, so I might have missed something. Do you have any ideas on how to capture installed versions as well as checking for new versions?

**Comment by konradmalik** [comment]
hah, good question.
The only 2 similar ways of checking that I know need to fallback to shell:

gopls specific:
```bash
~/.local/share/nvim/lsp_servers/go/gopls version
```
Outputs:
```
golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
```

More general for all binaries from go:
```bash
go version -m ~/.local/share/nvim/lsp_servers/go/gopls  
```
Outputs:
```
/Users/konrad/.local/share/nvim/lsp_servers/go/gopls: go1.17.5
	path	golang.org/x/tools/gopls
	mod	golang.org/x/tools/gopls	v0.7.4	h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
	dep	github.com/BurntSushi/toml	v0.4.1	h1:GaI7EiDXDRfa8VshkTj7Fym7ha+y8/XxIgD2okUIjLw=
	dep	github.com/google/go-cmp	v0.5.6	h1:BKbKCqvP6I+rmFHt06ZmyQtvB8xAkWdhFyr0ZUNZcxQ=
	dep	github.com/sergi/go-diff	v1.1.0	h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
	dep	golang.org/x/mod	v0.5.1	h1:OJxoQ/rynoF0dcCdI7cLPktw/hR2cueqYfjm43oqK38=
	dep	golang.org/x/sync	v0.0.0-20210220032951-036812b2e83c	h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
	dep	golang.org/x/sys	v0.0.0-20211019181941-9d821ace8654	h1:id054HUawV2/6IGm2IV8KZQjqtwAOo2CYlOToYqa0d0=
	dep	golang.org/x/text	v0.3.7	h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
	dep	golang.org/x/tools	v0.1.9-0.20211209172050-90a85b2969be	h1:JRBiPXZpZ1FsceyPRRme0vX394zXC3xlhqu705k9nzM=
	dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
	dep	honnef.co/go/tools	v0.2.1	h1:/EPr//+UMMXwMTkXvCCoaJDq8cpjMO80Ou+L4PDo2mY=
	dep	mvdan.cc/gofumpt	v0.1.1	h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
	dep	mvdan.cc/xurls/v2	v2.3.0	h1:59Olnbt67UKpxF1EwVBopJvkSUBmgtb468E4GVWIZ1I=
```

**Comment by williamboman** [comment]
Great, will look into this! Might end up getting implemented in #536, which I hope to merge in a week or two.

**Comment by williamboman** [comment]
Added in #536! https://asciinema.org/a/edIuP41OOvZjErYMOQ0OsDixc

**Comment by konradmalik** [comment]
Nice! Does it only work on linux though? On my Arch all looks great, but on my MacBook everything is the same as it way ("unable to detect version").

**Comment by williamboman** [comment]
Hm, works fine on my Mac. What's the output of

```
$ go version -m ~/.local/share/nvim/lsp_servers/go/gopls
$ go list -versions -json -m golang.org/x/tools/gopls
```

**Comment by konradmalik** [comment]
That's the same exact output as I pasted above. Those commands I've sent you were executed on my Mac.
Not sure what could be wrong. Plugins are up to date, I'm reusing the same config on mac and linux, interesting.

Healthcheck also seems fine:
```

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.5 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **Go**: `go version go1.18 darwin/amd64`
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **sh**: `Ok`
  - WARNING: **java**: not available
  - WARNING: **javac**: not available
  - OK: **node**: `v17.7.2`
  - OK: **python3**: `Python 3.9.10`
  - OK: **RubyGem**: `3.0.3.1`
  - OK: **npm**: `8.5.2`
  - OK: **pip3**: `pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
```

Repo at `/Users/konrad/.local/share/nvim/site/pack/packer/start/nvim-lsp-installer`:
```
commit 212d17a039da449043b67529c29851db37acc236 (HEAD -> main, origin/main, origin/HEAD)
Author: William Boman <william@redwill.se>
Date:   Sat Mar 26 13:41:50 2022 +0100

    add async managers (#536)
```

However that's my `gopls`:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/13033392/160251773-21041461-40e0-4f90-8cef-16868f93a15b.png">

**Comment by williamboman** [comment]
Ahh you installed the server prior to me adding installation receipts (https://github.com/williamboman/nvim-lsp-installer/pull/379). This receipt is necessary for the plugin to know what's installed at a given location. You'll have to reinstall/update the server for the mechanism to start working.

**Comment by konradmalik** [comment]
Ahh, cool, I thought it'll just work. Reinstalled and all good, thanks!

**Comment by williamboman** [comment]
Cool :). From now on it'll manage to check for new versions (you could try this by `:LspInstall gopls@v0.8.0` and then press `c` while the cursor is on the `gopls` server)
