### ISSUE TITLE
Problem: taplo-lsp outdated, conflicts with taplo v.0.6

### ISSUE THREAD

**Issue by rgnkn** [williamboman/nvim-lsp-installer#562]
### Problem description

I use "neoformat" for formating and use "taplo-cli" with toml-files for this purpose. Everything worked fine, so far.

Now, since the taplo version change from v0.5 to v0.6 there is a curious and serious bug occuring which seems to be related to the  very outdated `taplo-lsp` which is used by `nvim-lsp-installer`.

As soon as I use taplo v0.6 the toml-files get whiped out / cleared if `neoformat` hooks in (with me it's automatically hooked at save).

This does neither seem to be related to `taplo-cli` nor `neoformat` as the cli works correctly if invoked via the terminal and the invocation syntax didn't change either.

### Neovim version (>= 0.6)

NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-3JyIhf/neovim-0.7.0~ubuntu1+git202203291505-ba257d74b-dd05b3569=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-3JyIhf/neovim-0.7.0~ubuntu1+git202203291505-ba257d74b-dd05b3569/build/config -I/build/neovim-3JyIhf/neovim-0.7.0~ubuntu1+git202203291505-ba257d74b-dd05b3569/src -I/build/neovim-3JyIhf/neovim-0.7.0~ubuntu1+git202203291505-ba257d74b-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-3JyIhf/neovim-0.7.0~ubuntu1+git202203291505-ba257d74b-dd05b3569/build/src/nvim/auto -I/build/neovim-3JyIhf/neovim-0.7.0~ubuntu1+git202203291505-ba257d74b-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-114

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux xxx 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

taplo-lsp

### Steps to reproduce

1. Install `neoformat` plugin
2. Get the latest `taplo-cli` (v0.6): `cargo install taplo-cli`
3. Open any `Cargo.toml`
4. Fire `:Neoformat`

### Actual behavior

The `Cargo.toml` gets whiped out / cleared.

### Expected behavior

`Cargo.toml` should be reformatted or stay untouched.

### LspInfo

```shell
omnisharp, lemminx, jdtls, diagnosticls, graphql, yamlls, tsserver, clangd, dockerls, sumneko_lua, gopls, hls, sqlls, taplo, ansiblels, asm_lsp, texlab, jsonls, groovyls, clojure_lsp, html, eslint, remark_ls, julials, cssls, bashls, vimls, pyright, angularls, cmake
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.10`
  - OK: **curl**: `curl 7.80.0 (x86_64-conda-linux-gnu) libcurl/7.80.0 OpenSSL/1.1.1n zlib/1.2.11 libssh2/1.9.0 nghttp2/1.46.0`
  - OK: **wget**: `GNU Wget 1.21 built on linux-gnu.`
  - OK: **python3**: `Python 3.8.13`
  - OK: **node**: `v16.11.1`
  - OK: **Ruby**: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]`
  - OK: **Go**: `go version go1.17 linux/amd64`
  - OK: **julia**: `julia version 1.5.3`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.2.5`
  - OK: **npm**: `8.0.0`
  - OK: **javac**: `javac 18-ea`
  - OK: **pip3**: `pip 22.0.3 from /home/her/bin/.share/anaconda3/lib/python3.8/site-packages/pip (python 3.8)`
```

**Comment by williamboman** [comment]
It does seem like taplo has started embedding the LSP service inside its main CLI tool though, will look into that.

**Comment by rgnkn** [comment]
> It does seem like taplo has started embedding the LSP service inside its main CLI tool though, will look into that.

FYI and if you're using this: 

The formatting bug has been fixed. `cargo install --force --git https://github.com/tamasfe/taplo taplo-cli`
