### ISSUE TITLE
Dockerls. Unable to find executable. Please check your path and ensure the server is installed

### ISSUE THREAD

**Issue by ghillb** [williamboman/nvim-lsp-installer#567]
### Problem description

After installing  dockerls via nvim-lsp-installer dockerls, lsp client is not working in Dockerfile buffers and is exiting with:
`Client 3 quit with exit code 1 and signal 0`.

### Neovim version (>= 0.6)

NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-3zMtsI/neovim-0.7.0~ubuntu1+git202203311505-ea8ad7999-dd05b3569=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-3zMtsI/neovim-0.7.0~ubuntu1+git202203311505-ea8ad7999-dd05b3569/build/config -I/build/neovim-3zMtsI/neovim-0.7.0~ubuntu1+git202203311505-ea8ad7999-dd05b3569/src -I/build/neovim-3zMtsI/neovim-0.7.0~ubuntu1+git202203311505-ea8ad7999-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-3zMtsI/neovim-0.7.0~ubuntu1+git202203311505-ea8ad7999-dd05b3569/build/src/nvim/auto -I/build/neovim-3zMtsI/neovim-0.7.0~ubuntu1+git202203311505-ea8ad7999-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-102

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux vx 5.15.0-23-generic #23-Ubuntu SMP Fri Mar 11 14:54:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

dockerls

### Steps to reproduce
1. Open nvim & :PackerSync & :PackerCompile
2. Install `dockerls` via lsp installer
3. Open dockerfile and get error
```
local fn = vim.fn

-- bootstrap packer
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({ "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path })
  vim.cmd("packadd packer.nvim")
end

-- auto compile
vim.api.nvim_create_autocmd("BufWritePost", { pattern = "plugins.lua", command = "source <afile> | PackerCompile" })

return require("packer").startup({
  function(use)
    use({
      "williamboman/nvim-lsp-installer",
      config = function()
        local ok, nvim_lsp_installer = pcall(require, "nvim-lsp-installer")
        if not ok then
          return
        end

        nvim_lsp_installer.settings({
          ui = {
            icons = {
              server_installed = "✓",
              server_pending = "➜",
              server_uninstalled = "✗",
            },
          },
        })

        nvim_lsp_installer.on_server_ready(function(server)
          local opts = {}

          server:setup(opts)
        end)
      end,
    })
  end,
  config = {
    display = {
      open_fn = function()
        return require("packer.util").float({ border = "single" })
      end,
    },
  },
})
```

### Actual behavior

Lsp client quits with exit code 1 and signal 0

### Expected behavior

Client attaches to buffer and provides lsp features

### LspInfo

```shell
Language client log: /home/gh/.cache/nvim/lsp.log                                                               
Detected filetype:   dockerfile                                                                                 
                                                                                                                
0 client(s) attached to this buffer:                                                                            
                                                                                                                
Other clients that match the filetype: dockerfile                                                               
                                                                                                                
Config: dockerls                                                                                                
 filetypes:         dockerfile                                                                                  
 root directory:    NA                                                                                          
 cmd:               docker-langserver --stdio                                                                   
 cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: Ruby: not available
  - WARNING: RubyGem: not available
  - WARNING: Composer: not available
  - WARNING: PHP: not available
  - WARNING: julia: not available
  - OK: sh: `Ok`
  - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: tar: `tar (GNU tar) 1.34`
  - OK: gzip: `gzip 1.10`
  - OK: curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+        libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11`
  - OK: wget: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: python3: `Python 3.10.3`
  - WARNING: node: unsupported version `v12.22.9`. Node version must be >= 14
  - OK: Go: `go version go1.18 linux/amd64`
  - OK: java: `Ok`
  - OK: javac: `javac 11.0.14`
  - OK: pip3: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
  - OK: npm: `8.5.1`
```

**Comment by williamboman** [comment]
Hello! What does the LSP client logs say? `:exe 'tabnew ' .. luaeval("vim.lsp.get_log_path()")`

**Comment by ghillb** [comment]
`
[ERROR][2022-04-02 12:17:15] .../vim/lsp/rpc.lua:420  "rpc" "docker-langserver" "stderr"  "/home/gh/.local/share/nvim/lsp_servers/dockerfile/  node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;       \n                          ^\n\nSyntaxError: Unexpected token '.'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module.    _compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require      (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/gh/.local/   share/nvim/lsp_servers/dockerfile/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at  Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n"
`

**Comment by williamboman** [comment]
Ah, outdated Node version. I just saw in the checkhealth output that there is a warning for this already:

```
- WARNING: node: unsupported version `v12.22.9`. Node version must be >= 14
```

**Comment by ghillb** [comment]
I'm surprised that the node version is that old in 22.04 ubuntu repos. I will try to get a newer version from somewhere else and report back.

**Comment by williamboman** [comment]
Yeah, Node 12 reaches end-of-life at the end of April. https://github.com/nvm-sh/nvm is pretty nice and easy to set up, imo.

**Comment by williamboman** [comment]
Btw, I made version mismatch [report error](https://github.com/williamboman/nvim-lsp-installer/commit/1c5b858a74f488024a76c79a658014fcf2e623ae) in checkhealth, to make it a bit more noticeable

**Comment by ghillb** [comment]
That nvm tip was excellent. The snap version of node isn't functional for 22.04 and the official distribution of nodejs.org not ready yet.
With node 14.x its working now. Thanks!
