### ISSUE TITLE
R language server installer did not work on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [williamboman/nvim-lsp-installer#568]
```
    ◍ r_language_server (failed)
        
        R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
        Copyright (C) 2021 The R Foundation for Statistical Computing
        Platform: x86_64-w64-mingw32/x64 (64-bit)
        
        R is free software and comes with ABSOLUTELY NO WARRANTY.
        You are welcome to redistribute it under certain conditions.
        Type 'license()' or 'licence()' for distribution details.
        
          Natural language support but running in an English locale
        
        R is a collaborative project with many contributors.
        Type 'contributors()' for more information and
        'citation()' on how to cite R or R packages in publications.
        
        Type 'demo()' for some demos, 'help()' for on-line help, or
        'help.start()' for an HTML browser interface to help.
        Type 'q()' to quit R.
        
        > options(langserver_library = C:\\Users\\hongy\\AppData\\Local\\nvim-data\\lsp_servers\\r_language_server.tmp);
        Error: unexpected '\\' in "options(langserver_library = C:\\"
        Execution halted
        ...art\nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:222: Installation failed.
```

This is because the path was not quoted:

https://github.com/williamboman/nvim-lsp-installer/blob/8e03401ad37a6f95e2097ea6139308e24270662d/lua/nvim-lsp-installer/servers/r_language_server/init.lua#L8
https://github.com/williamboman/nvim-lsp-installer/blob/8e03401ad37a6f95e2097ea6139308e24270662d/lua/nvim-lsp-installer/servers/r_language_server/init.lua#L23

Surround `%q` with quotes will do:
```
 options(langserver_library = "%q"); 
```

**Comment by williamboman** [comment]
Hey! Ah interesting, it almost seems like R tries to interpret the backslash sequences as escape characters? I wonder if using a raw string would work?

```r
options(langserver_library = r"(%s)");
```

**Comment by hongyuanjia** [comment]
Yes, you are right. Backslash in strings in R is used to escape characters. The raw string approach is not a portable solution, since raw string was only introduced after R 4.0.
I am not familiar with `%q`. Does it add quotes? If not, I believe quote the path to make it a string is the way to go.

**Comment by williamboman** [comment]
> I am not familiar with `%q`. Does it add quotes?

The string is passed as the template string to Lua's `string.format()`, which I believe uses the same standards as C's string formatting mechanism (`printf`). And yes, it adds quotes:

```lua
> string.format("str_assignment = %q", "my value")
< "str_assigment = \"my value\""
```

**Comment by hongyuanjia** [comment]
Interesting. Then I have no idea why it seems that there were no quotes in the error messages. What further information shall I provide you to help thr debugging?

**Comment by williamboman** [comment]
So I think I've fixed it in #578 (branch `fix/rlang-windows`). Was a bit tedious to install rtools and R4.2 on my Windows machine, but I managed to resolve it 😅. The same issue might however remain when running the server - but at least installation should hopefully succeed now? Could you give it a try 🙏?

**Comment by hongyuanjia** [comment]
Thanks! Will give it a try now.

**Comment by hongyuanjia** [comment]
Unfortunately I still encountered an error as below:

```
  Pending servers (1) 
    ◍ r_language_server (failed)
        ...art\nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:222: ...ua/nvim-lsp-installer/servers/r_language_server/init.lua:37: attempt to index field 'spawn' (a nil value)
```

**Comment by williamboman** [comment]
Hmmmm that's really weird. Does installing `bashls` work? <sup>(there's nothing special with bashls itself, it's just another [async installer](https://github.com/williamboman/nvim-lsp-installer/commit/999476c324b26223aaf409a84497215e18d74499))</sup>

**Comment by hongyuanjia** [comment]
Nope. Similar error occured:

```
    ◍ bashls (failed)
        ...art\nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:222: ...taller/lua/nvim-lsp-installer/core/managers/npm/init.lua:36: attempt to index field 'fs' (a nil value)
```

**Comment by williamboman** [comment]
What's your `:checkhealth nvim-lsp-installer` output? Also, which operating system are you running (I'm assuming some version of Windows)?

**Comment by hongyuanjia** [comment]
Here is the output for `:checkhealth nvim-lsp-installer`:

```
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **node**: `v17.7.1
`
  - OK: **python**: `Ok`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.32`
  - OK: **curl**: `curl 7.64.1 (x86_64-pc-msys) libcurl/7.64.1 OpenSSL/1.1.1g zlib/1.2.11`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 11.0.12
`
  - OK: **pip**: `pip 21.2.4 from C:\Python310\lib\site-packages\pip (python 3.10)

`
  - OK: **npm**: `8.5.2`
```

I am using Windows 10 21H2 (19044.1586).

**Comment by williamboman** [comment]
Hmmm, that looks fine.. Did you restart your neovim instance after changing the plugin version?

**Comment by hongyuanjia** [comment]
Ha! I did not restart neovim after changing the plugin to the new branch (`fix/rlang-windows`). After restarting neovim, I can install the R language server without issue. The language server seems to work fine. Thanks!
