### ISSUE TITLE
Always install latest Haskell LSP

### ISSUE THREAD

**Issue by mystilleef** [williamboman/nvim-lsp-installer#58]
The latest version of `hls` is `1.3.0`. This installer downloads `1.2.0`. 

I'm not sure hard-coding the language server versions is a good idea, especially for Haskell projects. 

If resolvers, compilers, and language server versions don't match in some Haskell projects, especially those that use Stack, then the language server will not work. 

It'd be nice if `LspInstall hls` installs the latest language server. I assume most user will be updating their language server after updating their project resolver.

**Comment by mystilleef** [comment]
I opened PR #59 for this issue.

**Comment by williamboman** [comment]
Thanks for the description! Yeah whenever I've had the choice I've opted towards hard-coding the version rather than using the latest release as there's nothing in place to guarantee the install steps will succeed with newer versions (some tests would be a good start 😄 ). Let's merge #59, I'd also be happy to accept a PR that changes the install script for `hls` to use the latest version if you think that makes more sense!

**Comment by augustocdias** [comment]
I think this issue happens with `rust_analyzer` as well. They release new versions weekly and the version pointed there is quite old.

**Comment by williamboman** [comment]
I went ahead and implemented this for all servers: https://github.com/williamboman/nvim-lsp-installer/pull/106. Please give it a try and let me know if it works well!

**Comment by williamboman** [comment]
@augustocdias `:LspInstall rust_analyzer` now always installs the latest version. Since rust-analyzer also tags `nightly` releases, you can also do `:LspInstall rust_analyzer@nightly` for extra spicyness

**Comment by augustocdias** [comment]
Awesome. Great work.

**Comment by abalmos** [comment]
Just wanted to say thanks, this solves problems for me too.

**Comment by williamboman** [comment]
![DDAA8687-3B77-4311-B0F3-696528BCD33C](https://user-images.githubusercontent.com/6705160/135290868-560ad71a-fced-41b7-b28c-97b0b6076f00.gif)
