### ISSUE TITLE
[New server]: MQL4

### ISSUE THREAD

**Issue by eqan** [williamboman/nvim-lsp-installer#584]
### Server name

MQL4 Language Server Not Available

### Server homepage

https://github.com/pnetherwood/mql4-dev

### Languages

MQL4

### Is this server added in lspconfig?

- [ ] Yes
- [X] No

**Comment by williamboman** [comment]
Hey! The link you provided doesn't seem to be a language server? I did a quick Google search and I was unable to find a LSP implementation for MQL4

**Comment by eqan** [comment]
Got it I hope someone in the community knows about this issue, also I have the supposed syntax highlighting for MQL4 for vim here
https://github.com/vobornik/vim-mql4
I can't confirm if it works or not haven't tested it but still do let me know if anybody finds any helpful material related to the integration of MQL4 in the LSP server.

**Comment by williamboman** [comment]
Writing an LSP server is no small feat, so I'd not bet on it happening out of the blue. Anyways, I'll close this issue here seeing as there currently are no available servers!
