### ISSUE TITLE
Prettier support needed

### ISSUE THREAD

**Issue by lixiao189** [williamboman/nvim-lsp-installer#595]
### Is your feature request related to a problem? Please describe.

I need to use prettier to format my front end code 

### Describe the solution you'd like

I need to install prettier automatically

**Comment by williamboman** [comment]
Hello! Prettier does not have an LSP server. I have however continuously been doing some work towards enabling installing more things than just LSP servers, refer to https://github.com/williamboman/nvim-lsp-installer/issues/95 for updates on that!

**Comment by lixiao189** [comment]
Wow, thank you !
