### ISSUE TITLE
clangd LSP possibilities doesn't show signatures

### ISSUE THREAD

**Issue by BooleanCube** [williamboman/nvim-lsp-installer#603]
### Problem description

Hey there!

I installed all my LSPs through this lsp installer but, I am having some small issues with it. jdtls (java) works just fine. <br>
![image](https://user-images.githubusercontent.com/47650058/163705231-017c28a3-bb06-445e-bb28-c5cc5a4e9ea8.png)

but the problem is with clangd. i get the possibilities but everytime i hover over one i dont get any details or signatures it just says "overloads"
![image](https://user-images.githubusercontent.com/47650058/163705267-6fd4d892-87bf-4489-94f8-0d3b5d4d1d58.png)

What is the fix for this problem? There's also this really annoying bug with clangd where as im typing code it doesnt show lsp possibilities but when i hit backspace it suddenly shows all the lsp possibilities. so i have to type the whole method out and then backspace a character to use the lsp possibility. <br>
Before:
![image](https://user-images.githubusercontent.com/47650058/163705332-57cc85e0-04df-4a50-a33e-3c60167201c8.png)

After:
![image](https://user-images.githubusercontent.com/47650058/163705342-6e308e1d-0fdc-413f-9083-e2dd86da6ab5.png)

### Neovim version (>= 0.6)

NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 20.04

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

clangd

### Steps to reproduce

1. open neovim
2. write c++ code

### Actual behavior

It doesn't show method and class signature and details it just shows some nonsense.

### Expected behavior

It should show the details and signatures for each lsp possibility.

### LspInfo

```shell
Language client log: /home/boole/snap/alacritty/common/.cache/nvim/lsp.log
 Detected filetype:   alpha
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: html, ltex, sumneko_lua, clangd, zk, cssls, sqlls, pyright, jdtls
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.30`
  - OK: **gzip**: `gzip 1.10`
  - OK: **curl**: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
  - OK: **wget**: `GNU Wget 1.20.3 built on linux-gnu.`
  - OK: **java**: `Ok`
  - WARNING: **pip3**: not available
  - OK: **python3**: `Python 3.8.10`
  - OK: **node**: `v16.14.2`
  - OK: **javac**: `javac 17.0.2`
  - OK: **npm**: `8.5.0`
```

**Comment by williamboman** [comment]
Hello! Hmm I'm not sure how this is an issue with the installer? This seems more like an issue with either the completion plugin you're using or with the clangd LSP itself?

**Comment by BooleanCube** [comment]
im assuming the problem lies within the configuration of the lsp when it was installed. since i get it for jdtls servers with the same completion plugin, shouldnt i also be able to get it with clangd servers. is there more configuring i need to do for clangd to be able to get the method signatures from the lsp possibilities?

**Comment by williamboman** [comment]
What is available for completion is entirely delegated to the LSP server implementation itself. Just because server A does something won't mean server B does the same, unfortunately. The only thing they have in common is that the client <-> server communication is the same.

I believe the autocompletion problem is an issue with the completion mechanism/plugin that you're using, and the `[8 overloads]` completion popup is provided by the clangd server!
