### ISSUE TITLE
R language server only works with libraries installed along with the `languageserver` package

### ISSUE THREAD

**Issue by hongyuanjia** [williamboman/nvim-lsp-installer#609]
### Problem description

Currently, the R language server is installed into an isolated library location using the [`languageserversetup` R package](https://github.com/jozefhajnala/languageserversetup). This approach works seamlessly for the server installation.

However, the server is configured to run with `.libPaths(new = rlslib)`, where `rlslib` is the temporary library location used to install the server:

https://github.com/williamboman/nvim-lsp-installer/blob/90996e5c52c3f025a4a8987a3e1fefcfe142cfac/lua/nvim-lsp-installer/servers/r_language_server/init.lua#L37-L43

According to the [documentation](https://stat.ethz.ch/R-manual/R-devel/library/base/html/libPaths.html) of `.libPaths()`, `.libPaths(new = rlslib)` will not prepend the library paths, but set the library paths to `unique(c(new, .Library.site, .Library))`, i.e. the path of user's R library will be removed. That's why `nvim-cmp` only pops up namespace completion for R libraries installed at `rlslib` but not libraries for all libraries installed in R's default user library path. The fixes should be quite straightforward, just changing it to `.libPaths(c(rlslib, .libPaths))`:

```r
# original library paths
.libPaths()
#> [1] "C:/Users/hongy/R/win-library/4.1"
#> [2] "C:/Program Files/R/R-4.1.0/library"

# current approach
options("langserver_library" = "C:\\Users\\hongy\\AppData\\Local\\nvim-data\\lsp_servers\\r_language_server")
rlsLib <- getOption("langserver_library")
.libPaths(new = rlsLib)
.libPaths()
#> [1] "C:/Users/hongy/AppData/Local/nvim-data/lsp_servers/r_language_server"
#> [2] "C:/Program Files/R/R-4.1.0/library"     

# proposed approach
rlsLib <- getOption("langserver_library")
.libPaths(c(rlsLib, .libPaths()))
.libPaths()
#> [1] "C:/Users/hongy/AppData/Local/nvim-data/lsp_servers/r_language_server"
#> [2] "C:/Users/hongy/R/win-library/4.1"                                    
#> [3] "C:/Program Files/R/R-4.1.0/library"  
```

### Neovim version (>= 0.6)

NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113

### Operating system/version

Windows 10 21H2

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

r_language_server

### Steps to reproduce

Pls see above.

### Actual behavior

The user library paths have been removed and only the server installation path and R site library path are kept.

### Expected behavior

The user library paths should be kept.

### LspInfo

```shell
Language client log: C:\Users\hongy\AppData\Local\Temp\nvim\lsp.log
 Detected filetype:   r
 
 1 client(s) attached to this buffer: 
 
 Client: r_language_server (id: 1, pid: 21004, bufnr: [83, 10, 40])
 	filetypes:       r, rmd
 	autostart:       true
 	root directory:  C:/Users/hongy/Dropbox/proj
 	cmd:             R --slave -f C:\Users\hongy\AppData\Local\nvim-data\lsp_servers\r_language_server\server.R
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **node**: `v17.7.1`
  - OK: **python**: `Ok`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.32`
  - OK: **curl**: `curl 7.64.1 (x86_64-pc-msys) libcurl/7.64.1 OpenSSL/1.1.1g zlib/1.2.11`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 11.0.12`
  - OK: **pip**: `pip 21.2.4 from C:\Python310\lib\site-packages\pip (python 3.10)`
  - OK: **npm**: `8.5.2`
```

**Comment by williamboman** [comment]
Ah, thanks for the suggestions, I know very little about R! Happy to receive a PR to fix this, otherwise I'll look into it asap!

**Comment by hongyuanjia** [comment]
Sure. I will send a PR shortly. Cheers!

**Comment by hongyuanjia** [comment]
PR sent. See #611
