### ISSUE TITLE
Can't remove eslintls

### ISSUE THREAD

**Issue by mystilleef** [williamboman/nvim-lsp-installer#61]
It looks like `eslintls` is installed by default. `LspUninstall eslintls` doesn't remove it. I already use `eslint` with `null-ls`. So I don't need it installed at all.

**Comment by mystilleef** [comment]
`denols` that was the culprit. However, `eslintls` still seems to be magically installed for some reason.

**Comment by williamboman** [comment]
Are you sure it's actually considered installed (`server:is_installed()` or `:LspPrintInstalled`)? What I believe is happening is that once `eslintls` is added into lspconfig [here](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/eslintls/init.lua#L9-L47), it's registered as a server with lspconfig and will show up in certain places, such as `:LspInfo`. I don't believe it should interfere with anything though, other than being a nuisance?

Actually we already do some stuff to avoid this very same issue by [deferring interactions with `lspconfig`](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/server.lua#L45-L53), we should be able to do something similar for eslint.

**Comment by williamboman** [comment]
@mystilleef Could you see if the branch `defer-eslint-server-definition` (https://github.com/williamboman/nvim-lsp-installer/pull/62) fixes it? Seems like it does the trick for me, but I'm not sure we're talking about the same thing yet :D

**Comment by mystilleef** [comment]
> @mystilleef Could you see if the branch `defer-eslint-server-definition` (#62) fixes it? Seems like it does the trick for me, but I'm not sure we're talking about the same thing yet :D

Yeap, that fixes it.
