### ISSUE TITLE
High memory usage when a single file is opened

### ISSUE THREAD

**Issue by s1n7ax** [williamboman/nvim-lsp-installer#612]
### Problem description

When I create a `.lua` file in `HOME` directory and open it from `neovim`, within 5-10 minutes language server start to use so much memory. Note that it does not happen when I open `~/.config/nvim` which has a proper lua project structure.

### Neovim version (>= 0.6)

NVIM v0.7.1-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by s1n7ax

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux s1n7ax 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

sumneko_lua

### Steps to reproduce

1. `cd` to home directory
2. create and open a new lua file `nvim test.lua`
3. run `htop` and let `nvim` process running for few minutes

### Actual behavior

Runs out of memory and entire system will stuck

### Expected behavior

Not to take so much memory.

### LspInfo

```shell
Language client log: /home/s1n7ax/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [1])
 	filetypes:       css, markdown, scss, html, less, graphql, handlebars, yaml, typescript, json, vue, javascriptreact, javascript, jsonc, typescriptreact, lua, python
 	autostart:       false
 	root directory:  /home/s1n7ax
 	cmd:             nvim
 
 Client: sumneko_lua (id: 2, pid: 20908, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/s1n7ax
 	cmd:             lua-language-server
 
 Configured servers list: graphql, bashls, html, cssls, dockerls, eslint, jsonls, jdtls, sumneko_lua, pyright, rust_analyzer, tsserver, volar, groovyls, clangd
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v17.9.0`
  - OK: **cargo**: `cargo 1.59.0 (49d8809dc 2022-02-10)`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 11.0.15`
  - OK: **npm**: `8.5.5`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
```

### Screenshots or recordings

![Screenshot_20220419_161121](https://user-images.githubusercontent.com/18459807/163988456-a523fe46-eb1c-4b8b-878f-e6d41f721bf8.png)

**Comment by williamboman** [comment]
Hello! I'm not sure how this is an issue with nvim-lsp-installer 🤔? I imagine it's using a lot of resources because it's indexing the workspace directory (being your entire $HOME). If you want to open lua files within your $HOME directory you probably want to open them in single file mode (`:h lspconfig-single-file-support`). I personally don't have any of the root markers (`.git, '.luarc.json', '.luacheckrc', '.stylua.toml', 'selene.toml'`) in my $HOME, so the server starts in single file mode automatically.
