### ISSUE TITLE
attempt to call method 'setup_ls p' (a nil value)

### ISSUE THREAD

**Issue by brokenbyte** [williamboman/nvim-lsp-installer#614]
### Problem description

After installing any language server, and immediately upon startup with any language servers installed, I get the error message `...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:74: attempt to call method 'setup_lsp' (a nil value)`

### Neovim version (>= 0.6)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux archlinux 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

all

### Actual behavior

Unable to install/use any servers

### Expected behavior

Be able to install/use any servers

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **java**: `Ok`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v17.9.0`
  - OK: **Ruby**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **cargo**: `cargo 1.60.0 (d1fd9fe 2022-03-01)`
  - OK: **RubyGem**: `3.3.8`
  - OK: **javac**: `Ok`
  - OK: **npm**: `8.5.5`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
```

**Comment by williamboman** [comment]
Hello! If I had to guess, you're using a `.` instead of a `:` to access the `setup()` method. Try:

```diff
- server.setup(opts)
+ server:setup(opts)
```

More info: https://stackoverflow.com/questions/4911186/difference-between-and-in-lua

**Comment by brokenbyte** [comment]
Whelp that looks like it did it. I didn't realize there was a difference between the two. Thanks for the link!
