### ISSUE TITLE
bashls: installation incomplete

### ISSUE THREAD

**Issue by happy42779** [williamboman/nvim-lsp-installer#622]
Hi, this is my first time trying to interact with people here on github, trying to solve problems or questions I have. Therefore, please bear with me if I'm not following the standard procedure or the due courtesy.

## Problem:
After Installing bashls with nvim-lsp-installer, the installation succeeded, yet when I edit a .sh file, an error message would popup: bash-language-server not found. I tried looking for it under ~/.local/share/nvim/lsp_servers/bash/, but didn't find the executable named bash-language-server

## Solution:
As I used to install bashls manually, so I tried checked carefully and found out the bash-language-server is actually a soft link to node_module/bin/main.js. I solved the problem by manually creating a soft link.

## Question:
I'm not sure if I missed some important information that lies somewhere that describes this. Is there a better and elegant way to make this work? 

Thanks!

**Comment by williamboman** [comment]
Hello! I think this was a very well structured first issue :). 

How do you set up your servers currently? Did you see the [Setup section in the README](https://github.com/williamboman/nvim-lsp-installer#setup)?

As for where the executable is located; since the bash language server is distributed as an npm package, the executable can be found in `~/.local/share/nvim/lsp_servers/bash/node_modules/.bin`. nvim-lsp-installer will add this path to your `PATH` when you set the server up via nvim-lsp-installer (i.e. this does not happen if you call lspconfig directly like `lspconfig.bashls.setup {}`).

**Comment by happy42779** [comment]
> Hello! I think this was a very well structured first issue :).
> 
> How do you set up your servers currently? Did you see the [Setup section in the README](https://github.com/williamboman/nvim-lsp-installer#setup)?
> 
> As for where the executable is located; since the bash language server is distributed as an npm package, the executable can be found in `~/.local/share/nvim/lsp_servers/bash/node_modules/.bin`. nvim-lsp-installer will add this path to your `PATH` when you set the server up via nvim-lsp-installer (i.e. this does not happen if you call lspconfig directly like `lspconfig.bashls.setup {}`).

Hello! Thanks for your affirmation and reply!
Thanks for pointing out the problem and now I understand how it works! However, I'm new to neovim and lua, I followed the traditional lspconfig to setup specific languag servers, I am kind of lost on how to actually use nvim-lsp-installer. I know it's shouldn't be hard, but you know sometimes you can see things comprehensively and thus you're lost even though you are pretty close to where you want to go. I will read the manual more thoroughly and try again. Do you have any suggestions on how to work this out ?

Thanks again.

**Comment by williamboman** [comment]
Hey @happy42779! Try downloading the latest plugin version of nvim-lsp-installer, and then add this one line to your configuration (_make sure to add it before you set up any servers via lspconfig!_):

```lua
require("nvim-lsp-installer").setup {}
```

**Comment by jesse-osiecki** [comment]
hey to chime in here, I have the `require("nvim-lsp-installer").setup {}` function run in my vim config and have the same issue. I have `~/.local/share/nvim/lsp_servers/bash/node_modules/.bin/bash-language-server`.
:LspInfo shows me `Unable to find executable. Please check your path and ensure the server is installed`
happy to post some more debugging information
