### ISSUE TITLE
hls-1.7.0.0 installer returns 404

### ISSUE THREAD

**Issue by ThoNohT** [williamboman/nvim-lsp-installer#634]
### Problem description

Trying to install the hls language server fails with the following error:

`[ERROR Wed 27 Apr 2022 03:33:27 PM CEST] ...installer/lua/nvim-lsp-installer/core/installer/init.lua:79: Installation failed, name="hls", error='...taller/lua/nvim-lsp-installer/core/managers/std/init.lua:61: Failed to download file "https://github.com/haskell/haskell-language-server/releases/download/1.7.0.0/haskell-language-server-Linux-1.7.0.0.tar.gz".\nspawn: curl failed with exit code 22. curl: (22) The requested URL returned error: 404 \n'`

And indeed, https://github.com/haskell/haskell-language-server/releases/download/1.7.0.0/haskell-language-server-Linux-1.7.0.0.tar.gz does result in a 404.

It looks like from 1.7.0.0, the binaries are placed in a different place. https://github.com/haskell/haskell-language-server/releases/ has a link to https://downloads.haskell.org/~hls/haskell-language-server-1.7.0.0/ which lists different binaries for this language server.  It also notes "Subsequent releases will also be available at https://downloads.haskell.org/~hls"

### Neovim version (>= 0.6)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

### Operating system/version

5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

hls

### Actual behavior

I get the error:
`[ERROR Wed 27 Apr 2022 03:33:27 PM CEST] ...installer/lua/nvim-lsp-installer/core/installer/init.lua:79: Installation failed, name="hls", error='...taller/lua/nvim-lsp-installer/core/managers/std/init.lua:61: Failed to download file "https://github.com/haskell/haskell-language-server/releases/download/1.7.0.0/haskell-language-server-Linux-1.7.0.0.tar.gz".\nspawn: curl failed with exit code 22. curl: (22) The requested URL returned error: 404 \n'`

### Expected behavior

A version of hls is installed.

### LspInstallInfo output

```shell
Downloading file "https://github.com/haskell/haskell-language-server/releases/download/1.7.0.0/haskell-language-server-Linux-1.7.0.0.tar.gz"...
        ...taller/lua/nvim-lsp-installer/core/managers/std/init.lua:61: Failed to download file "https://github.com/haskell/haskell-language-server/releases/download/1.7.0.0/haskell-language-server-Linux-1.7.0.0.tar.gz".
        spawn: curl failed with exit code 22. curl: (22) The requested URL returned error: 404
```

### Installation log

```shell
[INFO  Wed 27 Apr 2022 03:40:42 PM CEST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:682: Starting install server_name="hls", requested_version=""
[ERROR Wed 27 Apr 2022 03:40:42 PM CEST] ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/process.lua:153: Failed to spawn process. cmd="gh", err="ENOENT: no such file or directory"
[ERROR Wed 27 Apr 2022 03:40:44 PM CEST] ...installer/lua/nvim-lsp-installer/core/installer/init.lua:79: Installation failed, name="hls", error='...taller/lua/nvim-lsp-installer/core/managers/std/init.lua:61: Failed to download file "https://github.com/haskell/haskell-language-server/releases/download/1.7.0.0/haskell-language-server-Linux-1.7.0.0.tar.gz".\nspawn: curl failed with exit code 22. curl: (22) The requested URL returned error: 404 \n'
[INFO  Wed 27 Apr 2022 03:40:44 PM CEST] ...-installer/lua/nvim-lsp-installer/ui/status-win/init.lua:701: Installation completed server_name="hls", success=false
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
  - OK: **gzip**: `gzip 1.10`
  - OK: **curl**: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3`
  - OK: **wget**: `GNU Wget 1.21 built on linux-gnu.`
  - WARNING: **pip3**: not available
  - OK: **python3**: `Python 3.9.2`
  - ERROR: **node**: unsupported version `v12.22.5`. Node version must be >= 14
  - OK: **npm**: `7.5.2`
  - OK: **RubyGem**: `3.2.5`
  - OK: **Ruby**: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]`
  - OK: **cargo**: `cargo 1.58.0 (7f08ace4f 2021-11-24)`
  - OK: **sh**: `Ok`
  - OK: **tar**: `tar (GNU tar) 1.3
```

**Comment by treatybreaker** [comment]
Looking at the releases page of the [haskell language server](https://github.com/haskell/haskell-language-server/releases/) is appears they've moved the packaged releases to their site per the [latest release](https://github.com/haskell/haskell-language-server/releases/tag/1.7.0.0). They're now hosted at https://downloads.haskell.org/~hls/.

The current target attempts to get the lsp on github, which they no longer provide there.

**Comment by williamboman** [comment]
I noticed there are some shell executables at the root of the tar file (ending with `.in`). The "old" executables are now located inside `bin/`. Does anyone know the difference, which one is preferred?

**Comment by cdimitroulas** [comment]
Is there a way to download an older version of hls as a workaround for this problem until it gets sorted?

**Comment by williamboman** [comment]
@cdimitroulas `:LspInstall hls@1.6.1.0` should work 🤞

**Comment by williamboman** [comment]
`fix/hls-install` (#651) ought to fix this. Detecting Linux distro is a bit of a hassle, so for now I've resorted to prompting the user which archive to download, like so:

https://asciinema.org/a/DVoMB32hq4xZXeYU0fgIu0wl8

**Comment by ThoNohT** [comment]
Installing now works indeed. One side note is that installing older versions no longer works.

One issue I have, but I am not sure if it is this plugin's problem, or of haskell-language-server. The hls that is installed is now dynamically linked, and gives me the following issue (in `~/.cache/nvim/lsp.log`):
> [ERROR][2022-05-03 07:48:45] .../vim/lsp/rpc.lua:420	"rpc"	"haskell-language-server-wrapper"	"stderr"	"/home/thonoht/.local/share/nvim/lsp_servers/haskell/bin/haskell-language-server-8.10.7: error while loading shared libraries: libHSCabal-3.2.1.0-ghc8.10.7.so: cannot open shared object file: No such file or directory\n"

I have been able to work around this for now by using ghcup to install hls, and symlinking `~/.local/share/nvim/lsp_servers/haskell/bin` (after renaming the original folder) to `~/.ghcup/bin`, so it is tricked into using the ghcup version which does work.

I believe (but haven't checked) that the vscode plugin used ghcup to install hls. And I found that it is possible to use `ghcup install hls VERSION -i TARGET_PATH` to tell ghcup to install to a specific location. Would this maybe be a way to install hls here as well? It also seems to automatically choose the right version for your distribution.

The directory structure seems to have changed though.
`ghcup install hls 1.6.1.0 -i TARGET_PATH` Seems to place all binaries statically linked directly in the specified path. 
`ghcup install hls 1.7.0.0 -i TARGET_PATH` Creates a structure:
```
bin\
  all binaries (statically linked)
lib\haskell-language-server-1.7.0.0\
  bin\
    all binaries (dynamically linked)
  lib\
    libraries per version
```

**Comment by williamboman** [comment]
> And I found that it is possible to use `ghcup install hls VERSION -i TARGET_PATH` to tell ghcup to install to a specific location. Would this maybe be a way to install hls here as well?

This seems much better, will look into this ASAP. Otherwise, PRs always welcome!
