### ISSUE TITLE
Prompt not looking like in the screenshots

### ISSUE THREAD

**Issue by karma-riuk** [williamboman/nvim-lsp-installer#652]
### Problem description

This is probably a stupid question and I am very sorry if it is, but here is the issue: the prompt that shows up to ask which language server to download when there are multiple options does not look at all like the one present in the screenshots of the README.md (name [this](https://user-images.githubusercontent.com/6705160/150685404-2cd34b25-166e-4c84-b9dd-1d5580dc2bdd.png)) and I have found nothing related to this in already existing issues (maybe I wasn't looking for the right words).

Am I missing some kind of dependency to make `nvim-lsp-installer` look like in the screenshots?

PS: Thanks a lot for developing this plugin, it is a great idea and is very helpful to a lot of us!

### Neovim version (>= 0.6)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui

### Operating system/version

Linux 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

all

### Actual behavior

The prompt I have is much like a command line prompt (see the screenshots section below).

### Expected behavior

The prompt should look like [this](https://user-images.githubusercontent.com/6705160/150685404-2cd34b25-166e-4c84-b9dd-1d5580dc2bdd.png)

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v17.9.0`
  - OK: **cargo**: `cargo 1.60.0`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 18.0.1`
  - OK: **npm**: `8.4.0`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
```

### Screenshots

![image](https://user-images.githubusercontent.com/30158492/166148752-567d997b-2ce0-465a-8c5c-09236a058553.png)

**Comment by williamboman** [comment]
Hello, see `:h vim.ui`. I use https://github.com/stevearc/dressing.nvim to customize `vim.ui`.
