### ISSUE TITLE
Improve documentation on server setup

### ISSUE THREAD

**Issue by gerazov** [williamboman/nvim-lsp-installer#659]
### Is your feature request related to a problem? Please describe.

`LspInstallInfo` lists a lot of server configuration settings, and it's not clear how we can change these.

### Describe the solution you'd like

Add a paragraph in the documentation describing an example.

For instance it took me while to figure out how to enable/disable plugins in the `pylsp` server. 
![image](https://user-images.githubusercontent.com/15214418/166215810-f15af383-9fac-466a-ab52-e4f364126267.png)

One thing I don't find very useful is the McCabe complexity check. Finally I got it working via the `lspconfig` setup function using:
```lua
require('lspconfig').pylsp.setup {
  on_attach = on_attach,
  flags = {
    -- This will be the default in neovim 0.7+
    debounce_text_changes = 150,
  },
  settings = {
    pylsp = {
      plugins = {
        -- pylint = { enabled = true },
        mccabe = { enabled = false }
      }
    }
  }
}
```

This might be server specific, but it would be nice to have this in the documentation to make it easier for people to find and tweak their server settings.

### Additional context

I'm not sure if this is the place to have this information but it would help users of your plugin.

I posted it on the `lspconfig` GitHub as well https://github.com/neovim/nvim-lspconfig/issues/1880

**Comment by williamboman** [comment]
Hello! nvim-lsp-installer is not responsible for setting up servers. What's displayed there is a read-only overview of the server's configuration schema. It's displayed first and foremost to aid discoverability of which settings each server supports.

Would something like this make things clearer:

![discalimer](https://user-images.githubusercontent.com/6705160/166316633-f3d32885-ea03-4f3f-bf0e-7efc1bf380c1.png)

![helop](https://user-images.githubusercontent.com/6705160/166316641-9c48cc61-1d28-4997-8aa0-382e1134e616.png)

**Comment by gerazov** [comment]
Makes sense :+1: I raised an issue there as well - for now they're pointing to the LSPs' websites but they're not nvim (lspconfig) related ...

Nice cow btw :smile:
