### ISSUE TITLE
module 'lspconfig.util' not found

### ISSUE THREAD

**Issue by vzytoi** [williamboman/nvim-lsp-installer#661]
### Problem description

Hey!
I know I'm doing something wrong but I just can't figure out what's going on and I didn't find anything on google so here am I.
Basically I just installed the plugin using packer.nvim and the configuration of the readme but I soon as I restarted by nvim I got this error. What am I doing wrong?
![eror_lsp_installer](https://user-images.githubusercontent.com/65293868/166338272-3e30f175-d8f3-4374-9373-2cb56c093706.png)
Sorry for the time loss :/

### Neovim version (>= 0.6)

NVIM v0.8.0-dev+95-g07660193a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux debian 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

none

### Actual behavior

error

### Expected behavior

no error

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
  - OK: **python3_host_prog**: `Ok`
  - OK: **gzip**: `gzip 1.10`
  - OK: **wget**: `GNU Wget 1.21 built on linux-gnu.`
  - OK: **python3**: `Python 3.9.2`
  - ERROR: **node**: unsupported version `v12.22.5`. Node version must be >= 14
  - OK: **PHP**: `PHP 7.4.28 (cli) (built: Feb 17 2022 16:17:19) ( NTS )`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **curl**: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3`
  - ERROR: **Go**: unsupported version `go version go1.15.15 linux/amd64`. Go version must be >= 1.17.
  - OK: **cargo**: `cargo 1.59.0 (49d8809dc 2022-02-10)`
  - OK: **npm**: `7.5.2`
  - OK: **pip3**: `pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)`
```

**Comment by williamboman** [comment]
Hey! Ah I assume you used the Packer example in the README. I changed it recently and I just realized it's wrong, fixed in https://github.com/williamboman/nvim-lsp-installer/commit/adf1eec567660fd6d56edd80ba68abdb34a9a65b. Try using:

```lua
use {
    "williamboman/nvim-lsp-installer",
    "neovim/nvim-lspconfig"
}
```

**Comment by vzytoi** [comment]
:o it's been literally hours hahah anyway this worked for me thank you very much 
```lua
        use {
            "williamboman/nvim-lsp-installer",
            "neovim/nvim-lspconfig",
            setup = function()
                require("nvim-lsp-installer").setup {}
            end
        }
```
