### ISSUE TITLE
install gopls faild in go 1.15.15

### ISSUE THREAD

**Issue by lvsoso** [williamboman/nvim-lsp-installer#662]
https://github.com/williamboman/nvim-lsp-installer/blob/adf1eec567660fd6d56edd80ba68abdb34a9a65b/lua/nvim-lsp-installer/core/managers/go/init.lua#L43

It can install after I change "install " to "get".

**Comment by williamboman** [comment]
Hello! The supported go versions are `>= 1.17`. See https://go.dev/doc/go-get-install-deprecation
