### ISSUE TITLE
 valals failed

### ISSUE THREAD

**Issue by chen244** [williamboman/nvim-lsp-installer#666]
### Problem description

I install vala_ls ,but it seemed that is is not installed

the fold of vala_ls is like
| name                            | type | size  | modified                                       |
| ------------------------------- | ---- | ----- | ---------------------------------------------- |
| nvim-lsp-installer-receipt.json | file | 371 B | Wed, 04 May 2022 18:59:21 +0800 (a minute ago) |

### Why do you think this is an issue with nvim-lsp-installer?

There is no vala_ls in fold,just a json

### Neovim version (>= 0.6)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux  5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

vala-ls

### Steps to reproduce

:LspInstall vala_ls
cd ~/.local/share/nvim/lsp_servers

### Actual behavior

There is no "vala_ls"

### Expected behavior

Valals installed

### LspInfo

```shell
NO vala_ls
```

### Healthcheck

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.83.0 (x86_64-pc-linux-gnu) libcurl/7.83.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **julia**: `julia version 1.7.2`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v18.1.0`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **sh**: `Ok`
  - OK: **cargo**: `cargo 1.60.0 (d1fd9fe 2022-03-01)`
  - OK: **java**: `Ok`
  - OK: **npm**: `8.5.5`
  - OK: **javac**: `javac 18.0.1`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
```

**Comment by williamboman** [comment]
Ah woops, this was accidentally broken recently, #668 should fix it
