### ISSUE TITLE
Use yarn when npm not exist

### ISSUE THREAD

**Issue by CanKolay3499** [williamboman/nvim-lsp-installer#671]
### Problem description

.

### Neovim version (>= 0.6)

NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux localhost 4.19.132-23682023 #1 SMP PREEMPT Mon Mar 14 11:16:00 +07 2022 aarch64 Android

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

.

### Actual behavior

.

### Expected behavior

Install with yarn when npm don't exist

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - ERROR: **npm**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-android.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **cargo**: `cargo 1.60.0`
  - OK: **Go**: `go version go1.18.1 android/arm64`
  - OK: **curl**: `curl 7.83.0 (aarch64-unknown-linux-android) libcurl/7.83.0 OpenSSL/3.0.2 zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (aarch64-unknown-linux-android)`
  - OK: **node**: `v17.9.0`
  - OK: **pip3**: `pip 22.0.4 from /data/data/com.termux/files/usr/lib/python3.10/site-packages/pip (python 3.10)`
```

**Comment by williamboman** [comment]
I'd prefer to avoid this (see https://github.com/williamboman/nvim-lsp-installer/issues/458#issuecomment-1030392612). Out of curiosity - how come you don't have `npm` installed?

**Comment by CanKolay3499** [comment]
You could uninstall it

**Comment by williamboman** [comment]
Ah ok. npm is currently a requirement to install Node-based LSP servers that are distributed via npm! If you want to use yarn you can override default servers with a custom install method where you use yarn
