### ISSUE TITLE
Configuration to specify download URL

### ISSUE THREAD

**Issue by flyingice** [williamboman/nvim-lsp-installer#678]
### Is your feature request related to a problem? Please describe.

It is a feature request not related to any existing problems.

nvim-lsp-installer tries to download a LSP server always from https://github.com. However, the access to github.com may be slow in some region due to various reasons. As a result, a lot of people there take advantage of a mirror site (e.g. https://hub.fastgit.xyz/) to get around the issue.

### Describe the solution you'd like

It would be nice to include a config option in the plugin which allows to customize the download URL.

### Additional context

Similar feature that has been implemented for wbthomason/packer.nvim:
https://github.com/wbthomason/packer.nvim/issues/433

**Comment by FrankOu2001** [comment]
If you  open `nvim-lsp-installer/lua/nvim-lsp-installer/core/managers/github/`, and there will be `init.lua` and `client.lua` two files. 
If you want to use the mirror for downloading, just editing `init.lua` in line 62:
```
local download_url = ("https://github.com/%s/releases/download/%s/%s"):format(opts.repo, release, asset_file)
```

Hope it is helpful to you.

**Comment by williamboman** [comment]
This definitely makes sense to support! Does branch `feat/github-download-url-setting` (https://github.com/williamboman/nvim-lsp-installer/pull/711) fix this?

**Comment by FrankOu2001** [comment]
I think it would be better to add such a function.
Also, you can write a simple guide in `README.md` to tell people how to use the mirror sites lol.

**Comment by FrankOu2001** [comment]
> I think it would be better to add such a function. Also, you can write a simple guide in `README.md` to tell people how to use the mirror sites lol.

I just see the branch, and I think using a template string is definitely ok.

**Comment by flyingice** [comment]
> This definitely makes sense to support! Does branch `feat/github-download-url-setting` (#711) fix this?
> 
> I'm not sure if using a template string for this is too restrictive, what do you think? Should it be a function instead perhaps?

A template string would be enough to start with. If people find it too restrictive, we can try to figure out a better way later on.

**Comment by williamboman** [comment]
:+1: 

> Also, you can write a simple guide in README.md to tell people how to use the mirror sites lol.

I added a helptag `:h nvim-lsp-installer-download-mirrors`
