### ISSUE TITLE
[New server]: yapf

### ISSUE THREAD

**Issue by brunobmello25** [williamboman/nvim-lsp-installer#680]
### Server name

yapf

### Server homepage

https://github.com/google/yapf

### Languages

Python

### Is this server added in lspconfig?

- [ ] Yes
- [X] No

### How is this server distributed?

via pip

**Comment by williamboman** [comment]
I don't believe there is a language server implementation specifically for yapf? There is a yapf plugin for `pylsp`

**Comment by brunobmello25** [comment]
@williamboman I belive I made a mistake, for some reason thought yapf was an lsp when it's in fact just a formatter. sorry for the confusion, I'll close this PR

**Comment by williamboman** [comment]
Formatters might end up happening soon, see https://github.com/williamboman/nvim-lsp-installer/issues/95! This will most very likely happen in a separate plugin though.

**Comment by brunobmello25** [comment]
That would be great! I'll follow that issue, looking forward to it happening one day
