### ISSUE TITLE
[New server]: eslint_d

### ISSUE THREAD

**Issue by brunobmello25** [williamboman/nvim-lsp-installer#681]
### Server name

eslint_d

### Server homepage

https://github.com/mantoni/eslint_d.js/

### Languages

typescript, javascript

### Is this server added in lspconfig?

- [X] Yes
- [ ] No

### How is this server distributed?

via npm

**Comment by williamboman** [comment]
There is already an `eslint` server!

**Comment by brunobmello25** [comment]
@williamboman eslint and eslint_d are actually different servers. would be nice to have eslint_d as well as eslint server

**Comment by williamboman** [comment]
Hm by server do you specifically mean an LSP-capable server that communicates with a LSP-capable client via JSON RPC? I've only used eslint_d superficially in the past, but my understanding is that it's simply just a daemon process that aims to speed up invocations of the CLI tool?

**Comment by brunobmello25** [comment]
huh, I guess it wouldn't make such a difference having eslint_d after all. I ended up just switching my config to use `eslint` instead of `eslint_d`. It's even simpler to setup.

Thanks for the help! and sorry again for the confusion hehe
