### ISSUE TITLE
How can I see all of the configurations?

### ISSUE THREAD

**Issue by mosheavni** [williamboman/nvim-lsp-installer#689]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Some language servers have a server configuration schema I can see when running `:LspInstallInfo`
I wish there could be a way to see ALL possible configurations for ALL LSPs

I want to contribute, where can the server settings be seen? only on the LSP github repo?
Anyway to see that in the code?

**Comment by williamboman** [comment]
Hello! Not all servers provide a JSONSchema for its configuration. Some don't even document it at all, while others only put it in a README file. [This gist](https://gist.github.com/williamboman/a01c3ce1884d4b57cc93422e7eae7702) maps servers to their respective schema.
