### ISSUE TITLE
[New server]: Tilt Starlark server

### ISSUE THREAD

**Issue by Davincible** [williamboman/nvim-lsp-installer#695]
### Server name

Tilt

### Server homepage

https://docs.tilt.dev/cli/tilt_lsp_start.html

### Languages

starlark

### Is this server added in lspconfig?

- [ ] Yes
- [X] No

### How is this server distributed?

https://github.com/tilt-dev/tilt

**Comment by alexander-born** [comment]
Just learned of this language server. Does this also work for bazel files, which also use the starlark language? That would be great.

**Comment by Davincible** [comment]
Not sure, probably

**Comment by williamboman** [comment]
The Tilt LSP ships with the `tilt` runtime itself, so I won't be adding it to nvim-lsp-installer. See https://github.com/neovim/nvim-lspconfig/pull/1941 for adding it to lspconfig, once added you just need to make sure `tilt` is installed in PATH and then:

```lua
require("lspconfig").tilt_ls.setup {}
```

You might need to add ftdetect autocommands, like:

```vim
autocmd BufRead Tiltfile set ft=tiltfile
```

**Comment by nicksieger** [comment]
> Just learned of this language server. Does this also work for bazel files, which also use the starlark language? That would be great.

You might be able to use https://github.com/tilt-dev/starlark-lsp standalone for this. Let me know if you need any help with that.
