### ISSUE TITLE
[New server]: Apex, Aura, and LWC

### ISSUE THREAD

**Issue by LeviticusNelson** [williamboman/nvim-lsp-installer#701]
### Server name

Apex, Aura, LWC

### Server homepage

https://github.com/forcedotcom/salesforcedx-vscode

### Languages

apex, javascript, etc. (I think the list is supplied in the GitHub ReadME)

### Is this server added in lspconfig?

- [ ] Yes
- [X] No

**Comment by acifuentes99** [comment]
Hi!, I have been trying recently porting the Apex lsp into nvim-lsp-installer. I just make it work, following instructions on (https://github.com/williamboman/nvim-lsp-installer/blob/demo/old-setup/CUSTOM_SERVERS.md), for automating installation. 

In the following gist, is the piece of code that I imported into my config: https://gist.github.com/acifuentes99/ea1231bb8f7ab023d1dc4589ae43c16c

That should work. I'll update my rc for more context of usage

**Comment by LeviticusNelson** [comment]
@acifuentes99 Thanks! I got the server to show up on lsp install but now it won't activate when I am in a .cls file

**Comment by acifuentes99** [comment]
@LeviticusNelson are .cls file reading as apexcode type of file? (command :set filetype?) I think, if you registered the server on lspconfig[lsp].setup (line 71), it should work.

Otherwise, it could be that nvim didn't recognize .cls files as apexcode. For references, there is my init.lua conifguration: https://github.com/acifuentes99/vimrc/tree/pure_lua

**Comment by LeviticusNelson** [comment]
I just switched from NvChad to LunarVim so I don't know how to add a custom server, but I did find many more references for @williamboman
https://github.com/johnmutuma5/coc-apex
https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex
https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-lwc
https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-visualforce-language-server

**Comment by williamboman** [comment]
Hello! Could you please give the following branches a try:

- `williamboman/lspconfig: branch feat/apex_ls`
- `williamboman/nvim-lsp-installer: branch feat/apex_ls`

**Comment by williamboman** [comment]
I'm a bit confused as I have no previous experience with these Salesforce tools. So the above adds an "Apex" language server. I believe the only other one is the Visualforce language server, the other packages seem to be VSCode client-only extensions?

**Comment by LeviticusNelson** [comment]
Yeah, Apex and Visualforce should have their own language server. Aura components are just prebuilt web components, so an LSP isn't needed for that. Lightning Web Components uses VS Code's default HTML language server, so I don't know how that would translate well for an LSP.

**Comment by williamboman** [comment]
As for the Visualforce language server - this one's a bit more problematic. If anyone would like to ask them to publish the `.vsix` files as part of their GitHub releases, that'd be really helpful.

**Comment by williamboman** [comment]
Apex added in #746. Visualforce will be added in #748 pending lspconfig merge.
