### ISSUE TITLE
"--depth=1" cause ccls installation failed

### ISSUE THREAD

**Issue by black-desk** [williamboman/nvim-lsp-installer#715]
https://github.com/williamboman/nvim-lsp-installer/blob/4ed43f1f885612f587253b3e32f54408c793ca55/lua/nvim-lsp-installer/core/managers/git/init.lua#L24

https://github.com/MaskRay/ccls/blob/74458915b3472b0df26264d7d1599505385cf453/CMakeLists.txt#L247

ccls run `git describe --tag --long HEAD` in its CMakeList.txt, which will failed with git repo cloned with `--depth=1`.

**Comment by williamboman** [comment]
Hello! Hmm I'm unable to reproduce on the systems I have access to. Could you please follow the issue template dedicated for server installations issues [here](https://github.com/williamboman/nvim-lsp-installer/issues/new?assignees=&labels=installation-issue&template=server_installation_form.yaml) 🙏?
