### ISSUE TITLE
Add `ltex-ls` platform independent version as an install option 

### ISSUE THREAD

**Issue by David-Else** [williamboman/nvim-lsp-installer#717]
### Is your feature request related to a problem? Please describe.

At the moment all the versions of `ltex-ls` offered have the entire Java runtime built in. If you have Java 11 or greater on your computer then you are far better using the platform independent version that does not come with Java.

https://valentjn.github.io/ltex/ltex-ls/installation.html#installation

On github this is https://github.com/valentjn/ltex-ls/releases/download/15.2.0/ltex-ls-15.2.0.tar.gz for the current version.

It is far better to let your distro manage Java as it can keep up with any security issues for you, and you only need the runtime, for example on RHEL that is `sudo dnf install java-11-openjdk-headless`

### Describe the solution you'd like

You might even test if Java is installed and download this one automatically, or give an option. Cheers!

**Comment by williamboman** [comment]
Hello! It seems like the `ltex-ls` script respects `JAVA_HOME` (`[ -z "$JAVA_HOME" ] && JAVA_HOME="$BASEDIR"/jdk-11.0.12+7`), so you can already use a custom Java runtime if you'd like. It'll however mean that a Java runtime is unnecessarily downloaded alongside ltex (`~60M`).

I think it'd be reasonable to download platform-independent version if `java` exists on the system :+1:
