### ISSUE TITLE
Unable to access lsp install window

### ISSUE THREAD

**Issue by jpdube** [williamboman/nvim-lsp-installer#722]
### Problem description

Hi,
I received this error when I try to access the lsp installer info window:

Error detected while processing function <SNR>32_LspInstallInfo:
line    1:
E5108: Error executing lua ...im-lsp-installer/lua/nvim-lsp-installer/servers/init.lua:246: Unable to import server denols.

This is an unexpected error, please file an issue at https://github.com/williamboman/nvim-lsp-installer with the following information:
loop or previous error loading module 'nvim-lsp-installer.servers.denols'
stack traceback:
        [C]: in function 'error'
        ...im-lsp-installer/lua/nvim-lsp-installer/servers/init.lua:246: in function <...im-lsp-installer/lua/nvim-lsp-installer/servers/init.lua:243>
        vim/shared.lua: in function 'get_available_servers'
        ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/ui/init.lua:1103: in function 'status_win'
        ...cker/start/nvim-lsp-installer/lua/nvim-lsp-installer.lua:51: in function 'open'
        [string ":lua"]:1: in main chunk

### Neovim version (>= 0.7)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info

### Operating system/version

Darwin leica-m6 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [ ] Yes

### Affected language servers

all

### Actual behavior

Not working

### Expected behavior

To enable access to the install window

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v16.13.1`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
  - OK: **Go**: `go version go1.18.2 darwin/arm64`
  - OK: **sh**: `Ok`
  - OK: **cargo**: `cargo 1.61.0 (a028ae42f 2022-04-29)`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.0.3.1`
  - OK: **javac**: `Ok`
  - OK: **npm**: `8.1.2`
  - OK: **pip3**: `pip 22.0.4 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Wed 25 May 21:48:15 2022.
```

**Comment by williamboman** [comment]
Hm that seems pretty odd. Is this 100% reproducible or just a one-off occurrence? Were you by chance upgrading plugin versions without restarting neovim while it happened?

**Comment by williamboman** [comment]
Please reopen if you're still having issues

**Comment by jpdube** [comment]
Yes it is, Because I have the exact same config on my linux laptop with no issues. On my mac I even removed the .local/share/nvim directory where packer stores all the plugin and start from scratch, and I still have the problem. It’s impossible to setup lsp server.

Salutations,
------------------------------------------
[signature_1537136080]
Jean-Pierre Dubé
Président
www.numa-informatique.com<https://urldefense.com/v3/__http:/www.numa-informatique.com/__;!!HUqgN_M!9P23id5LuEs07kbAelK2nhDBxSMvfRB26SbhZtOqqJYhmx_jrBBMu2vAcA8Y8sA$>
990 Tailleur
Laval, Québec
Canada, H7X3P3
Tel: 514-316-6700 ext :101
Support technique : 514-316-6700 ext : 500

From: William Boman ***@***.***>
Date: Thursday, May 26, 2022 at 08:03
To: williamboman/nvim-lsp-installer ***@***.***>
Cc: Jean-Pierre Dube ***@***.***>, Author ***@***.***>
Subject: Re: [williamboman/nvim-lsp-installer] Unable to access lsp install window (Issue #722)

Hm that seems pretty odd. Is this 100% reproducible or just a one-off occurrence? Were you by chance upgrading plugin versions without restarting neovim while it happened?
