### ISSUE TITLE
lsp cannot find soland executable despite being installed and available

### ISSUE THREAD

**Issue by gdnathan** [williamboman/nvim-lsp-installer#727]
### Problem description

I installed solang with nvim-lsp-installer, and no errors. Solang executable exist in `/home/erudyx/.local/share/nvim/lsp_servers/solang`, but when i start nvim on a .sol file, and run `:LspInfo`, i have this error on solang language server:

```
 	cmd is executable: false (checked by nvim-lsp-installer)
 	                   Make sure you have set up nvim-lsp-installer (:h nvim-lsp-installer-quickstart)
```

### Why do you think this is an issue with nvim-lsp-installer?

The non-executability of solang server is marked "checked by nvim-lsp-installer", and i installed with it, so the issue probably come from it.

### Neovim version (>= 0.7)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux erudyx-endeavouros 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

Solang

### Steps to reproduce

1 - open a .sol file
2 - do `:LspInstall`
3 - refresh

### Actual behavior

there is no language server active on the file (no lint, no hover, no diagnostics...)

### Expected behavior

solang language server works``

### LspInfo

```Text
Language client log: /home/erudyx/.cache/nvim/lsp.log
 Detected filetype:   solidity
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: solidity
 
 Config: solang
 	filetypes:         solidity
 	root directory:    NA
 	cmd:               solang --language-server --target ewasm
 	cmd is executable: false (checked by nvim-lsp-installer)
 	                   Make sure you have set up nvim-lsp-installer (:h nvim-lsp-installer-quickstart)
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: sumneko_lua, hls, clangd, rust_analyzer, tsserver, solang
```
```


### LspLog

_No response_

### Healthcheck

```Text
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.83.1 (x86_64-pc-linux-gnu) libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v14.19.3`
  - OK: **cargo**: `cargo 1.62.0-nightly (3f052d8ee 2022-05-12)`
  - OK: **Go**: `go version go1.18.2 linux/amd64`
  - OK: **sh**: `Ok`
  - OK: **npm**: `8.5.5`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: GitHub API rate limit. Used: 8. Remaining: 52. Limit: 60. Reset: sam. 28 mai 2022 16:32:59.
```

**Comment by williamboman** [comment]
Hello! (I will assume you have read and followed the necessary setup docs for this plugin) In your steps to reproduce, what do you mean by `3. refresh`? Do you still get the error message about it not being executable if you restart neovim after installation?

Also, I see that `:LspInfo` is reporting `root directory: NA`. This means that lspconfig was unable to find a project directory in which to start the server in (see `:h lspconfig-root-dir`). Solang looks for the [nearest `.git/` directory.](https://github.com/williamboman/nvim-lspconfig/blob/1edb28b1c88aa417b040a244dd70a203eb85b8b7/lua/lspconfig/server_configurations/solang.lua#L6), so make sure you're working in a git project (or, change the `root_dir` yourself when you set up the server `:h lspconfig-setup`).

**Comment by gdnathan** [comment]
By "refresh" i mean "leave and restart neovim", to make sure everything is set up correctly after install

`git init` solved the problem, thank you ! I didnt know about this, now it's working, thank you !
