### ISSUE TITLE
error while require 'nvim-lsp-installer'

### ISSUE THREAD

**Issue by Acceyuriko** [williamboman/nvim-lsp-installer#738]
### Problem description

```
E5113: Error while calling lua chunk: Vim:E6100: "state" is not a valid stdpath
stack traceback:
        [C]: in function 'stdpath'
        .../start/nvim-lsp-installer/lua/nvim-lsp-installer/log.lua:35: in main chunk
        [C]: in function 'require'
        ...rt/nvim-lsp-installer/lua/nvim-lsp-installer/core/fs.lua:1: in main chunk
        [C]: in function 'require'
        ...cker/start/nvim-lsp-installer/lua/nvim-lsp-installer.lua:1: in main chunk
        [C]: in function 'require'
        /home/yuriko/.config/nvim/lua/yuriko/cmp.lua:8: in function 'setup'
        /home/yuriko/.config/nvim/init.lua:98: in main chunk
```

### Why do you think this is an issue with nvim-lsp-installer?

I guess the commit [2631265173cd2c9b3ffa9057b6125477b077abf8 ](https://github.com/williamboman/nvim-lsp-installer/commit/2631265173cd2c9b3ffa9057b6125477b077abf8) caused this problem.

If I download installer of version 3c21304c3f54caf0c00fab00cf1e4e9c0507b5d1, the problem disappeared.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+124-g815b65d77
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux Acceyuriko 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [ ] Yes

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

all

### Steps to reproduce

1. update nvim-lsp-installer to newest version.
2. restart neovim.

### Actual behavior

errors occured.

### Expected behavior

require('nvim-lsp-installer') normally

### LspInfo

```Text
crashed, so there is nothing
```

### Healthcheck

```Text
crashed, so there is nothing
```

**Comment by Slotos** [comment]
Updating to latest neovim-nightly fixes this issue.

Seems like `stdpath("state")` is not available in early nightlies that report version as 0.8.0.
