### ISSUE TITLE
Cannot disable provider check

### ISSUE THREAD

**Issue by r2com** [williamboman/nvim-lsp-installer#741]
adding:
vim.g.loaded_java_provider=0

does not remove java check during :checkhealth
it prints me:
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
...
- WARNING: java: not available
...

same with other languages which I am disabling, how to disable it?

**Comment by williamboman** [comment]
Hello! So the health check doesn't concern itself with how different providers (`:h provider`) are configured. To my knowledge, that is only relevant for remote plugins (`:h remote-plugin`). The health check of this plugin checks whether the different tools and utilities needed to install servers are available, so you can just ignore any WARNING messages you see if you're not experiencing issues with the plugin.
