### ISSUE TITLE
How to set path to existing server?

### ISSUE THREAD

**Issue by xbladesub** [williamboman/nvim-lsp-installer#742]
I have installed LSP server (solc) on my system and I don't want to install it again. So basically I need to specify already existing server instead of use :LspInstall solc... How can I achieve that?

**Comment by xbladesub** [comment]
> Hello! To use servers managed outside of nvim-lsp-installer you either need to:
> 
> 
> 
> 1) ensure they are on your `PATH` (`:echo executable("<replace-with-server-executable>")` should print `1`), or
> 
> 2) when setting up the server (via for example `lspconfig`), provide the full path to the server executable, like `/place/where/server/is/installed/start-server`)
> 
> 
> 
> nvim-lsp-installer is not involved in either of above cases

Actually I have little bit different problem - I want to use 'solc-select', which allows you to choose different 'solc' versions, unfortunately lspconfig doesn't recognize 'solc' executable, which is used by 'solc-select'

**Comment by williamboman** [comment]
I'm unable to reproduce in a clean container: https://asciinema.org/a/qJeVZFThhIA2wK7Jsai1vnTPj. Make sure `solc` is in your PATH when launching neovim. (also this is not at all related to nvim-lsp-installer)
