### ISSUE TITLE
Need a border setting instead of setting it up via autocmd.

### ISSUE THREAD

**Issue by cpea2506** [williamboman/nvim-lsp-installer#752]
I'm using transparent background and no border make `LspInstallInfo` window have a weird look.

<img width="1295" alt="Screen Shot 2022-06-05 at 22 21 55" src="https://user-images.githubusercontent.com/42694704/172057766-64b319e0-274b-4d48-b5bf-f7f7834a497a.png">
 

I would like to have a border setting like below.

```lua
require("nvim-lsp-installer").setup({
    ui = {
        border = "rounded", -- default to "none"
    }
})
```

**Comment by williamboman** [comment]
Added in #754!
