### ISSUE TITLE
Support installation of debugging servers.

### ISSUE THREAD

**Issue by sharpenedblade** [williamboman/nvim-lsp-installer#756]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Install debugging servers in the same way lsp servers are installed.

### Describe potential alternatives you've considered

Using `dap-buddy.nvim`(used to be `DIInstall.nvim`). The new version is not working yet, and it would be simpler to have both be managed by the same plugin. Otherwise there is a lot of duplicated code.

**Comment by williamboman** [comment]
Hello! This would probably not be in scope for this plugin per se, I'll refer to this comment for more context:  https://github.com/Pocco81/dap-buddy.nvim/issues/71#issuecomment-1106527425
