### ISSUE TITLE
LSP's using zx to install fails on `replaceAll('\\', '\\\\')

### ISSUE THREAD

**Issue by Issafalcon** [williamboman/nvim-lsp-installer#76]
### Software installed
- Ubuntu-20.04 LTS
- Neovim 0.5 (nightly, or app image)
- Latest nvim-lsp-installer plugin

### Description

Firstly, thanks for writing this installer. It has simplified my neovim setup immensely! 

The issue occurs when I try to install lsps that rely on the zx package. Specifically `terraform-ls` and `clangd`. When running :LspInstall, I get the following error:

```
file:///home/issafalcon/.local/share/nvim/lsp_servers/.zx/node_modules/zx/index.mjs:244
      .replaceAll('\\', '\\\\')
       ^

TypeError: arg.replaceAll is not a function
    at Function.quote (file:///home/issafalcon/.local/share/nvim/lsp_servers/.zx/node_modules/zx/index.mjs:244:8)
    at $ (file:///home/issafalcon/.local/share/nvim/lsp_servers/.zx/node_modules/zx/index.mjs:39:13)
    at file:///home/issafalcon/.local/share/nvim/site/pack/packer/start/nvim-lsp-installer/lua/nvim-lsp-installer/servers/clangd/install.mjs:15:8
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async importPath (file:///home/issafalcon/.local/share/nvim/lsp_servers/.zx/node_modules/zx/zx.mjs:130:3)
    at async file:///home/issafalcon/.local/share/nvim/lsp_servers/.zx/node_modules/zx/zx.mjs:49:5

[Process exited 1]
```

I tried for clojure_lsp also, which has the same issue, but sumneko_lua works fine. For now, I am installing manually and using my own configuration for these servers, but thought I would raise this in case others are finding the same problem, and it's not just an issue on my own machine setup.

**Comment by williamboman** [comment]
Hey! What Node version are you running `node --version`? It seems like zx snuck in a bump in required Node version [this July](https://github.com/google/zx/releases/tag/1.15.1), going from 14 (LTS) to 15 (`String.prototype.replaceAll` was added in Node.js 15).

**Comment by Issafalcon** [comment]
Ah, thanks! I was running on 14.7. I updated to 15.14.0, which seemed to get me further to this point:
```
/bin/bash: /home/issafalcon/.local/share/nvim/lsp_servers/.zx/node_modules/.bin/zx: No such file or directory
```

**Comment by williamboman** [comment]
Hmm, interesting. Did you restart neovim after upgrading Node? It caches zx installations per neovim session which might be causing some issues

**Comment by Issafalcon** [comment]
Seems killing and restarting my tmux session was also necessary for it to work! Thanks for your help! I'll close this out.

**Comment by williamboman** [comment]
:+1: cool. I've asked if they could backport the fix to the `v1` release branch, in which case Node 14 (LTS) should work just fine again!
