### ISSUE TITLE
More faster installation of the sumneko_lua server...

### ISSUE THREAD

**Issue by TeoDev1611** [williamboman/nvim-lsp-installer#78]
Hey I am here again 😄 

Well the installation for sumneko is more easy will dont need compile with ninja the binaries are [here](https://github.com/sumneko/vscode-lua)

Can you clone the repo and use the binaries example with lspconfig :) 

https://github.com/TeoDev1611/AstroVim/blob/astro/lua/lsp/lsp-servers/init.lua#L10

Using this repo

Great work with the windows support 🚀

**Comment by williamboman** [comment]
Cool, will take a look!

By the way, speaking of Windows.. I've been working on making a prettier UI where you can get a better overview of installed & available LSP servers, and also improved support for parallel installations. Would you mind giving the branch `UI` a try? I've tested it a bit on Windows and it at least didn't blow up

**Comment by TeoDev1611** [comment]
> Cool, will take a look!
> 
> By the way, speaking of Windows.. I've been working on making a prettier UI where you can get a better overview of installed & available LSP servers, and also improved support for parallel installations. Would you mind giving the branch `UI` a try? I've tested it a bit on Windows and it at least didn't blow up

Great.. I will test :)

**Comment by TeoDev1611** [comment]
@williamboman  works good the ui 
![image](https://user-images.githubusercontent.com/73144037/132258313-14de058b-a22c-41c7-9310-9005a3f335e5.png)

But sometimes the neovim window take freezed

**Comment by williamboman** [comment]
Thanks for checking so quickly!

> But sometimes the neovim window take freezed

Hmm how do you mean? That nothing is updating visually in the window, or that your neovim actually freezes? What are you doing when it happens?

**Comment by TeoDev1611** [comment]
> Thanks for checking so quickly!
> 
> > But sometimes the neovim window take freezed
> 
> Hmm how do you mean? That nothing is updating visually in the window, or that your neovim actually freezes? What are you doing when it happens?

I can't move between the buffers only are freezed and show the window and the information. Example in the image

**Comment by williamboman** [comment]
> I can't move between the buffers only are freezed and show the window and the information. Example in the image

Can you see if there is a background terminal window that captures your focus? In my tests on Windows, I noticed that it would spawn terminal windows due to a specific configuration I had set. I've now changed that configuration to disable this behavior and pushed again to `UI` branch

**Comment by TeoDev1611** [comment]
> > I can't move between the buffers only are freezed and show the window and the information. Example in the image
> 
> Can you see if there is a background terminal window that captures your focus? In my tests on Windows, I noticed that it would spawn terminal windows due to a specific configuration I had set. I've now changed that configuration to disable this behavior and pushed again to `UI` branch

Now not freeze  the windows intersting

**Comment by williamboman** [comment]
Resolved in #85.
