### ISSUE TITLE
minimal sample stopped working

### ISSUE THREAD

**Issue by alex-popov-tech** [williamboman/nvim-lsp-installer#80]
hello!
here is video of minimal setup of that perfect plugin, which stopped working  ( i think after updating it today ):

https://user-images.githubusercontent.com/21224705/132539461-0f140b62-4705-47b2-a85c-249791556d3b.mp4

basically it looks like `cb` is never called for some reason 🤔 
any ideas on that?

**Comment by williamboman** [comment]
Hi! Yes this was due to an error I made yday when doing some refactoring https://github.com/williamboman/nvim-lsp-installer/commit/77ee79632a0a6ce885246c15cd0cd1e8c0b889fc. Should be fixed in the latest version! Could you try upgrading the plugin version?

**Comment by alex-popov-tech** [comment]
oh, thanks!
i should do that before 1h debugging session :)

**Comment by williamboman** [comment]
> i should do that before 1h debugging session :)

Sorry 🙈!
