### ISSUE TITLE
Clangd in Windows

### ISSUE THREAD

**Issue by XtraSavx** [williamboman/nvim-lsp-installer#82]
Hi! 😀

I make this issue because I wanted to know if Clangd is available on Windows, because I run `:LspInstall clangd`,
and it tells me: **Windows is not supported yet for server "clangd"**.

And what I want to ask is if you could give support to clangd in Windows or do I have to install something so that the server can be installed.

That's all I await your answer. 😊

**Comment by williamboman** [comment]
Hey! Windows support for clangd seems fairly easy to implement, will look into it asap!

**Comment by XtraSavx** [comment]
> Hey! Windows support for clangd seems fairly easy to implement, will look into it asap!

Thanks!
So if windows has the support, how can I install it?

**Comment by williamboman** [comment]
> So if windows has the support, how can I install it?

`:LspInstall clangd`

**Comment by XtraSavx** [comment]
> > So if windows has the support, how can I install it?
> 
> `:LspInstall clangd`

![image](https://user-images.githubusercontent.com/81933734/132601788-14508127-a3a7-4c63-888d-d4e2ad3cf26f.png)
I get this. 😕

**Comment by williamboman** [comment]
Hehe yes I haven't had time to look into this yet, I'll let you know in this issue once it's ready

**Comment by XtraSavx** [comment]
> Hehe yes I haven't had time to look into this yet, I'll let you know in this issue once it's ready

Thank you I will be attentive. 👀

**Comment by williamboman** [comment]
Hej @XtraSavx, `clangd` support should be available for Windows now. Upgrade the plugin to the latest version and it should work!
