### ISSUE TITLE
Can't install any server

### ISSUE THREAD

**Issue by lcmen** [williamboman/nvim-lsp-installer#833]
### Problem description

When I try to install any LSP server I get error "attempt to yield across methamethod/C-call boundary". It happens for me on Ubuntu 22 LTS running inside VM. It all works fine locally on MacOS.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-a1pIhJ/neovim-0.7.0~ubuntu1+git202206222126-b20b28249-dd05b3569=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-a1pIhJ/neovim-0.7.0~ubuntu1+git202206222126-b20b28249-dd05b3569/build/config -I/build/neovim-a1pIhJ/neovim-0.7.0~ubuntu1+git202206222126-b20b28249-dd05b3569/src -I/build/neovim-a1pIhJ/neovim-0.7.0~ubuntu1+git202206222126-b20b28249-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-a1pIhJ/neovim-0.7.0~ubuntu1+git202206222126-b20b28249-dd05b3569/build/src/nvim/auto -I/build/neovim-a1pIhJ/neovim-0.7.0~ubuntu1+git202206222126-b20b28249-dd05b3569/build/include
Compiled by buildd@bos02-arm64-069

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux vm 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:57:22 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

All

### Actual behavior

When I try to install any LSP server I get error "attempt to yield across methamethod/C-call boundary" without any further explanation. Changing logging to `DEBUG` mode does not help either.

### Expected behavior

It should install a server successfully.

### LspInstallInfo output

```Text
Pending servers (1)
  ◍ tsserver (failed)
      attempt to yield across metamethod/C-call boundary
```

### Installation log

```Text
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: Queuing server="tsserver", version="" for installation
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: Starting install server_name="tsserver", requested_version=""
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: Executing installer for name="tsserver"
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: fs: mkdirp /home/lucas/.local/share/nvim/lsp_servers/tsserver.tmp
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: fs: write_file /home/lucas/.local/share/nvim/lsp_servers/tsserver.tmp/.npmrc
[ERROR Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: Installation failed, name="tsserver", error="attempt to yield across metamethod/C-call boundary"
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: fs: rmrf /home/lucas/.local/share/nvim/lsp_servers/tsserver.tmp
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: fs: rmrf /home/lucas/.local/share/nvim/lsp_servers/tsserver.tmp
[DEBUG Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: fs: rmrf failed
[INFO  Thu 23 Jun 2022 10:24:16 PM CEST] (tail call):-1: Installation completed server_name="tsserver", success=false
```

### Healthcheck

```Text
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux]`
  - OK: **RubyGem**: `3.3.7`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `7.24.0`
  - OK: **node**: `v16.10.0`
  - OK: **python3**: `Python 3.10.4`
  - OK: **pip3**: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **curl**: `curl 7.81.0 (aarch64-unknown-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (aarch64-unknown-linux-gnu)`
  - OK: **sh**: `Ok`
  - WARNING: Failed to check GitHub API rate limit status.
```

**Comment by williamboman** [comment]
Hello! I believe this could be due to the Lua runtime that is bundled with your neovim installation. There's another report of this happening here: https://github.com/williamboman/nvim-lsp-installer/discussions/825. My suggestion to them was to try to build neovim from source instead and see if that helps. It seems like this issue with coroutines is not isolated to just this plugin which leads me to believe that something's up with your Lua runtime itself. (this plugin makes heavy use of coroutines so I'm not sure there's much I can do, unless my implementation of them is erroneous in some way)

**Comment by lcmen** [comment]
Thanks @williamboman for suggestions. I also tried to install Neovim from Snap but I've encountered the same problem. I will try to compile Neovim from source then.
