### ISSUE TITLE
Update Command

### ISSUE THREAD

**Issue by arnavgpt** [williamboman/nvim-lsp-installer#839]
### Is your feature request related to a problem? Please describe.

Updates for installed servers are only exclusively checked when the UI window is opened, that happens when you either try to install/uninstall a server. 

Primarily, users don't generally installs/reinstalls servers until they are caught with some sort of issue.
This leads to outdated servers for long duration of time.

### Describe the solution you'd like

Commands like `LspUpdateAll` or `LspUpdate <server>` would resolve this issue

### Describe potential alternatives you've considered

N/A

### Additional context

N/A

**Comment by williamboman** [comment]
Hello! There's a (pretty old) issue for this already here - #194. It's not particularly difficult to implement, but I'm a bit hesitant on doing it as I'm worried it might lead to usage patterns that are harmful. Example being things like automatically executing the command everytime neovim is launched, opening up for 1) heavy I/O operations that are "hidden" to the user, 2) botched installations in case of short sessions or opening multiple neovim instances simultaneously, 3) somewhat undefined behavior that currently exists if a server is upgraded while it's already running, and 4) inadvertently upgrading to new versions that carry breaking changes.

Of course some of these also apply when upgrading via the UI, but I feel like doing it via the UI is more of a conscious decision where you're more prepared for things to "break". They're all solvable problems but it's not something I've put much effort into yet, until then I'll probably have the same opinion.
