### ISSUE TITLE
Error while installing tsserver in windows

### ISSUE THREAD

**Issue by HypsterOP** [williamboman/nvim-lsp-installer#84]
Hey! When i tried to install tsserver i got an error, and I thought it might be an issue of mine so when I tried to install json i got the same error

Image reference => [Imgur](https://i.imgur.com/1ZNrJy4.png)

**Comment by williamboman** [comment]
Hey! It seems like you've got the https://github.com/kabouzeid/nvim-lspinstall plugin installed, not this one. Or perhaps both, but https://github.com/kabouzeid/nvim-lspinstall loaded after this one so it captures the `:LspInstall` command

**Comment by HypsterOP** [comment]
> Hey! It seems like you've got the https://github.com/kabouzeid/nvim-lspinstall plugin installed, not this one. Or perhaps both, but https://github.com/kabouzeid/nvim-lspinstall loaded after this one so it captures the `:LspInstall` command

So can you tell me how to fix it? thanks.

**Comment by williamboman** [comment]
I'm sorry I can't help you as it depends on how you've set things up. But basically, if you want to use this plugin, only install this one and not https://github.com/kabouzeid/nvim-lspinstall. If you want to use https://github.com/kabouzeid/nvim-lspinstall only install that plugin and not this one.
