### ISSUE TITLE
:LspInfo after installing hls throws error 

### ISSUE THREAD

**Issue by cheeze2000** [williamboman/nvim-lsp-installer#844]
### Problem description

After installing hls from the ui in `:LspInstallInfo` and restarting neovim, hls works perfectly (autocompletion and hover work fine). The only problem is when `:LspInfo` is run and it throws this error:
![image](https://user-images.githubusercontent.com/26966445/176805310-3f17af3c-5fb0-4320-a06f-8ef2cba20026.png)
![image](https://user-images.githubusercontent.com/26966445/176805959-7ea5aafa-ce2d-4034-8eea-ef8eb414f5bc.png)

### Why do you think this is an issue with nvim-lsp-installer?

I tried installing hls from ghcup myself and removed nvim-lsp-installer from my config and `:LspInfo` does not throw any error

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux Mozzarella 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

hls

### Steps to reproduce

1. Download the minimal debug config
2. Include this line `lspconfig.hls.setup { on_attach = on_attach }`
3. Run neovim with that config and install hls
4. Enter any haskell project
5. LSP works but only `:LspInfo` throws

### Actual behavior

`:LspInfo` throws an error, screenshot above

### Expected behavior

`:LspInfo` does not throw an error and it shows that 1 server is running, which is hls

### LspInfo

```Text
Doing this throws an error and upon dismissing the error, it is just a blank floating window
```

### LspLog

```Text
No, the LSP works
```

### Healthcheck

```Text
It is included in one of the screenshots above
```

**Comment by williamboman** [comment]
Hello! Should be fixed in #847
