### ISSUE TITLE
Spawning language server with cmd: `a-language-server` failed. The language server is either not installed, missing from PATH, or not executable.

### ISSUE THREAD

**Issue by williamhCode** [williamboman/nvim-lsp-installer#848]
### Problem description

After I install a server and setup the config and everything, it never works when I go in the file. For example if I go into a python file, it says.
```
Spawning language server with cmd: `pyright-langserver` failed. The language server is either not installed, missing from PATH, or not executable.
```

### Why do you think this is an issue with nvim-lsp-installer?

If I brew install pyright instead of using nvim-lsp-installer, it works.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+528-g3b1423bfa
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin Williams-MacBook-Pro-2.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

all

### Steps to reproduce

1. Do the basic setup for lsp-config and nvim-lsp-installer.
2. Open any file that has its language server installed.

### Actual behavior

Command line outputs
```
Spawning language server with cmd: `a-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
```

### Expected behavior

The Lsp server should run.

### LspInfo

```Text
Python:
 Language client log: /Users/williamhou/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: python
 
 Config: pyright
 	filetypes:         python
 	root directory:    /Users/williamhou/Documents/Coding/Personal-coding/Free-Notes-Platform
 	cmd:               pyright-langserver --stdio
 	cmd is executable: true (checked by nvim-lsp-installer)
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: sumneko_lua, pyright, ccls

Lua:
 Language client log: /Users/williamhou/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: python
 
 Config: pyright
 	filetypes:         python
 	root directory:    /Users/williamhou/Documents/Coding/Personal-coding/Free-Notes-Platform
 	cmd:               pyright-langserver --stdio
 	cmd is executable: true (checked by nvim-lsp-installer)
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: sumneko_lua, pyright, ccls
```

### LspLog

```Text
Nope
```

### Healthcheck

```Text
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - OK: **luarocks**: `/opt/homebrew/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.12.1`
  - OK: **node**: `v16.15.1`
  - OK: **python3**: `Python 3.10.0`
  - OK: **pip3**: `pip 21.2.3 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 16.0.1`
  - OK: **java**: `openjdk version "16.0.1" 2021-04-20`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 2. Remaining: 58. Limit: 60. Reset: Mon Jul  4 21:51:27 2022.
```

**Comment by williamboman** [comment]
Hello! Have you verified that you set up nvim-lsp-installer before you set up any servers via lspconfig?

**Comment by williamhCode** [comment]
Yep! I just retried everything, setting up nvim-lsp-installer before I set up lspconfig.

**Comment by williamboman** [comment]
Hm. How does your setup code look like?

**Comment by williamhCode** [comment]
lsp-config setup
```lua
require('lspconfig').pyright.setup {
    settings = {
        python = {
            analysis = {
                typeCheckingMode = 'off'
            }
        }
    }
}
require('lspconfig').ccls.setup {}
require('lspconfig').sumneko_lua.setup {}
```

nvim-lsp-installer setup
```lua
require("nvim-lsp-installer").setup {
    automatic_installation = true, -- automatically detect which servers to install (based on which servers are set up via lspconfig)
    ui = {
        border = "rounded"
    }
}
```

They are properly required by the init.lua file.

**Comment by Integralist** [comment]
I'm having a similar issue. Things worked fine with vimscript but then I ported my setup over to lua and now I'm getting this issue with (for example terraform related lsps):

<img width="1055" alt="Screenshot 2022-07-08 at 11 57 09" src="https://user-images.githubusercontent.com/180050/177979401-edb3ef7f-24f2-4e11-aea5-f03c80167be9.png">

My configuration can be seen [here](https://github.com/Integralist/dotfiles/blob/main/.config/nvim/lua/plugin-manager.lua#L132-L136) and [here](https://github.com/Integralist/dotfiles/blob/main/.config/nvim/plugin/lsp-config.lua#L120-L127).

**Comment by williamboman** [comment]
Thanks for sharing the source, leaves the guesswork out! So you set up nvim-lsp-installer within the `config` hook provided by packer, and you set up lspconfig servers inside a plugin/ script - which executes first? I find it to be much easier to just colocate the setups in the same file, making sure to put `nvim-lsp-installer` before any lspconfig interactions. If you want them separate you'll have to look into in which order things are executed and ensure nvim-lsp-installer's setup executes first.

Also, with my new plugin https://github.com/williamboman/mason.nvim this tight coupling with lspconfig will no longer be a thing, if you want to give it a try

**Comment by Integralist** [comment]
Hi @williamboman thanks for this info. Looks like you were right. I added a print statement to both areas of the code and the files in plugin/ were being loaded first before my lua/plugin-manager.lua file.

So I decided to co-locate the setup/configuration, here:
https://github.com/Integralist/dotfiles/blob/main/.config/nvim/lua/plugin-manager.lua#L135-L153

And there are no errors, but still the LSP clients aren't attaching 😞 

In fact I think I've messed something else up because the situation is worse and now it doesn't think there are any LSP clients that match the terraform file (see my earlier screenshot compared to the following)
<img width="502" alt="Screenshot 2022-07-08 at 22 05 00" src="https://user-images.githubusercontent.com/180050/178070230-289a39be-17a8-4328-af85-f494df88c52f.png">

**Comment by williamboman** [comment]
Have you ran `:PackerCompile`?

**Comment by Integralist** [comment]
I have just now and that worked! 🎉 Thanks 🙂

Although I'm not entirely sure why only tflint is attached and not the terraform lsp?

<img width="763" alt="Screenshot 2022-07-08 at 22 25 03" src="https://user-images.githubusercontent.com/180050/178072438-af3394f9-6434-4062-a525-ec4c7461847d.png">

**Comment by Integralist** [comment]
WEIRD. I just ran `LspInstallInfo` and saw everything showing as it should.

I then went and ran `LspInfo` and this time it shows two clients attached

<img width="754" alt="Screenshot 2022-07-08 at 22 26 24" src="https://user-images.githubusercontent.com/180050/178072589-3d9585a0-a207-4b6b-a4e8-79ad3e84b93f.png">

**Comment by williamboman** [comment]
Nice :+1:! Sometimes it takes a while for a server to boot up and be ready

**Comment by williamhCode** [comment]
Sorry for the trouble, I just got it to work. Turns out in my init.lua file, I put the lsp-config require before. I thought by setting up nvim-lsp-installer before lsp-config meant plug installing + installing the servers before; the setup require went over my head.
