### ISSUE TITLE
Installation UI not show on MacOS and WSL

### ISSUE THREAD

**Issue by JonasHiltl** [williamboman/nvim-lsp-installer#852]
### Problem description

Every time a Popup is supposed to show, the background dims but the Popup does not appear. I have tested both the `:LspInstallInfo` and `:LspInstall` command and the UI does not show up in both cases. I have tested it on WSL with Windows Terminal and Macos with iTerm2 and both don't work.

My guess is that some other UI settings in neovim causes the Popup to be transparent. Does anybody has an idea which setting could cause this bug?

Here are my [dotfiles](https://github.com/JonasHiltl/.dotfiles/blob/main/nvim/.config/nvim/lua/config/lsp/config.lua) and especially the part where I setup `LspConfig` and the `LspInstaller`

### Neovim version (>= 0.7)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by _nixbld1

### Operating system/version

Tested on Mac and WSL

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

all

### Actual behavior

Popup does not appear so I can't select language servers or confirm the installation of server.

### Expected behavior

The Popup to appear so that I can select Language Servers to install or confirm the installation.

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.17.6 darwin/arm64`
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.1.2`
  - OK: **node**: `v16.13.2`
  - OK: **python3**: `Python 3.9.13`
  - OK: **pip3**: `pip 22.1.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **javac**: `javac 17.0.3`
  - OK: **java**: `openjdk version "17.0.3" 2022-04-19 LTS`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.10.4`
  - OK: **JAVA_HOME**: `openjdk version "17.0.3" 2022-04-19 LTS`
  - OK: GitHub API rate limit. Used: 11. Remaining: 49. Limit: 60. Reset: Tue Jul  5 21:01:58 2022.
```

### Screenshots

https://user-images.githubusercontent.com/71456708/177398641-1630ae7d-40ab-4c4c-bc6b-01bf8f98f0ec.mp4

**Comment by williamboman** [comment]
What neovim frontend do you use? Is it something like neovide or do you run it in a terminal (and in which case which terminal)? Does this happen with other floating windows such as `:PackerStatus` or `:LspInfo`? Does disabling your colorscheme work? Do you use transparent backgrounds?

**Comment by bugabinga** [comment]
I can confirm this issue, but only as long as `dapc11/Shade.nvim` is loaded.
This could very well be an issue in the Shade-plugin.

**Comment by JonasHiltl** [comment]
Same here, it is caused by the `sunjon/shade.nvim` plugin. I will drop it, since it doesn't seem to be maintained anymore.

**Comment by williamboman** [comment]
:+1:
