### ISSUE TITLE
EFM for windows

### ISSUE THREAD

**Issue by lucax88x** [williamboman/nvim-lsp-installer#91]
Ehy, great plugin, been in love so far.

When I work in linux, everything is perfect, however sometimes I have to work on the little VM windows machine, and in there, I cannot install EFM

Failed to spawn process cmd=go pid=ENOENT: no such file or directory

**Comment by lucax88x** [comment]
looking at the code, maybe I need to install a go globally?

**Comment by lucax88x** [comment]
Yea, after installing go it worked.

Maybe would be a good idea to provide a better error in case go is not installed?

**Comment by williamboman** [comment]
Hey! Yep the error message could be better for sure! In fact there already exist an [ensure_executables](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/installers/std.lua#L118-L130) that we could easily compose into all the `go`, `npm`, `pip3`, ... installers.
