### ISSUE TITLE
LspInstall installs nothing and cannot easily see installation logs

### ISSUE THREAD

**Issue by wookayin** [williamboman/nvim-lsp-installer#96]
```
:LspInstall pyright
```

After executing this, `:LspInstallInfo` says that the `pyright` server is installed successfully (installed today).

However, lsp servers can't start:

```
cmd ["$HOME/.local/share/nvim/lsp_servers/python/node_modules/.bin/pyright-langserver"] is not executable.
```

In the directory `$HOME/.local/share/nvim/lsp_servers/` folders like `python`, `tsserver`, etc. are created but they are **just empty directories**.

FYI, I am using macOS and my neovim version is `NVIM v0.6.0-dev+1556-gc642f3ac2                                                                                                  `.

Plus, I cannot find any relevant log files; I wanted to show **the output of installer scripts** but apparently the GUI window doesn't have any feature. How can I debug this?

**Comment by williamboman** [comment]
Hey! That sounds really weird indeed... What are your `Node` and `npm` versions? Also are you able to successfully `LspUninstall` these servers? What plugin version are you on?

> Plus, I cannot find any relevant log files; I wanted to show the output of installer scripts but apparently the GUI window doesn't have any feature. How can I debug this?

Yeah there are no [structured logging in place](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/log.lua) today unfortunately 😬. The stdout/stderr buffers are released if a server is successfully installed, and are only expanded in the GUI should a server fail to install.

Just for the sake of ruling out possibilities, are you able to properly install `pylsp` (installs via pip) or perhaps `rust_analyzer`, `clangd`, `elixirls` (sort of random servers that are not npm based)?

**Comment by wookayin** [comment]
I am on the current latest `main` branch: a75b8df.

I was using node v16.5.0 and npm 7.19.1 --- running `npm install pyright` or any node command works without any problems. node and npm are on the global $PATH (e.g. `/usr/local/bin/node`) so they should be runnable in neovim as well. Indeed, `!which npm` returns the correct path.

I tried `rust` and `clangd` (which doesn't use npm) and they work well for me. I see `lsp_servers/rust/rust-analyzer` and `clangd/clangd_12.0.1`. So this should be probably node-related issue for me.

**Comment by williamboman** [comment]
> :LspUninstall works -- I think it simply removes the directory.

Cool :+1:. Yeah it just removes the directory, just wanted to rule out potential permission errors.

> * Even if I didn't have pyright installed, `npm install pyright` will not install node modules into `stdpath("data")/lsp_servers/python/...`. I think the command does nothing on this directory; wouldn't it install node modules globally or on some different path? The npm installer should be transparent to global `node` and `npm` (as https://github.com/kabouzeid/nvim-lspinstall does).

This is really odd behavior though. It should be installing the provided packages in the current working directory, which in the case of `pyright` is `stdpath("data")/lsp_servers/python`. Only if you provide the `global` option to `npm` will it install in the "global" path. It also should not care about any globally installed packages - if anything it might just speed up the installation as the package might already be cached locally. But it should always produce a `node_modules` output. This plugin doesn't (intentionally) install, or in any way modify, anything outside of `stdpath("data")/lsp_servers`

Could you try reverting the nvim-lsp-installer to either dbe99dd012217c872fc257ab4214ee7eadc8fd42 or 31f77fc8d638001a1dc548e45580714b9a63d3f2 and see if it makes `pyright` actually install? If it doesn't, I am wondering if you maybe have some npm configuration that might be overriding some default behavior. Would you mind sharing the output of `$ npm config ls -l`?

**Comment by wookayin** [comment]
I figured out why. From https://stackoverflow.com/questions/14032160/npm-install-module-in-current-directory

> Locally: npm looks for an existing folder called node_modules in the current directory and creates a folder for each package you install in that folder. If it can't find an existing node_modules folder here, **it then looks through the current directory's ancestors until it finds one**. If it can't find one, it creates one in the current directory.

I somehow happened to have `$HOME/node_modules` and that was why -- the package were being installed there. I didn't know this until today! Although after removing that directory I find `npm install pyright` still install the packages on `~/node_modules` because I had `$HOME/package.json` as well.

Bottomline: I removed `$HOME/node_modules` and `$HOME/package.json` (which had been created accidentally) and it works now well. To avoid such errors, I think you need to **first make sure `package.json` exists in the current LSP servers directory (e.g. `.../nvim/lsp_servers/python`) before running `npm install`.

Indeed, https://github.com/kabouzeid/nvim-lspinstall does the thing in the right way:
```
  install_script = [[
  ! test -f package.json && npm init -y --scope=lspinstall || true
  npm install pyright@latest
  ]]
```

So you'll need to have `npm init -y --scope=...`.

**Comment by williamboman** [comment]
Ahh of course! Will fix asap, nice catch :)

**Comment by williamboman** [comment]
#97 ought to fix this, was able to repro locally and tested the fix

**Comment by wookayin** [comment]
Thank you very much for such a fast response and patch!

**Comment by williamboman** [comment]
Hehe thanks! This particular issue makes me reconsider running the installation in a tempdir and only upon successful completion move it to the stdpath location. I remember there being some cross platform difficulties with doing so though.

**Comment by kylo252** [comment]
Thanks for fixing this! I'm in the middle of transitioning LunarVim to use this, so I got worried that none of the node servers are going to install correctly 😄
